### ISSUE TITLE
Allow model to be loaded into memory on launch

### ISSUE THREAD

**Issue by RitwikGopi** [RasaHQ/rasa_nlu#1017]
**Rasa NLU version**: 0.12.0

**Operating system** (windows, osx, ...): Ubuntu

**Content of model configuration file**:
```yml
language: "en"

path: "./projects"

fixed_model_name: "model"

pipeline:
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_duckling"
- name: "intent_entity_featurizer_regex"
```

**Issue**: When I am running the rasa as a server it is not loading the models in to the memmory untill I make the first parse call. Any idea why? It would have been a really good feature
