### ISSUE TITLE
map words to entities

### ISSUE THREAD

**Issue by disimone** [RasaHQ/rasa_nlu#1084]
**Rasa NLU version**:
commit 3d736227e3439ab745126263e8431e875b1882cd
**Operating system** (windows, osx, ...):
linuc
**Content of model configuration file**:
```yml
language: "de"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_spacy"
- name: "ner_synonyms"
- name: "ner_duckling"
- name: "intent_classifier_sklearn"

```

**Issue**:
Hi all,

I am working on a chatbot for some very specific topic. In my context, some specific words can be always associated to a domain-specific entity. For those special keywords there is in principle no need to train at all. What is the recommended way to instruct the NLU model to properly recognize them?

In principle, I would like to provide something like

```
{"entity1": ["word1","word2","word3"],
"entity2": ["word4","word5","word6"]}
```

and be 100% sure that every time "word1" appears, an entity "entity1" is returned. "entity1" may additionally be also recognized by other components (ner_crf for example), but the point is that I also want it to be keyword-based.

Thanks for your help,

Andrea.
