### ISSUE TITLE
Handle negation and mispelling 

### ISSUE THREAD

**Issue by Graziella-Husson** [RasaHQ/rasa_nlu#1091]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): linux

**Content of model configuration file**: (spacy large model en)
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
```

**Issue**:
Sorry if I ask obvious questions but I did'nt find the answer in rasa issues. I'm trying to build a bot with a few intents related to emotionnal and physical well being. I choosed to have intents with bad mood and good mood for each.  I have tested it and come here with some questions.

1) Is there a way to make the bot **detect negation**? If I say 'I'm not very well' it's detected as emotionnal good mood (because of the 'very well' part I think). Do I have to add some examples of negations in the training data?

2) How the **mispelling** stuff is handled ? I tried to detect some entities and use a slot to make my bot saying the entity detected and it seems that the entities are well detected with the mispelling. How does this work? Is it possible to correct ths mispelling in python with a custom action (using some librairies)?
For example: "I have a pain in the arrm", "arrm" is detected as a body part but with its mispelling. Do you know a way to handle this?
