### ISSUE TITLE
Model doesn't save anywhere if no -o arg is given

### ISSUE THREAD

**Issue by jgutta** [RasaHQ/rasa_nlu#1101]
**Rasa NLU version**: 12.3

**Operating system** (windows, osx, ...): OSX, linux

**Content of model configuration file**:
```yml
  language: "en"
  pipeline:
    - name: "nlp_spacy"
      model: "en"
    - name: "tokenizer_spacy"
    - name: "intent_featurizer_count_vectors"
    - name: "intent_classifier_tensorflow_embedding"
      intent_tokenization_flag: false
    - name:   "ner_crf"
      BILOU_flag": true
      features:
      - ["low", "title", "upper", "pos", "pos2", "word3", "digit"]
      - ["low", "upper", "bias", "pos", "pos2", "title", "word3", "digit"]
      - ["low", "title","upper", "pos", "pos2", "word3", "digit"]
      max_iterations: 50
      L1_c: 1
      L2_c: 1e-4

```

**Issue**:
When running training from the command line, if the -o argument is not supplied, the training will run through completely and then throw away the model. Setting the -o argument fixes the saving issue, however in past versions there was a default location to save into.
