### ISSUE TITLE
spaCy NER not working!

### ISSUE THREAD

**Issue by azarezade** [RasaHQ/rasa_nlu#1113]
I wanted to compare the accuracy of `ner_spacy` with `ner_crf`, but after training I get the following  results, which`ner_crf` works very well but `ner_spacy` returns zeros accuracy!
Moreover, `ner_spacy` also shows the entities for its default NER, which is undesirable for me.

<img width="574" alt="screen shot 1397-03-07 at 11 26 06 am" src="https://user-images.githubusercontent.com/11195749/40612787-28ca3d2e-6291-11e8-82f7-1e701aa748b7.png">

<img width="1192" alt="screen shot 1397-03-07 at 11 26 59 am" src="https://user-images.githubusercontent.com/11195749/40612792-2c20d578-6291-11e8-9c55-693462072ee5.png">

**Rasa NLU version**: 0.12.3

**Operating system** : Mac OS X

**Content of model configuration file**:
```yml
language: "fa"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
```
