### ISSUE TITLE
Intents never recognized

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/rasa_nlu#1120]
```
**Rasa NLU version**:

(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ pip list :
Package             Version    
------------------- -----------
...
rasa-core           0.9.0      
rasa-nlu            0.12.3
...
```

**Operating system** :

Linux 16.04

**Content of model configuration file**:
```yml
slots:
  location:
    type: text
  mood:
    type: text
  information:
    type: text
  adjective:
    type: text

entities:
 - location
 - mood
 - information
 - adjective

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'
  utter_joy:
    - 'Am so happy for you'
  utter_fear:
    - 'you shouldn be afraid'
  utter_anger:
    - 'Calm down, everything gonna be alright'
  utter_sadness:
    - 'be a tough guy'
  utter_disgust:
    - 'I understand, this is disgusting, we should get over it'
  utter_shame:
    - 'Ridicule does not kill'
  utter_guilt:
    - 'You must not feel guilty, feel proud'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - actions.ActionWeather
 - utter_joy
 - utter_fear
 - utter_anger
 - utter_sadness
 - utter_disgust
 - utter_shame
 - utter_guilt
```

**Issue**:

Having problems with the tutorial, I followed the [climate chatbot rasa tutorial](https://vimeo.com/254777331) provided by Justina Petraityte, you can find the [GitHub repository here](https://github.com/JustinaPetr/Weatherbot_Tutorial). However, my chatbot never recognizes the intent I tried to give it when I try with run_online.py, which has to be the location, 
Indeed, for instance when testing the following sentence "_I had a bad day today_" with : 

```
from rasa_nlu.training_data import load_data
from rasa_nlu import config
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata, Interpreter

def train_nlu(data, configs, model_dir):
	training_data = load_data(data)
	trainer = Trainer(config.load(configs))
	trainer.train(training_data)
	model_directory = trainer.persist(model_dir, fixed_model_name = 'weathernlu')

def run_nlu():
	interpreter=Interpreter.load('./models/nlu/default/weathernlu/test')
	print(interpreter.parse(u"I am planning my holiday to Lithuania. I wonder what is the weather out there."))
	
if __name__ == '__main__':
	#train_nlu('./data/data.json', 'config_spacy.json', './models/nlu')
	run_nlu()
```
He wasn't able to recognize it : 

```
(MoodEnv) mike@mike-thinks:~/Programing/Rasa/Moodbot$ python3 nlu_model.py 
/home/mike/Programing/Rasa/Moodbot/MoodEnv/lib/python3.5/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from './models/nlu/default/weathernlu/test/entity_synonyms.json'
  "".format(entity_synonyms_file))
{'intent_ranking': [], 'text': 'I am planning my holiday to Lithuania. I wonder what is the weather out there.', 'entities': [], 'intent': None}
```

You can find the `training_data.json` file [here](https://api.myjson.com/bins/19hufa) and metadata.json [there](https://api.myjson.com/bins/aypc6)
