### ISSUE TITLE
Dialogflow entities are not considered. Expecting a utterances covering each entity value

### ISSUE THREAD

**Issue by ashwinbiyani** [RasaHQ/rasa_nlu#1124]
**0.12**:

**windows**

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
```

**Issue**:
We have exported all the data from API AI and extracted into a local folder. Now, running rasa train command and pointing to that folder.

The folder has intents, intents_usersay values and also entities names and values.

When we train command all the user_say values are converted and training data and also additionally synonyms are considered too but an exhaustive list of entity values are ignored and only user say values considered.

For Example:

Intent : greet
intent_user_says : 
hi ashwin
hello rasa

entity name : username
entity values:
rasa
ashwin
jack
jim

**when we ask a question: hello jack** 
It is not categorizing jack under username many a time. looks like it is expecting me to define utterances for each entity value rather than we define one utterance covering all the exhaustive entities and while building a model it picks up all the exhaustive values of each entity and train. 

Please let me know if I am missing something here.
