### ISSUE TITLE
Failed to validate at component "ner_crf". Missing property: "spacy_doc"

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_nlu#1139]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): OSX 10.11.6

**Content of model configuration file**: 
```
language: "fr"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

**Training data**: 
```
{
  "text":"Bonjour",
  "intent":"greet",
  "entities":[

  ]
},
{
  "text":"Bonjour. Je suis Développeur depuis environ 5 ans dans marseille",
  "intent":"greet+inform",
  "entities":[
    {
      "start":17,
      "end":28,
      "value":"Développeur",
      "entity":"job"
    },
    {
      "start":44,
      "end":49,
      "value":"5 ans",
      "entity":"experienceYears"
    },
    {
      "start":55,
      "end":64,
      "value":"marseille",
      "entity":"city"
    }
  ]
},
{
  "text":"Je suis Développeur depuis environ 5 ans dans marseille",
  "intent":"inform",
  "entities":[
    {
      "start":17,
      "end":28,
      "value":"Développeur",
      "entity":"job"
    },
    {
      "start":44,
      "end":49,
      "value":"5 ans",
      "entity":"experienceYears"
    },
    {
      "start":55,
      "end":64,
      "value":"marseille",
      "entity":"city"
    }
  ]
}
```

**Issue**:  
Hello, I am trying to work with Multiple Intents ( in a sentence ) and I am getting this error: "Failed to validate at component "ner_crf". Missing property: "spacy_doc" " 
Any help?

**Comment by MinhMinnie** [comment]
Can anyone help me?

**Comment by wrathagom** [comment]
On 0.12.3 `ner_crf` relies upon spacy pre-processing. Please modify your pipeline to look like this:

```
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "tokenizer_whitespace"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

Alternatively you could switch to running from master and the CRF without the spacy dependent features thanks to this PR. https://github.com/RasaHQ/rasa_nlu/pull/1095
