### ISSUE TITLE
Failed to load synonyms file entity_synonyms.json

### ISSUE THREAD

**Issue by weizhenzhao** [RasaHQ/rasa_nlu#1146]
**Rasa NLU version**:latest

**Operating system** (windows, osx, ...):linux

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_mitie"
  model: "data/total_word_feature_extractor.dat"
- name: "tokenizer_mitie"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_classifier_mitie"
```

**Issue**:
I met an error when I post an messge to the server it writes as follow

[root@localhost rasa_nlu]# python -m rasa_nlu.server --path projects
2018-06-10 11:40:04+0800 [-] Log opened.
2018-06-10 11:40:04+0800 [-] Site starting on 5000
2018-06-10 11:40:04+0800 [-] Starting factory <twisted.web.server.Site object at 0x7f079f72c630>
2018-06-10 11:40:10+0800 [-] /usr/local/python3/lib/python3.6/site-packages/h5py/__init__.py:36: builtins.FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
2018-06-10 11:40:11+0800 [-] /root/rasa_nlu/rasa_nlu/extractors/entity_synonyms.py:85: builtins.UserWarning: Failed to load synonyms file from '/root/rasa_nlu/projects/default/model_20180608-012640/entity_synonyms.json'
2018-06-10 11:40:12+0800 [-] "127.0.0.1" - - [10/Jun/2018:03:40:12 +0000] "POST /parse HTTP/1.1" 200 194 "-" "curl/7.29.0"
^C2018-06-10 11:44:00+0800 [-] Received SIGINT, shutting down.
2018-06-10 11:44:00+0800 [twisted.web.server.Site] (TCP Port 5000 Closed)
2018-06-10 11:44:00+0800 [-] Stopping factory <twisted.web.server.Site object at 0x7f079f72c630>
2018-06-10 11:44:00+0800 [-] Main loop terminated.
[root@localhost rasa_nlu]# ^C
[root@localhost rasa_nlu]# 

so I have an check at the projects folder
there's no entity_synonyms.json
files in the folder are:
entity_extractor.dat
intent_classifier.dat
metadata.json
regex_featurizer.json
training_data.json

So can you help me to solve this issue?

Thank you very much
WeiZhen
