### ISSUE TITLE
Failed to validate at component 'ner_crf'. Missing property: 'spacy_doc'

### ISSUE THREAD

**Issue by reza-ebrahimi** [RasaHQ/rasa_nlu#1151]
**Rasa NLU version**: master branch

**Operating system** (windows, osx, ...): ubuntu 18.04 (based on docker image)

**Content of model configuration file**:
```yml
language: "fa"
pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
    features: [["low", "title"], ["bias", "suffix3"], ["upper"]]
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"
    intent_tokenization_flag: true
    intent_split_symbol: "_"
```

**Issue**: It throws an exception and exiting: `Exception: Failed to validate at component 'ner_crf'. Missing property: 'spacy_doc'`

I'm aware of PR #1095 and the code I'm testing on has PR #1095 commits, but it fails to launch with an exception.

The command below is also part of my `Dockerfile` that downloads and installs `rasa_nlu`:

```dockerfile
RUN git clone https://github.com/RasaHQ/rasa_nlu.git && \
    cd rasa_nlu/ && \
    pip install -r alt_requirements/requirements_bare.txt && \
    pip install -r alt_requirements/requirements_spacy_sklearn.txt && \
    pip install -r alt_requirements/requirements_tensorflow_sklearn.txt && \
    pip install -e .
```
