### ISSUE TITLE
How to support misaligned entity annotation

### ISSUE THREAD

**Issue by 91ns** [RasaHQ/rasa_nlu#1152]
**Rasa NLU version**:
0.12.3

**Operating system** (windows, osx, ...):
Ubuntu

**Content of model configuration file**:
```yml
language: "en"

pipeline: 
- name: "nlp_spacy"
  model: "xx_ent_wiki_sm"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"

- name: "ner_crf"
- name: "ner_synonyms"
```

**Issue**:

I get the following warning when I try to train my model for NER. 

 WARNING  rasa_nlu.extractors.crf_entity_extractor - Misaligned entity annotation in sentence { }. Make sure the start and end values of the annotated training examples end at token boundaries (e.g. don't include trailing whitespaces).

The problem is, sometimes the entities can be a part of a token, therefore it won't start and end at the token's boundaries. Is there a template that supports this case?
