### ISSUE TITLE
Entity recognition assigns wrong values to entities

### ISSUE THREAD

**Issue by griffonn** [RasaHQ/rasa_nlu#1161]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): Windows 10

**Content of model configuration file**:
```yml
language: "en"
pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
  - name: "ner_crf"
```

**Issue**:
Hi, I'm trying to train an entity/intent recognizer using the above pipeline.
Currently I focus only on entity recognition, so my training data has single intent and about 10 different entities (most of which have closed domain with anywhere between 4 and 20 possible values; e.g. for an entity "Size" the value can be "extra small, small, medium, large, extra large".
I start with only three entities (size - 5 possible values, price - 9 possible values, season - 4 possible values), and generate about 5000 training examples - sentences which include all three entities with random value combination; the sentences are in one of 14 possible "patterns" - in means of which words appear in it apart the values for the entities, mostly search query-like.
But when I test the resulting model, if the test sentence is not of the "format" that was in training data (i.e. the words which are unrelated to any of the entities are different, or in different order), the model makes a lot of mistakes: assigns values from different entities to the same entity, assigns one of the unrelated words to an entity while missing the real value for that entity, etc).
Example test sentence: "find me an extra large affordable winter dress"
Result: size: extra large, size:affordable, season:winter

What can I do to improve the performance of my model?
