### ISSUE TITLE
Duckling language changes when another project trains a model in a different language

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_nlu#1164]
**Rasa NLU version**: 0.12.x

**Issue**:

On an instance having projects with models trained with different languages (e.g one project in FR one in EN)
Steps:
- Train EN Project -> Train FR Project
Observe:
Duckling catches FR structured entities in the EN project (i.e. Duckling will catch "Demain" but not "Tomorrow" in the EN project

**Comment by souvikg10** [comment]
did you mention the locale? I have two rasa-Nlu config basically that connects to duckling over http with an additional parameter for locale
```
language: "fr"

pipeline:
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values

- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_spacy"
- name: "ner_synonyms"
- name: "ner_duckling_http"
  locale: "fr_Nothing"
  url: "http://duckling:8000"
- name: "intent_classifier_sklearn"
```
