### ISSUE TITLE
newbie learning rasa_nlu with unsupported language (bahasa indonesia)

### ISSUE THREAD

**Issue by Primtek** [RasaHQ/rasa_nlu#1195]
**Rasa NLU version**:
0.12.3
**Operating system** (windows, osx, ...):
centOS 7
**Content of model configuration file**:
```yml
vi nlu_config.yml
language: "en"
pipeline: "spacy_sklearn"

```

**Issue**:
I am new to rasa_nlu and I m in the progress learning it.. but it does not support our language (bahasa Indonesia).. could anybody here please info complete reference for applying unsupported language (better if someone here already used bahasa indonesia in rasa_nlu)

huge thanks in advance

Regards
Wi
