### ISSUE TITLE
Ner_CRF not working for French

### ISSUE THREAD

**Issue by wayneguolei** [RasaHQ/rasa_nlu#1200]
**Rasa NLU version**:
0.12.2
**Operating system** (windows, osx, ...):
OSX
**Content of model configuration file**:
```yml
language: "fr"
pipeline: 
- name: "nlp_spacy"
  model: "fr"
- name: "tokenizer_spacy"
- name: "ner_crf"
  BILOU_flag: true
  features:
    # features for word before token
    - ["low", "title", "upper", "pos", "pos2"]
    # features of token itself
    - ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"]
    # features for word after the token we want to tag
    - ["low", "title", "upper", "pos", "pos2"]
  max_iterations: 50
  L1_c: 1
  L2_c: 1e-3
- name: "ner_synonyms"
```

**Issue**:
Hi, I tried to use ner_crf to train NER on my french corpus, but it seems it doesn't work on the French corpus:
![image](https://user-images.githubusercontent.com/17290769/42168352-0c1ddb40-7e11-11e8-9479-d9da33ae6c1b.png)
And then I changed the config file to see if ner_crf works on English model, it seems it works well:
![image](https://user-images.githubusercontent.com/17290769/42168539-88ff103e-7e11-11e8-909f-0792dfe3c969.png)
