### ISSUE TITLE
Incorrect slots are getting filled during online training

### ISSUE THREAD

**Issue by Ujjwalsas9** [RasaHQ/rasa_nlu#1201]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): windows 7

**Content of model configuration file**:
```yml
intents:
    - helper_clothing
    - greet
    - deny
    - accept
    - coloryes
    - None
entities:
    - dress
    - agerange
    - category
    - greet
    - brand
    - color
    - budget
slots:
    dress:
        type: text
    agerange:
        type: categorical
        values:
        - infant
        - teenage
        - young
        - mature
        - elders
    category:
        type: categorical
        values:
        - men
        - women
        - kids
    brand:
        type: text
    color:
        type: text
    budget:
        type: categorical
        values:
        - below 1500
        - between 1500 to 5000
        - more than 5000
    matches:
        type: unfeaturized
templates:
    utter_greet:
        - 'Hello! Welcome to Pantaloons! How may I help you?'
    utter_ask_brands:
        - 'Do you have any brands in mind?'
    utter_ask_category:
        - text: "Could you please specify the category:"
    utter_ask_age:
        - text: "What is the age of the person?"
    utter_ask_budget:
        - text: "Do you have any budgets in mind?"
    utter_ask_color:
        - text: "Do you have any color preferences?"
    utter_ask_gender:
        - text: "What is the gender of the person?"
    utter_suggest:
        - text: "I would suggest you to buy Armani Jeans. It would cost you INR 15000. But we have a discount of 10% on it if you have Citi Bank Credit Card. It looks like:"
          image: "https://goo.gl/images/RhgvCi"
    utter_bye:
        - 'Goodbye! I will wait to see you again. Enjoy your time.'
actions:
        - utter_greet
        - utter_ask_category
        - utter_ask_age
        - utter_ask_budget
        - utter_ask_gender
        - utter_bye
        - utter_suggest
        - utter_ask_color
        - actions.ActionOrderCloth
```

**Issue**:
While online training, I realized that, incorrect slots are getting filled. Please let me know if you have any ideas on what I am missing here. Thanks in advance!
