### ISSUE TITLE
Preprocessing user input in Rasa NLU

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_nlu#1208]
**Rasa NLU version**: 0.13.0a2

**Operating system** (windows, osx, ...): Ubuntu

**Content of model configuration file**:
```
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "sentiment_textblob"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

**Issue**:
My bot only can predict inputs like : "hello" as "greet" intent but when I input "helloooooooooo" , the bot falls to "fall back" action. I want "hellooooooo" is predicted to "greet" intent. Should I add a new component to RASA NLU to preprocess user inputs ?
