### ISSUE TITLE
ner_spacy not extracting PERSON entity.

### ISSUE THREAD

**Issue by devansh1497** [RasaHQ/rasa_nlu#1212]
<img width="1277" alt="screen shot 2018-07-05 at 21 16 22" src="https://user-images.githubusercontent.com/29357469/42333597-c90c2e58-8098-11e8-941f-d169e2128f38.png">
 

**Rasa NLU version**:0.8

**Operating system** (windows, osx, ...):3.6.4

**Content of model configuration file**:
```yml
slots:
  all_issues:
    type: text
  bugs:
    type: text
  stories:
    type: text
  project_name:
    type: text
    initial_value: "FAE"
  med_pri:
    type: text
  low_pri: 
    type: text
  high_pri:
    type: text
  PERSON:
    type: text
intents:
 - greet
 - goodbye
 - inform
 - anything_else
 - find_count
entities:
 - all_issues
 - bugs
 - stories
 - project_name
 - low_pri
 - med_pri
 - high_pri
 
templates:
      
  utter_greet:
    - 'Hello! How can I help?'
    - 'Hi!'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye!'
  utter_anything_else:
    - "Can I help you with anything else?"
    - "Anything else?"
    - "Do you need anything else?"

actions:
 - utter_greet
 - utter_goodbye
 - utter_anything_else
 - actions.ActionIssue
 - actions.ActionCount 

```
config.json
```
{
"pipeline" : ["nlp_spacy",
"tokenizer_spacy",
"intent_entity_featurizer_regex",
"intent_featurizer_spacy",
"ner_spacy",
"ner_crf",
"ner_synonyms",
"intent_featurizer_ngrams",
"intent_classifier_sklearn"

],
	
	"language" : "en",

	"path": "./models/nlu",

	"data": "./data/testData.json"


}

```
**Issue**:
I am unable to extract the PERSONS entity using ner_spacy. I have tried various examples but to no avail.
