### ISSUE TITLE
why I only able to parse intent greet and bye?

### ISSUE THREAD

**Issue by Primtek** [RasaHQ/rasa_nlu#1225]
**Rasa NLU version**:
0.12
**Operating system** (windows, osx, ...):
centOS 7
**Content of model configuration file**:
config.yml

```
language: "en"

pipeline:
 - name: "tokenizer_whitespace"
 - name: "intent_featurizer_count_vectors"
 - name: "intent_classifier_tensorflow_embedding"
   intent_tokenization_flag: true
   intent_split_symbol: "+"
```

domain.yml

```
intents:
   - greet
   - goodbye
   - claimreport

templates:
   utter_greet:
     - text: "Hey, I m Bot"
   utter_goodbye:
     - text: "Thank you, bye :)"
   utter_claimreport:
     - text: "For claim reporting, I would ask you some questions blah blah blah"
   
actions:
   - utter_greet
   - utter_goodbye
   - utter_claimreport
```

data/nlu_data.md  

```
## intent:greet
   - hi
   - hey
   - hallo
   - halo
   - hello
## intent:goodbye
   - bye
   - goodbye
   - good bye
## intent:claimreport
   - accident
   - lost
   - theft
```

data/stories.md

```
## story 1
  * greet
     - utter_greet
  * claim_report
      - utter_claim_report
  * goodbye
     - utter_goodbye
```

**Issue**:

why I only able to parse intent greet and bye?

when parsing greet and bye intent, it returns correctly (name of the intent shown), but if I parse claimreport intnet the name of intent shown null..

== trying to parse greet and bye intent ==
```
[root@ai learn04]# curl -XPOST localhost:5000/parse -d '{"q":"hey"}'
{
  "project": "default",
  "entities": [],
  "model": "fallback",
  "intent": {
    "confidence": 1.0,
    "name": "greet"
  },
  "text": "hey"
}[root@ai learn04]# curl -XPOST localhost:5000/parse -d '{"q":"bye"}'
{
  "project": "default",
  "entities": [],
  "model": "fallback",
  "intent": {
    "confidence": 1.0,
    "name": "goodbye"
  },
  "text": "bye"

== trying to parse claimreport intent ==
}[root@ai learn04]# curl -XPOST localhost:5000/parse -d '{"q":"accident"}'
{
  "project": "default",
  "entities": [],
  "model": "fallback",
  "intent": {
    "confidence": 1.0,
    "name": null
  },
  "text": "accident"
}[root@ai learn04]# curl -XPOST localhost:5000/parse -d '{"q":"lost"}'
{
  "project": "default",
  "entities": [],
  "model": "fallback",
  "intent": {
    "confidence": 1.0,
    "name": null
  },
  "text": "lost"
}[root@ai learn04]# curl -XPOST localhost:5000/parse -d '{"q":"theft"}'
{
  "project": "default",
  "entities": [],
  "model": "fallback",
  "intent": {
    "confidence": 1.0,
    "name": null
  },
  "text": "theft"
[root@ai learn04]#
```
