### ISSUE TITLE
particular format of number is matching

### ISSUE THREAD

**Issue by Sharma-Saravanan** [RasaHQ/rasa_nlu#1230]
**Rasa NLU version**:0.12.3

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Content of model configuration file**: 
```yml
language: "en"


pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"
```

**Issue**:

my intent training data has been included the following data
           {{ firstName | limitTo: 7 }}{{firstName.length > 7 ? '...' : ''}} 
once the data is trained, while testing this intent is matching for the input **20/7/2018**
