### ISSUE TITLE
pipeline error tensorflow_embedding 

### ISSUE THREAD

**Issue by tushar1328** [RasaHQ/rasa_nlu#1234]
## Getting error " Exception: Failed to validate at component 'ner_crf'. Missing property: 'spacy_doc' "
I am Using latest version of RASA-CORE and RASA-NLU
```
language: "en"
pipeline:

    name: "tokenizer_whitespace"
    name: "ner_crf"
    name: "intent_featurizer_count_vectors"
    name: "intent_classifier_tensorflow_embedding"
    intent_tokenization_flag: true
    intent_splitsymbol: ""
```
