### ISSUE TITLE
Wrong Intent classification of short terms

### ISSUE THREAD

**Issue by donnercody** [RasaHQ/rasa_nlu#1238]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): windows

**Content of model configuration file**:
```yml
language: "C:/...../de_core_news_sm-2.0.0"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
```

**Issue**:
Hi,

i am a very big fan of rasa and for us it works fine in long sentences intent classification.

We have big trouble in "short term" classification.

For example if we try to recognize "accept" and "deny" (in german: akzeptieren / ablehnen) than we get wrong confidence. 

The query was "akzeptieren" (our training model is attached and contains this word)
**Query: "akzeptieren"
intent: "deny", confidence: 0.7709115983848002**

`{
    "intent": {
        "name": "deny",
        "confidence": 0.7709115983848002
    },
    "entities": [],
    "intent_ranking": [
        {
            "name": "deny",
            "confidence": 0.7709115983848002
        },
        {
            "name": "accept",
            "confidence": 0.22908840161519992
        }
    ],
    "text": "akzeptieren",
    "project": "default",
    "model": "model_20180716-101727"
}`

What can we do in this case? What did we wrong?

We also tried this with an older rasa version and got same experience.

Thanks for your help.

Here is the training data
[rasa-data.json.txt](https://github.com/RasaHQ/rasa_nlu/files/2196902/rasa-data.json.txt)
