### ISSUE TITLE
Regex not improving accuracy

### ISSUE THREAD

**Issue by atotalnoob** [RasaHQ/rasa_nlu#1248]
Rasa NLU version: 0.12.2

Operating system (windows, osx, ...): Windows Server 2012 R2

Content of model configuration file:
Server YML:
language: "en"

pipeline:

name: "nlp_spacy"
name: "tokenizer_spacy"
name: "intent_featurizer_spacy"
name: "ner_crf"
features: [["low", "title"], ["bias", "word3"], ["upper", "pos", "pos2"]]
name: "ner_synonyms"
name: "intent_classifier_sklearn"
name: "intent_entity_featurizer_regex"
name: "ner_duckling_http"
url: "url"
dimensions: [ "time", "number", "duration"]
Training YML:
language: "en"

pipeline:

name: "nlp_spacy"
name: "tokenizer_spacy"
name: "intent_featurizer_spacy"
name: "ner_crf"
features: [["low", "title"], ["bias", "word3"], ["upper", "pos", "pos2"]]
name: "ner_synonyms"
name: "intent_classifier_sklearn"
name: "intent_entity_featurizer_regex"
name: "ner_duckling_http"
url: "url"
dimensions: [ "time", "number", "duration"]
data: {Data Goes Here}

**Issue**:
Adding regex does not affect intent accuracy or entity extraction. 

My model has around 50 intents in it (each with 10-20 examples) and my accuracy on each intent is quite low (around 10% on average). 

Only like 3-4 intents were getting misclassified.

So to improve accuracy/classify correct, I added more examples, which causes everything to shift and misclassify things. Making the issue larger than before.  

 So, since the misclassifications were mostly on one/two word examples. Example (I'll keep using this example throughout for consistency, it isn't just limited to this): "Audit Report" gets classified as "Audit Control Matrix." For ease, let's assume the intents are just camel cased, so auditReport and auditControlMatrix.

Initially I added regex like this:

```
"regex_features":
[
{
"name": "AuditReport",
"pattern": "^[Aa]udit [Rr]eport$"
}
]
```

This resulted in the EXACT same confidences (Only checked the top 3). 

I then made it into an entity, to see if this would work. 

```
"common_examples":
[
{
"text": "audit report",
"intent": "auditReport",
"entities":[
"start":0,
"end":12,
"value":"audit report",
"entity":"auditReport"
]
}
]
```
Retrained and this resulted into the exact same confidence. 

Why?

**Comment by akelad** [comment]
Ok so disregarding the regexes for a second, if you have 50 intents, I'd say you need **at least** 50 examples per intent - how many do you have now? Also, it sounds like your intents overlap a lot - that's probably the root cause of the issue. It's hard to say much more without seeing all the data, but you could try a) merging some intents and using entities to distinguish stories instead or b) try the tensorflow_embedding pipeline and see if that works any better

**Comment by atotalnoob** [comment]
Alright. Is there a rule of thumb for the amount of examples for each intent based on how many intents you have? 

I have around 10-20 per right now. I've used the entity as a "designator" in some of the truly similar ones.

I am adding tensorflow embedding as we speak. Are there any suggestions or recommended configurations to give me a jumping off point? I kinda used whats in the docs. Are all of my components in a good order?

My new pipeline: 
```
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- features: [["low", "title"], ["bias", "word3"], ["upper", "pos", "pos2"]]
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "intent_entity_featurizer_regex"
- name: "ner_duckling_http"
  url: "http://sd-bd3a-cb86:5006/"
  dimensions: [ "time", "number", "duration"] 
- name: "intent_featurizer_count_vectors"
  "min_ngram": 1
  "max_ngram": 1
- name: "intent_classifier_tensorflow_embedding"
  "num_hidden_layers_a": 2
  "hidden_layer_size_a": [256, 128]
  "num_hidden_layers_b": 0
  "hidden_layer_size_b": []
  "batch_size": 32
  "epochs": 300
  # embedding parameters
  "embed_dim": 10
  "mu_pos": 0.8  # should be 0.0 < ... < 1.0 for 'cosine'
  "mu_neg": -0.4  # should be -1.0 < ... < 1.0 for 'cosine'
  "similarity_type": "cosine"  # string 'cosine' or 'inner'
  "num_neg": 10
  "use_max_sim_neg": true  # flag which loss function to use
  # regularization
  "C2": 0.002
  "C_emb": 0.8
  "droprate": 0.2
  # flag if to tokenize intents
  "intent_tokenization_flag": false
  "intent_split_symbol": "_"
```
