### ISSUE TITLE
Unable to extract entities in arabic chatbot

### ISSUE THREAD

**Issue by balinda-1995** [RasaHQ/rasa_nlu#1255]
**Issue**:  I am trying to create an arabic chatbot but my model can't extract the entities. I get this error when I test my model on an utterance that contains entities to extract:

`UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-4: ordinal not in `range(128)`

This is my configuration file:
```

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```
