### ISSUE TITLE
Conditional based Intents

### ISSUE THREAD

**Issue by poovarasanvasudevan** [RasaHQ/rasa_nlu#1271]
**Rasa NLU version**: 0.12.3

**Operating system** (windows, osx, ...): windows

**Content of model configuration file**:
```yml
language: en

pipeline:
- name: "nlp_spacy"
- name: "ner_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "core.extractor.NerEntityExtractor"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: "ner_duckling_http"

```

**Issue**:
How can i make conditional based intent selection,
Say for example , i am developing a password reset system, where bot will asks security questions, 

**User1** has 5 security Questions
**User2** has 2 security Questions

I made custom actions to ask security  question by connection our database, how can i choose intents for no of security questions,

Thanks,
