### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 1693: invalid start byte

### ISSUE THREAD

**Issue by kapilkathuria** [RasaHQ/rasa_nlu#1282]
**Rasa NLU version**:
rasa_nlu: 0.12.3

**Operating system** (windows, osx, ...):
Windows 7

**Content of model configuration file**: This is our custom model
```yml
language: "en_nom_ops_t0"

pipeline:
- name: "nlp_spacy"                   # loads the spacy language model
- name: "tokenizer_spacy"             # splits the sentence into tokens
- name: "ner_spacy"                   # uses the pretrained spacy NER model
- name: "intent_featurizer_spacy"     # transform the sentence into a vector representation
- name: "intent_classifier_sklearn"   # uses the vector representation to classify using SVM
```

**Issue**:
Trainer fails to load data if text contains '¥' (Yen) symbol.

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-41-6c4f51ec4195> in <module>()
      5 
      6 # loading the nlu training samples
----> 7 training_data = load_data("nlu.md")
      8 
      9 # trainer to educate our pipeline

~\AppData\Local\Continuum\anaconda3\lib\site-packages\rasa_nlu\training_data\loading.py in load_data(resource_name, language)
     52 
     53     files = utils.list_files(resource_name)
---> 54     data_sets = [_load(f, language) for f in files]
     55     data_sets = [ds for ds in data_sets if ds]
     56     if len(data_sets) == 0:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\rasa_nlu\training_data\loading.py in <listcomp>(.0)
     52 
     53     files = utils.list_files(resource_name)
---> 54     data_sets = [_load(f, language) for f in files]
     55     data_sets = [ds for ds in data_sets if ds]
     56     if len(data_sets) == 0:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\rasa_nlu\training_data\loading.py in _load(filename, language)
     97     """Loads a single training data file from disk."""
     98 
---> 99     fformat = _guess_format(filename)
    100     if fformat == UNK:
    101         raise ValueError("Unknown data format for file {}".format(filename))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\rasa_nlu\training_data\loading.py in _guess_format(filename)
    114     """Applies heuristics to guess the data format of a file."""
    115     guess = UNK
--> 116     content = utils.read_file(filename)
    117     try:
    118         js = json.loads(content)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\rasa_nlu\utils\__init__.py in read_file(filename, encoding)
    201     """Read text from a file."""
    202     with io.open(filename, encoding=encoding) as f:
--> 203         return f.read()
    204 
    205 

~\AppData\Local\Continuum\anaconda3\lib\codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

~\AppData\Local\Continuum\anaconda3\lib\encodings\utf_8_sig.py in _buffer_decode(self, input, errors, final)
     67                        codecs.utf_8_decode(input[3:], errors, final)
     68                     return (output, consumed+3)
---> 69         return codecs.utf_8_decode(input, errors, final)
     70 
     71     def reset(self):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 1693: invalid start byte
