### ISSUE TITLE
ner_crf + intent_classifier_tensorflow_embedding is dependent on locale settings

### ISSUE THREAD

**Issue by jmrf** [RasaHQ/rasa_nlu#1297]
**Rasa NLU version**: rasa-nlu==0.13.1

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "ner_duckling"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  # flag if to tokenize intents
  intent_tokenization_flag: true
  intent_split_symbol: "_"
  # nn architecture
  num_hidden_layers_a: 1
  hidden_layer_size_a: [64]
  num_hidden_layers_b: 1
  hidden_layer_size_b: [32]
  batch_size: 5
  epochs: 60
  # embedding parameters
  embed_dim: 10
  mu_pos: 0.8  # should be 0.0 < ... < 1.0 for 'cosine'
  mu_neg: -0.4  # should be -1.0 < ... < 1.0 for 'cosine'
  similarity_type: "cosine"  # string 'cosine' or 'inner'
  num_neg: 10
  use_max_sim_neg: true  # flag which loss function to use
  # regularization
  C2: 0.002
  C_emb: 0.8
  droprate: 0.2
```

**Issue**: 

When using the `ner_spacy` together with `intent_classifier_tensorflow_embedding` training might eventually fail depending on the `locale` settings. 
If the locale settings are configured to use a comma (,) instead of a period (.) the training fails showing a long trace ending with an error similar as this one:
```bash
google.protobuf.text_format.ParseError: 48:12 : Message type "tensorflow.AttrValue" has no field named "5".
```
In the Google protobuf implementation, a locale-dependent function is used to convert float to strings what causes problems I guess when `ner_duckling` extracts its dimensions.

So to summarize this happens (at least) when three things co-occur:
* using `ner_spacy`
* using `intent_classifier_tensorflow_embedding`
* locale settings use comma (,) for decimal numbers.

I know this is not a RASA specific error but maybe a warning could be raised or this could be stated in the documentation.

Hope at least this issue could help others in a similar situation.
