### ISSUE TITLE
Tensorflow embedding sensitivity Part2

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1317]
Hey,

I thought words which are not trained have no weight on classification?

But I found, that like:

`amount money`

is corectly classified (word `amount` is not part of training data! Money is though)

But 

`money`

gets a different Intent!

Although it should be same since `amount` was not learned.

My config:

```

language: "de"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"

```
