### ISSUE TITLE
Untrained words influence Tensorflow Embedding 

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#1319]
Hi,

I see some strange things that unseen words within intent classification are changing the intent. Although  Two  diffeernt words (not in training data for intent) give two different intents!
But, one of the word is used for NER_CRF training where I set the intent label to`""` and I thought this is then not used for intent training.  Therefore, it seems that the tensorflow embedding knows this words although the intent label was removed?!

I have a very strong suggestion. Is it possible that the order of the NER_CRF pipeline and the tensorflow embedding pipeline plays a role?

Here the config file:

```

language: "de"


pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
  "stop_words": ['mein','der','die','das','ein']
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: false
  intent_split_symbol: "+"
```

chagning NER_CRF to the end,  yields totally different and correct result such that the word used for entity training is not seen by tensorflow embedding!?

```

language: "de_core_news_sm"


pipeline:
- name: "intent_featurizer_count_vectors"
  "stop_words": ['mein','der','die','das','ein']
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: false
  intent_split_symbol: "+"
- name: "tokenizer_whitespace"
- name: "ner_crf"

```

**Apart from above: I tried now same sentence with few OOVs and everytime I get different intents! SO there seems really an issue.**

Maybe some of default setting in a pipeline like intent_featurizer_count_vectors does the thing. Maybe the standard `token_pattern` plays a role? What is the meaning of it?
