### ISSUE TITLE
Entity Recognition does not work properly.

### ISSUE THREAD

**Issue by azizullah2017** [RasaHQ/rasa_nlu#1321]
**Rasa NLU version**: 0.13.1

**Operating system** (ubuntu 17.10.):

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
  model: "en"
- name: "tokenizer_whitespace"
- name: "tokenizer_spacy"
- name: "ner_synonyms"
- name: "ner_crf"
- name: "intent_entity_featurizer_regex"
  BILOU_flag: true
  features:
    # features for word before token
    - ["low"]
    # features of token itself
    - ["bias", "low", "prefix5", "prefix2", "suffix3", "suffix2", "digit", "pattern"]
    # features for word after the token we want to tag
    - ["low"]
  max_iterations: 50
  L1_c: 0.1
  L2_c: 0.1
- name: "intent_featurizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name: "intent_classifier_sklearn"

```

**Issue**:
The entities are not recognized in all test sentences. 
Some it recognize the entity, some time it does not ?

How much training instances do I need to train to recognize properly ?
