### ISSUE TITLE
some times get {   "error": "The server can't train more models right now!" } while training new models

### ISSUE THREAD

**Issue by gauravbrills** [RasaHQ/rasa_nlu#1323]
**Rasa NLU version**: 0.13.0-full

****:

**Content of model configuration file**:
```yml
language: "en"

pipeline: 
  - name: "nlp_spacy"  
  - name: "tokenizer_spacy"
  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf"
  - name: "ner_synonyms"  
  - name: "ner_spacy"
  - name: "ner_duckling_http"
    dimensions: ["amount-of-money", "distance", "duration", "email", "number", "ordinal", "phone-number", "quantity", "temperature", "time", "unit", "unit-of-duration", "url", "volume"]
  - name: "intent_featurizer_count_vectors" 
  - name: "intent_classifier_tensorflow_embedding" 
    intent_tokenization_flag: true 
    intent_split_symbol: "+"
```

**Issue**:
I do get sometimes
```json
{
  "error": "The server can't train more models right now!"
}
``` 
. I am currently using the latest docker version of rasa . I am not sure this is an issue but is there some limit on the number models we can train ,if yes how we can scale to accommodate more models or should the deployment be specific number of models per container ?
