### ISSUE TITLE
tensorflow embedding intent classifier GPU optimization issue

### ISSUE THREAD

**Issue by princerk** [RasaHQ/rasa_nlu#1324]
**Rasa NLU version**: 0.13.1

**Operating system** (windows, osx, ...): ubuntu

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  "epochs": 3000
```

**Issue**: Training time on GPU and CPU are almost same. I tested this with Nvidia P100 GPU on google club services.
