### ISSUE TITLE
case sensitive

### ISSUE THREAD

**Issue by AdelePh** [RasaHQ/rasa_nlu#1355]
**Rasa NLU version**: 0.13.0a2

**Operating system** (windows, osx, ...): Ubuntu

**Content of model configuration file**:
```yml
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "sentiment_textblob"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```
**Issue**:
in my training data, I have examples:
```
"I am a doctor"
- intent : inform
- entity : job (doctor)

"I am Adele"
- intent : intro
- entity : name (Adele)
```
I want the bot to capture the "name" slot to greet user : Hi {name} but Rasa NLU is getting confused with this case.
