### ISSUE TITLE
unable to train with mixed datatype

### ISSUE THREAD

**Issue by andy51002000** [RasaHQ/rasa_nlu#1363]
**Rasa NLU version**:
"version": "0.13.2"

**Operating system** (windows, osx, ...):
docker
**Content of model configuration file**:
```yml
language: "en"

pipeline: "spacy_sklearn"

# data contains the same json, as described in the training data section
data: {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      }
    ]
  }
}
```

**Issue**:

I tried to train my data using the command from document

```
$ curl -XPOST -H "Content-Type: application/x-yml" localhost:5000/train?project=my_project \
    -d @mydata.yml
```

I got an error below. 

```json
{
    "error": "while parsing a block mapping\n  in \"<unicode string>\", line 1, column 1:\n    language: \"en\"pipeline: \"spacy_s ... \n    ^\nexpected <block end>, but found '<scalar>'\n  in \"<unicode string>\", line 1, column 15:\n    language: \"en\"pipeline: \"spacy_sklearn\"# data  ... \n                  ^"
}
```
How to fix this?

**Comment by akelad** [comment]
Please post the error in a legible format, with ```

**Comment by andy51002000** [comment]
@akelad   Thanks for your mention. I've updated my post. May I know, is there something I misunderstood so that I couldn't train the mix data.

**Comment by akelad** [comment]
Is this the exact error in the log you got? It looks very strange.
Is that file the exact one you used as well? Having one intent example isn't going to do much. I guess there's probably some sort of formatting error

**Comment by andy51002000** [comment]
Yes. It is the exact error I got. The model I used is from the rasa nlu repository /sample_configs/config_train_server_json.yml. Please check the attachment below

![2018_09_05_02_49_20_10 36 172 171_remote_desktop_connection](https://user-images.githubusercontent.com/18550249/45085803-7186db80-b0b6-11e8-998a-8768c21e2e19.png)

I've also tested other model. I still got the same error message. 

```yml
language: "en"

pipeline: "spacy_sklearn"

# data contains the same json, as described in the training data section
data: {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey man",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hi",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "give me coffee",
        "intent": "order",
        "entities": []
      },
      {
        "text": "give me tea",
        "intent": "order",
        "entities": []
      },
      {
        "text": "give me water",
        "intent": "order",
        "entities": []
      },
      {
        "text": "see you",
        "intent": "goodby",
        "entities": []
      },
      {
        "text": "see you next time",
        "intent": "goodby",
        "entities": []
      },
      {
        "text": "goodbye",
        "intent": "goodby",
        "entities": []
      }
    ]
  }
}

```
