### ISSUE TITLE
how to change default tacker store in rasa?

### ISSUE THREAD

**Issue by neerajb1** [RasaHQ/rasa_nlu#1373]
**Rasa NLU version**:0.13.0

**Operating system** (windows, osx, ...):windows

**Content of model configuration file**:
```yml
language: "en"

pipeline:
 - name: "nlp_spacy"
 - name: "tokenizer_spacy"
   model: "en"
 - name: "ner_crf"
 - name: "intent_featurizer_spacy"
 - name: "intent_classifier_sklearn"
 - name: "intent_featurizer_count_vectors"
 - name: "intent_classifier_tensorflow_embedding"
   intent_tokenization_flag: true
   intent_split_symbol: "+"

```

**Issue**:
I want to save mine conversastion detail in mongodb. I findout tracker store. help me to know how i'll use it to save on mongodb
