### ISSUE TITLE
NLU Model training is taking more than 15 hours. Is it normal?

### ISSUE THREAD

**Issue by Priya-ch** [RasaHQ/rasa_nlu#1377]
**Rasa NLU version**: 0.13.1

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_mitie"
  model: "data/total_word_feature_extractor.dat"
  case_sensitive: false
- name: "tokenizer_mitie"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"

```

**Issue**: NLU Model training is taking more than 15 hours. Is it normal?
