### ISSUE TITLE
Entity extractor is not generalising.

### ISSUE THREAD

**Issue by utkarshrai2** [RasaHQ/rasa_nlu#1384]
**Rasa NLU version**:
0.12.3
**Operating system** (windows, osx, ...):
ubantu 16.06
**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_ngrams"
- name: "intent_classifier_sklearn"
```

**Issue**:

i am building a simple faq bot. i need to identify entities as answers vary according to entity. Presently my dataset is small. NLU is giving good results for training data but not for unseen data. I think nlu unit is overfitting. How do i resolve this issue.
