### ISSUE TITLE
On 0.12.3 `ner_crf` relies upon spacy pre-processing. Please modify your pipeline to look like this:

### ISSUE THREAD

**Issue by JoeTorino** [RasaHQ/rasa_nlu#1397]
```
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "tokenizer_whitespace"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```
I used this pipeline but my chatbot for some reason produces two seperate metadata.json files. One metadata file for the spacy components and the other for the r-nn components from tensorflow.

When I run it I get really good results for intent classification but the entity extraction part doesn't seem to working which makes me think half the pipeline is not considered. 

How can I resolve this?

**Comment by akelad** [comment]
you're using two tokenizers, that might be causing an issue. Try changing your pipeline to:
```
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_count_vectors"
- name: "ner_crf"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"
```
If entities still aren't being picked up, it might be an issue with your data. I'd suggest upgrading to 0.13 though, there you can use ner_crf with tensorflow without spacy
