### ISSUE TITLE
Working with rasa-nlu 0.13.3

### ISSUE THREAD

**Issue by JoeTorino** [RasaHQ/rasa_nlu#1401]
```
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "tokenizer_whitespace"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```
Thanks for your help, I was having similar problems with my pipeline and this helped. I also wanted to use look up tables in my chatbot and noticed that this pipeline doesn't seem to function with the up to date rasa-nlu version.

Do you have any suggestions?
