### ISSUE TITLE
Problem with special german characters 

### ISSUE THREAD

**Issue by alexxk82** [RasaHQ/rasa_nlu#1402]
**Rasa NLU version**: 0.13.2

**Operating system** (windows, osx, ...): docker image "rasa/rasa_nlu:0.13.2-full"

**Content of model configuration file**:
This does not work:
```yml
language: "de"

pipeline: "tensorflow_embedding"

data: {
  "rasa_nlu_data": {
    "regex_features": [],
    "entity_synonyms": [
    ],
    "common_examples": [
      {
        "text": "xyz äöüß",
        "intent": "test_äöüß",
        "entities": [
          {
            "entity": "test_äöüß",
            "value": "xyz_äöüß",
            "start": 0,
            "end": 3
          }
        ]
      }
    ]
  }
}
       
```
This works:
```yml

language: "de"

pipeline: "tensorflow_embedding"

data: {
  "rasa_nlu_data": {
    "regex_features": [],
    "entity_synonyms": [
    ],
    "common_examples": [
      {
        "text": "xyz äöüß",
        "intent": "test_äöüß",
        "entities": [
          {
            "entity": "test",
            "value": "xyz_äöüß",
            "start": 0,
            "end": 3
          }
        ]
      }
    ]
  }
}
```

**Issue**:
If there are special german characters like ä, ö, ü, or ß inside the entity-name of common examples the rasa training throws an error.

**Training failed
HTTP status is:
500
Response is:
{
  "error": "ascii"
}**
