### ISSUE TITLE
intent recognition does not work

### ISSUE THREAD

**Issue by prz3mcio** [RasaHQ/rasa_nlu#1417]
**Rasa NLU version**: 0.13.3

**Operating system** (windows, osx, ...): ubuntu 16.04

**Content of model configuration file**:
```yml
language: "en"

pipeline:
  - name: "tokenizer_whitespace"
    #  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"

path: "../model/current/mondelez_nlu_model"
data: "../data/"

    #pipeline:
    #  - name: "nlp_spacy"
    #    model: "en_core_web_lg"
    #    case_sensitive: false
    #  - name: "tokenizer_spacy"          
    #  - name: "intent_featurizer_spacy"
    #  - name: "ner_crf"
    #  - name: "ner_synonyms"
    #  - name: "intent_featurizer_ngrams"
    #    max_number_of_ngrams: 10
    #  - name: "intent_classifier_sklearn"
```

**Issue**:
intents never get recognized when online training. recognized intent name is always user's text speech:

Chat history:

        bot did:        action_listen

        user said:      yo

                 whose intent is:       {'confidence': 1.0, 'name': 'yo'}

        bot did:        action_listen

        user said:      hello

                 whose intent is:       {'confidence': 1.0, 'name': 'hello'}

        bot did:        action_listen

        user said:      hey

                 whose intent is:       {'confidence': 1.0, 'name': 'hey'}

the 'greet' json data am using is from github examples, and it looks like this:

{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "yo",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "howdy",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey there",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hi",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "good morning",
        "intent": "greet",
        "entities": []
      }
]
}
}
