### ISSUE TITLE
Can sklearn_intent_classifier support gamma?

### ISSUE THREAD

**Issue by GaoQ1** [RasaHQ/rasa_nlu#1419]
**Rasa NLU version**:
0.13.4
**Operating system** (windows, osx, ...):
windows 10
**Content of model configuration file**:
```yml
pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
    C: [1, 3, 5, 7, 9, 11, 13, 20, 100]
    kernels: ["rbf"]
    gamma: [0.00001, 0.0001, 0.001, 0.1, 1, 10, 100, 1000]
  - name: "ner_crf"
  - name: "ner_synonyms"
```

**Issue**:
Can sklearn_intent_classifier.py support gamma paramter? I find no support in the source code.
Tuned_parameters does not have this parameter.
