### ISSUE TITLE
None is not of type 'string' when training

### ISSUE THREAD

**Issue by atotalnoob** [RasaHQ/rasa_nlu#1438]
**Rasa NLU version**: 12.2

**Operating system** (windows, osx, ...): Windows Server 2012 R2

**Content of model configuration file**:
```yml
language: "en"

 

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
  features: [["low", "title"], ["bias", "pos2"], ["upper", "pos", "pos2"]]
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "intent_entity_featurizer_regex"
- name: "ner_duckling"
  dimensions: [ "time", "number", "duration"] 
- name: "intent_featurizer_count_vectors"
  "min_ngram": 1
  "max_ngram": 1
- name: "intent_classifier_tensorflow_embedding"
  "num_hidden_layers_a": 2
  "hidden_layer_size_a": [256,128]
  "num_hidden_layers_b": 0
  "hidden_layer_size_b": []
  "batch_size": 32
  "epochs": 300
  "mu_pos": 0.8
  "mu_neg": -0.4
  "similarity_type": "cosine"
  "num_neg": 10
  "use_max_sim_neg": true
  "C2": 0.002
  "C_emb": 0.8
  "droprate": 0.2
  "intent_tokenization_flag": false
  "intent_split_symbol": "_"

data: {DataObj}
```
My entities for this model: 
`"entity_synonyms":[{"value":"trainingHours","synonyms":["Training Hours","training hours","hours of training"]}]`

**Issue**:
When using http training I receive this error repeatedly: 

2018-10-01 10:02:55-0400 [-] 2018-10-01 10:02:55 WARNING  rasa_nlu.data_router -
 [Failure instance: Traceback (failure with no frames): <class 'rasa_nlu.train.T
rainingException'>: None is not of type 'string'
2018-10-01 10:02:55-0400 [-] ]

What should I do? I've checked my JSON data objects and YML and don't see an issue.  I read this, but I don't think its the issue. https://github.com/paschmann/rasa-ui/issues/67
