### ISSUE TITLE
Rasa-moodbot-demo evaluation error

### ISSUE THREAD

**Issue by PersonalizedFinances** [RasaHQ/rasa_nlu#1440]
**Rasa NLU version**:0.13.4

**Operating system** (windows, osx, ...):windows 10

**Content of model configuration file**:
```yml

language: "en"

pipeline:
- name: "nlp_spacy"                   # loads the spacy language model
- name: "tokenizer_spacy"             # splits the sentence into tokens
- name: "ner_spacy"                   # uses the pretrained spacy NER model
- name: "intent_featurizer_spacy"     # transform the sentence into a vector representation
- name: "intent_classifier_sklearn"   # uses the vector representation to classify using SVM
```

**Issue**:
I tried to replicate results from your rasa-moodbot-demo, but when I execute command pprint(interpreter.parse("doing great")) to evaluate Rasa NLU model performance, I get following error.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-8f1691e01b65> in <module>()
----> 1 pprint(interpreter.parse("doing great"))

c:\users\xxxx\anaconda3\envs\chatbot\lib\site-packages\rasa_nlu\model.py in parse(self, text, time, only_output_properties)
    355 
    356         for component in self.pipeline:
--> 357             component.process(message, **self.context)
    358 
    359         output = self.default_output_attributes()

c:\users\xxxx\anaconda3\envs\chatbot\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py in process(self, message, **kwargs)
    174             X = message.get("text_features").reshape(1, -1)
    175             intent_ids, probabilities = self.predict(X)
--> 176             intents = self.transform_labels_num2str(intent_ids)
    177             # `predict` returns a matrix as it is supposed
    178             # to work for multiple examples as well, hence we need to flatten

c:\users\xxxx\anaconda3\envs\chatbot\lib\site-packages\rasa_nlu\classifiers\sklearn_intent_classifier.py in transform_labels_num2str(self, y)
    110         :param y: List of labels to convert to numeric representation"""
    111 
--> 112         return self.le.inverse_transform(y)
    113 
    114     def train(self, training_data, cfg, **kwargs):

c:\users\xxxx\anaconda3\envs\chatbot\lib\site-packages\sklearn\preprocessing\label.py in inverse_transform(self, y)
    271         """
    272         check_is_fitted(self, 'classes_')
--> 273         y = column_or_1d(y, warn=True)
    274         # inverse transform of empty array is empty array
    275         if _num_samples(y) == 0:

c:\users\xxxx\anaconda3\envs\chatbot\lib\site-packages\sklearn\utils\validation.py in column_or_1d(y, warn)
    786         return np.ravel(y)
    787 
--> 788     raise ValueError("bad input shape {0}".format(shape))
    789 
    790 

ValueError: bad input shape (1, 6)

I see that the error is probably with sklearn classifier but I don't know how to fix it. Please help.

Thank you.
