### ISSUE TITLE
how to extract entity which are not adjacent words

### ISSUE THREAD

**Issue by manslogic** [RasaHQ/rasa_nlu#1468]
**Rasa NLU version**:0.13.6

**Operating system** (windows, osx, ...):windows

**Content of model configuration file**:
```yml

language: "en"

pipeline:
- name: tokenizer_whitespace
- name: intent_entity_featurizer_regex
- name: ner_crf
- name: ner_synonyms
- name: intent_featurizer_count_vectors
- name: intent_classifier_tensorflow_embedding
  intent_tokenization_flag: true
  intent_split_symbol: "+"
path: ./models/nlu
data: ./data/training_nlu.json

```

**Issue**:

how to extract entity. which are not adjacent words. below is an example:

i need to train my NLU to understand public grievances, like STREET LIGHT OUT,POTHOLE IN STREET,STREET LIGHTS ON DAYS

My entity value is STREET LIGHT OUT  , that means a person wants to report a Street light not working.
he/she will do it in below format .

The __Street light__ adjacent to Dr Vasanth Shetty's Clinic , WH Hanumanthappa Layout, Ulsoor Road, Bangalore 42 has been __fused__ since  a week.

__Street light__ alone is not an entity or __fused__ alone is not my entity.
street light fused is a synonym . 
Is it possible , to train NLU to extract street light fused from this sentence. if yes how.

if no , is splitting Street Light and fused as different entities is the only solution?
 but it may be possible to extract __street light fused__ from above sentence because it can extract entities which multiple words in it  and tokenizer_whitespace just break at an white space .  

please suggest should is split into multiple entities ?
