### ISSUE TITLE
Rasa is not connecting to duckling's swedish server

### ISSUE THREAD

**Issue by alonsopg** [RasaHQ/rasa_nlu#1471]
Rasa NLU version: 0.13.6
OS: MacOS

**Content of model configuration file**:
```
language: 'sv'
pipeline: 
  - name: "nlp_spacy"              
  - name: "tokenizer_spacy"        
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_spacy"
  - name: "ner_spacy"
  - name: "ner_crf"            
  - name: "ner_synonyms"
  - name: "intent_classifier_sklearn"
  - name: "ner_duckling_http"
    url: "http://0.0.0.0:8000"
    locale: "en_UK"
    dimensions: ["time"]
    timezone: "UK/London"
```

**Issue**:

I installed this Swedish model as follows:

`user:~$ pip3 install sv_model-0.0.0.tar.gz && python3 -m spacy link sv_model sv`

Then, I train Rasa's model:

```
user:~/duckling/migration_2/rasa-assistant$ python3 -m rasa_nlu.train -c config.yml --data data/swedish_dev/ -o models --project current --verbose`

```

Then, after that when I test the model with:

`User:~$python3 -m rasa_nlu.server --path ./models`

However, even I set up the config for duckling support, I cant get any time resolved. For instance:
```
user@User:~$ curl 'localhost:5000/parse?q=Jag%vill%flyga%från%Paris%till%London%imorgon&project=current'
```

Interestingly, when I test curl duckling without Rasa:
```
User:~$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=sv_SV&text=Jag vill flyga från Paris till London imorgon'
[{"body":"imorgon","start":38,"value":{"values":[{"value":"2018-10-17T00:00:00.000-07:00","grain":"day","type":"value"}],"value":"2018-10-17T00:00:00.000-07:00","grain":"day","type":"value"},"end":45,"dim":"time","latent":false}]
```
The dates are resolved correctly. So which is the correct way of linking Rasa and duckling for Swedish support?
