### ISSUE TITLE
Polish duckling in RASA_NLU server

### ISSUE THREAD

**Issue by Quarion25** [RasaHQ/rasa_nlu#1478]
**Rasa NLU version**:
0.13.4

**Operating system** (Ubuntu):

**Content of model configuration file**:
```yml
pipeline:
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: "ner_duckling_http"
  url: "http://0.0.0.0:8000"
  dimensions: ["time"]
  locale: "pl_PL"
  timezone: "Europe/Warsaw"
```

**Issue**:

Hello
I tried to run rasa_nlu.server with config file above, but i can't detect any of time entities. But when i directly ask duckling i get a correct response.
