### ISSUE TITLE
Is it necessary to create a pr?

### ISSUE THREAD

**Issue by GaoQ1** [RasaHQ/rasa_nlu#1487]
**Rasa NLU version**:
rasa nlu 0.13.4

**Operating system** (windows, osx, ...):
osx 10.14

**Issue**:
Hi, I customize a component, that can realize part of speech annotation. And it's based on Jieba.
The configuration file like
```yml
language: "zh"

 pipeline:
 - name: "tokenizer_jieba"
 - name: "ner_crf"
 - name: "jieba_pseg_extractor"
   part_of_speech: ["nr", "ns", "nt"]

 - name: "intent_featurizer_count_vectors"
   OOV_token: oov
   token_pattern: '(?u)\b\w+\b'
 - name: "intent_classifier_tensorflow_embedding"
```
The component I named "jieba_pseg_extractor", and the result like that
```json
{
  "q": "帮我看一下周杰伦上个月消费多少",
  "model": "model_20181028-093018"
}
```
```json
{
    "intent": {
        "name": "request_search",
        "confidence": 0.9231363534927368
    },
    "entities": [
        {
            "start": 8,
            "end": 11,
            "value": "上个月",
            "entity": "time",
            "confidence": 0.90110105378646,
            "extractor": "jieba_pseg_extractor"
        },
        {
            "start": 11,
            "end": 13,
            "value": "消费",
            "entity": "item",
            "confidence": 0.9340974897429838,
            "extractor": "jieba_pseg_extractor"
        },
        {
            "start": 5,
            "end": 8,
            "value": "周杰伦",
            "entity": "nr",
            "extractor": "jieba_pseg_extractor"
        }
    ],
    "intent_ranking": [
        {
            "name": "request_search",
            "confidence": 0.9231363534927368
        },
        {
            "name": "unknown_intent",
            "confidence": 0.06890465319156647
        },
        {
            "name": "goodbye",
            "confidence": 0.04904055595397949
        },
        {
            "name": "inform_package",
            "confidence": 0.016052521765232086
        },
        {
            "name": "inform_other_phone",
            "confidence": 0
        },
        {
            "name": "request_management",
            "confidence": 0
        },
        {
            "name": "thanks",
            "confidence": 0
        },
        {
            "name": "inform_current_phone",
            "confidence": 0
        },
        {
            "name": "deny",
            "confidence": 0
        },
        {
            "name": "greet",
            "confidence": 0
        }
    ],
    "text": "帮我看一下周杰伦上个月消费多少",
    "project": "default",
    "model": "model_20181028-093018"
}
```
So , is it necessary to make a pr?
