### ISSUE TITLE
Influence of using nlp_spacy together with tensorflow_embedding?

### ISSUE THREAD

**Issue by Dylan0126** [RasaHQ/rasa_nlu#1510]
**Rasa NLU version**:   0.13.2

**Content of model configuration file**:
```yml

- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"


```

**Issue**:
Just realized that I was using the above config file to train tensorflow_embedding models(I used this when I was not familiar with the pipeline components thus I had no idea what I was doing at that time). 

I think there are conflicts in the pipline. Just want to confirm some of my understandings.  nlp_spacy is using pre-trained word vectors while tensorflow_embedding should be training its own domain specific word vectors. I also included two tokenizers in this pipeline.

But I am very interested to know what's the behavior of rasa_nlu when this kind of conflicts happen? 
1. Which word_vectors is this pipeline actually using to produce models? The pre-trained one or the one from tensorflow_embedding?

2. Will this pipeline create any performance issues for intent recognition?

3. Does the choice of using a pre-trained or tensorflow learned word_vectors have any influence on entity extraction part? For example, if I am using a spacy_sklearn pipeline with ner_crf (as entity extraction component) and a tensorflow_embedding pipeline with ner_crf, will they perform the same in terms of entity extraction?
