### ISSUE TITLE
Rasa_nlu returns intent as null for training samples using tensorflow classifier(Chinese) 

### ISSUE THREAD

**Issue by pfZhu** [RasaHQ/rasa_nlu#1515]
**Rasa NLU version**: 0.13.0

**Operating system** (windows, osx, ...): ubuntu 18.04

**Content of model configuration file**:
```yml
language: "zh"
project: "ivr_nlu"
fixed_model_name: "demo"
path: "models"
pipeline:
- name: "nlp_mitie"
  model: "data/total_word_feature_extractor_zh.dat"
- name: "tokenizer_jieba"
  dictionary_path: "data/userdict.txt"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name: "ner_mitie"
- name: "ner_synonyms"
```

**Issue**:
The language of my system is Chinese. Most of the training samples are classified correctly, but a few samples return an intent as null. The model failed to classify the sample “在吗” which means “are you there” and “是” which means “yes”. Could the model “data/total_word_feature_extractor_zh.dat” affect intent classification? Besides, it didn't happen when I used spacy_sklearn as intent classifier. What is wrong with tf embedding or my configuration?
