### ISSUE TITLE
Entity Extraction lookup table is not working

### ISSUE THREAD

**Issue by Dylan0126** [RasaHQ/rasa_nlu#1528]
**Rasa NLU version**: 0.13.7

**Operating system** (windows, osx, ...):  Tested on both macOS 10.13.5 and Amazon Linux EC2

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
  features: [
              ["low", "title", "upper"],
              ["bias", "low", "prefix5", "prefix2", "suffix5", "suffix3",
               "suffix2", "upper", "title", "digit", "pattern"],
              ["low", "title", "upper"]
            ]
```

**Issue**:
I want to try if a lookup table will improve the entity extraction performance of my model. I am following the blog here: http://blog.rasa.com/improving-entity-extraction.

I used a similar training data format as the company demo in the blog:
Here are the first couple lines of my training data:
{
  "rasa_nlu_data": {
    "lookup_tables": [
      {
        "name": "sofia",
        "elements": "data/sofia/dependent_type.csv"
      }
    ],
    "common_examples": [
      {.............

The CSV file is at the correct location containing 10 words. This training data format is the same as in the demo. 

But after training my model using the training data above with lookup table, I found no difference in the performance which is weird, I am expecting at least some kind of difference. So I checked the training_data.json file under model folder, at the bottom I found that lookup_tables is showing as empty here.
"regex_features": [],
"lookup_tables": [],
"entity_synonyms": []
However when I check the training_data.json under your demo in the blog, I found 
    "regex_features": [],
    "lookup_tables": [
      {
        "name": "company",
        "elements": "data/company/startups_filtered.csv"
      }
    ],
    "entity_synonyms": []

I think this means this lookup table feature is not working correctly in my case.
I am pretty sure I am using the correct training data file, but the training process is not capturing the lookup table as it should be. So the training_data.json in the model folder is not showing anything in the lookup_tables field.
