### ISSUE TITLE
Feature Request: character_count_vectorizer_

### ISSUE THREAD

**Issue by jamesmf** [RasaHQ/rasa_nlu#1530]
**Feature Request**:
It would be useful to have a separate `intent_featurizer_count_char_vectors` (or similarly named) Component. Using a separate Component makes it simple to combine them using defaults (mixing defaults across char- and word-level `CountVectorizer` is messy since they're very different). 

**Sample**:
```yml
  - name: "intent_featurizer_count_vectors"
    max_features: 1000
    min_ngram: 1  # int
    max_ngram: 2  # int

  - name: "charcountvectorizer.charcountvectorizer.CharCountVectorsFeaturizer"
    max_features: 1000
    analyzer: "char"
    min_ngram: 1
    max_ngram: 6
```
This config file would create features for the top 1000 *word* uni- and bi-grams, then would supplement that with the top 1000 *character* uni- to 6-grams. I've tested this with my own data and confirmed it does imbue the pipeline with some spelling/typo invariance. Obviously once it's default component we can name it something better than it is above.

The only changes I think are necessary are:
1) base the new component off `CountVectorFeaturizer`
2) add 'analyzer' argument
3) edit new defaults
4) update `.load` to reference itself instead of `CountVectorFeaturizer`
5) add it to the registry

Could address #1217 and #1494
