### ISSUE TITLE
slot names containing '-'

### ISSUE THREAD

**Issue by jmrf** [RasaHQ/rasa_nlu#1556]
**Rasa NLU version**: 0.13.2

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Content of model configuration file**: 
```yml
language: "en"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"  
```

**Issue**: 

At least in `markdown` NLU training data, slots with a `-`  or `+` in the name are not detected at training time and hence not predicted. 
I guess the only allowed characters are alphanumeric + underscore (`_`)?
Is not a problem by itself but would be good if possible to print a warning about entities with incompatible names. Also, add the allowed character set for the slot names to the docs.

As an example:
```yml
## intent:hello
- Hello my name is [Alice](client-name) # this won't work
- Hey this is [Alice](client_name) # this works
- I am [Alice](client_name) # this works

## intent:goodbye
- See you
- goodbye
```

`python rasa_nlu.train [...] --verbose` will print out:
```bash
	- intent examples: 5 (2 distinct intents)
	- Found intents: 'hello', 'goodbye'
	- entity examples: 2 (1 distinct entities)
	- found entities: 'client_name'
```

I've checked the [docs for data format](https://rasa.com/docs/nlu/0.13.2/dataformat/) but I haven't found an express warning of such limitation.
Maybe I am missing something, in that case sorry for the noise.
