### ISSUE TITLE
How to setup the config.yml for allowing all the cors_origin

### ISSUE THREAD

**Issue by sanjeethanspal** [RasaHQ/rasa_nlu#1599]
**Rasa NLU version**: 0.13.8

**Operating system** Ubuntu 16.04.5 :
**Python version**:  3.6

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: "ner_duckling_http"
  # url of the running duckling server
  url: "http://localhost:8000"
  # dimensions to extract
  dimensions: ["time", "number", "amount-of-money", "distance"]
  # allows you to configure the locale, by default the language is
  # used
  locale: "en_US"
  # if not set the default timezone of Duckling is going to be used
  # needed to calculate dates from relative expressions like "tomorrow"
  timezone: "America/Los_Angeles"

cors_origins:
- "*"

```

**Issue**:
How to setup the config file for the cors_origin. I tried the above file as a configuration and even tried running the action server by following command but didn't helped. So how to allow cross origin using config file for whitelisting the domains.

```
python3 -m rasa_core_sdk.endpoint --actions actions --cors '*'
```
