### ISSUE TITLE
Different confidence score on same NLU models for the same user query.

### ISSUE THREAD

**Issue by dhruvrajkotia** [RasaHQ/rasa_nlu#1620]
**Rasa NLU version**: 0.13.8
**Operating system** (windows, osx, ...): any

**Content of model configuration file**:
```yml
pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
"epochs": 3000
```

**Issue**: When we train NLU models on same train data, and if we tried the same user query on both the models then we got different confidence score.

Is there any solution for that??

I think ideally it should be the same confidence score for both the models on the same user query.
