### ISSUE TITLE
No output on evaluate script

### ISSUE THREAD

**Issue by jamesmf** [RasaHQ/rasa_nlu#1627]
**Rasa NLU version**:
0.13.8

**Content of model configuration file**:
```yml
pipeline:
  - name: "mycustomrasa.my_entity_extractor.MyEntityExtractor"
```

**Issue**:
It would be useful to be able to use `rasa_nlu.evaluate` to evaluate the performance of your own extractors. The documentation states:

```
The ner_crf is the only entity extractor which you train using your own data, and so is the only one which will be evaluated. If you use the spaCy or duckling pre-trained entity extractors, Rasa NLU will not include these in the evaluation.

Rasa NLU will report recall, precision, and f1 measure for each entity type that ner_crf is trained to recognize.
```

Is there a reason that we can't evaluate custom components? If we set `start`, `end`, `entity`, and `extractor` would it be difficult to evaluate performance using the same method?

**Comment by akelad** [comment]
Have you tried evaluating your extractor with the script? I think the point of that piece of documentation is to say that it won't evaluate the pretrained entity extractors

**Comment by jamesmf** [comment]
Looks like I might have had a different issue. I ran a simple pipeline:

```
pipeline:
    - name: "tokenizer_whitespace"
    - name: "intent_featurizer_count_vectors"
      max_features: 10
    - name: "mycustomrasa.my_entity_extractor.MyEntityExtractor"
      checkpoint_path: "tmp_data/best-model.pt"
   
    - name: "intent_classifier_sklearn"
```

I got an error when I didn't have an intent classifier, so I put in a particularly trivial one.

When I run 
```
python -m rasa_nlu.evaluate --data path-to-data/ --model path-to-model/
```
I can see that my entity extractor is getting called, but it doesn't print any evaluation results at all. I do see the outputs `errors.json`, `confmat.png`, and such.

I'm also running this with a `matplotlibrc` containing `backend:agg` to avoid issues plotting in docker.

**Comment by jamesmf** [comment]
I tried two more pipelines to see what replicates the behavior:

First, I tried the same pipeline with `ner_crf` instead my custom module, and I did see the reports for both intents and entities.
```
pipeline:
    - name: "tokenizer_whitespace"
    - name: "intent_featurizer_count_vectors"
      max_features: 10
    - name: "ner_crf"
    - name: "intent_classifier_sklearn"
```

Then I simply added `ner_crf` to my existing pipeline (with my custom component) and after doing so I didn't get any reports output at all (neither intents nor entities)
```
pipeline:
    - name: "tokenizer_whitespace"
    - name: "intent_featurizer_count_vectors"
      max_features: 10
    - name: "ner_crf"
    - name: "mycustomrasa.my_entity_extractor.MyEntityExtractor"
      checkpoint_path: "tmp_data/best-model.pt"
    - name: "intent_classifier_sklearn"
```
