### ISSUE TITLE
ner_crf output is always lowercase

### ISSUE THREAD

**Issue by amitga-rnd** [RasaHQ/rasa_nlu#1676]
**Rasa NLU version**: 0.13.8

**Operating system**: Linux (Ubuntu 16.04)

**Content of model configuration file**:
```yml
pipeline:
- name: "nlp_spacy"       
  model: "en_core_web_lg"
- name: "tokenizer_spacy"
- name: "ner_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "intent_classifier_sklearn"
```

**Issue**:
Hi.
I have successfully trained NLU using `ner_crf` to extract some custom entities (for example vehicles).
It works great at extracting vehicles entities, regardless if I entered the vehicle's name all lowercase or with first letter capital (works like I want it to).
The issue is that the result from `ner_crf` is always lowercase. I would like it to be returned just as the user entered it.

For example, if I send the following request:
`http://localhost:5000/parse?q=Find me a Subaru Impreza&project=mybot&model=nlu`
This is what `ner_crf` returns (compared to spacy):
```json
"entities": [
    {
      "entity": "ORG",
      "value": "Subaru",
      "start": 10,
      "confidence": null,
      "end": 16,
      "extractor": "ner_spacy"
    },
    {
      "entity": "PRODUCT",
      "value": "Impreza",
      "start": 17,
      "confidence": null,
      "end": 24,
      "extractor": "ner_spacy"
    },
    {
      "start": 10,
      "end": 16,
      "value": "subaru",
      "entity": "vehicle-make",
      "confidence": 0.9548908938009781,
      "extractor": "ner_crf"
    },
    {
      "start": 17,
      "end": 24,
      "value": "impreza",
      "entity": "vehicle-model",
      "confidence": 0.9113687018573872,
      "extractor": "ner_crf"
    }
  ],
```
As you can see, `ner_crf` entities are always lowercase, while `ner_spacy` returns them correctly.
The reason I want to use `ner_crf` is because while spacy does a good job most of the time recognizing the vehicle make as `ORG` and the vehicle model as `PRODUCT`, its far from perfect.
Using `ner_crf` with some lookup tables has given better results so far...

Is there any way to configure `ner_crf` to return the entities in the original case (as they were entered) ?

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@amitga-rnd Can you please try this pipeline

```yml
pipeline:
- name: "nlp_spacy"       
  model: "en_core_web_lg"
  case_sensitive: true
- name: "tokenizer_spacy"
- name: "ner_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "intent_classifier_sklearn"
```
