### ISSUE TITLE
Could not broadcast input array from shape (128) into shape (96)

### ISSUE THREAD

**Issue by bguivarch** [RasaHQ/rasa_nlu#1683]
**Rasa NLU version**:
14.0a1

**Operating system** (windows, osx, ...):
Image built with docker, and running on docker.

**Content of model configuration file**:
here is the pipeline config:
```yml
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

**Issue**:
The training sent me an error: 
```javascript
{
    "error": "could not broadcast input array from shape (128) into shape (96)"
}
```

If I change the pipeline and don't use spacy anymore, it works fine.
Is there a reason why this pipeline is not working fine with both spacy and tensorflow_embedding?
