### ISSUE TITLE
While running the rasa training it is showing SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by bandarunagesh** [RasaHQ/rasa_nlu#1714]
**Rasa NLU version**: Version: 0.15.0a1

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Content of model configuration file**:
```yml
language: "en"
pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
  - name: "ner_crf"
  - name: "ner_synonyms"

policies:
  - name: "FallbackPolicy"
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: "my_fallback_action"
```

**Issue**:
While running the below command in the ubuntu, i am getting issue saying 
"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/opt/rasa_nlu/rasa_nlu/train.py", line 87
    def create_persistor(persistor: Optional[Text]):
                                  ^
SyntaxError: invalid syntax
"
I am executing below command:
python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose
