### ISSUE TITLE
Multi-core training for CRF

### ISSUE THREAD

**Issue by careless25** [RasaHQ/rasa_nlu#1730]
**Rasa NLU version**: 0.13.7 

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Content of model configuration file**:
```yml
pipeline:
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "nlp_spacy"
  model: "en_core_web_lg"
- name: "tokenizer_spacy"
- name: "custom.component.CustomName"
- name: "intent_featurizer_spacy"
- name: "intent_featurizer_ngrams"
- name: "ner_spacy"
- name: "intent_featurizer_count_vectors"
- name: "ner_duckling"
  timezone: "Canada/Eastern"
  locale: "en"
- name: "ner_duckling_http"
  url: "http://localhost:8000"
  dimensions: ["time", "number", "amount-of-money", "distance", "email", "phone-number", "url", "ordinal"]
  timezone: "Canada/Eastern"
  locale: "en"
- name: "ner_crf"
  BILOU_flag: False,
  features: [ ["low","title"], ["bias", "prefix5" , "prefix2", "suffix5",  "suffix3" ,"suffix2","suffix1", "pos" ,"pos2", "pattern"], ["low", "title"] ]
  max_iterations: 100
- name: "ner_synonyms"
- name: "intent_classifier_tensorflow_embedding"
  epochs: 50
  "num_hidden_layers_a": 2
  "hidden_layer_size_a": [ 1024 , 512]
  "num_hidden_layers_b": 0
  "hidden_layer_size_b": []
  "batch_size": 7012 
  # embedding parameters
  "embed_dim": 300
  # regularization parameters
  "C2": 0.002
  "droprate": 0.1
```

**Issue**: Our dataset is large, ~50,000 training examples with 300+ intents and increasing with 200+ different entity types + lookup tables/synonyms, and the training time for a model is increasing. On a machine with 8 cores and a GPU, we are seeing a training time of about 8 hours for 1 model. 

The main bottleneck for the model training seems to be the CRF which only uses one core for the training and not all possible cores. Could this be sped up? Training the TF embeddings is relatively short compared to that (about 30 mins).
