### ISSUE TITLE
Run evaluation fails every time

### ISSUE THREAD

**Issue by nadabou** [RasaHQ/rasa_nlu#1742]
**Rasa NLU version**:
0.14.3
**Operating system** (windows, osx, ...):
Windows 10
**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy" 
- name: "tokenizer_spacy" 
- name: "intent_featurizer_spacy" 
- name: "intent_classifier_sklearn" 
```

**Issue**:
After training my model and parsing utterances with it, I try to evaluate it using:
```
from rasa_nlu.evaluate import run_evaluation
run_evaluation("nlu.md", model=model_directory)
```
Where nlu.md contains my test data and model_directory is the path to my model.
Evaluation starts and then fails every time with the same error:
`TypeError: classification_report() got an unexpected keyword argument 'output_dict'`

![image](https://user-images.githubusercontent.com/29257680/53424001-a713de00-39e2-11e9-8600-5720a58a0752.png)
