### ISSUE TITLE
Parse doesn't use latest trained model

### ISSUE THREAD

**Issue by simonline** [RasaHQ/rasa_nlu#1743]
**Rasa NLU version**:
0.15.0a1

**Operating system** (windows, osx, ...):
Ubuntu 18.04.1 LTS

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"

data: {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      }
    ]
  }
}
```

**Issue**:
In the HTTP API docs (https://rasa.com/docs/nlu/http/#id3) it says „By default the latest trained model for the project will be loaded“. However this doesn't work for me.

My attempt to parse with `curl -XPOST localhost:5000/parse -d '{"q":"test", "project": "test_1"}'` returned:
```
{
    "intent": {
        "name": null,
        "confidence": 1
    },
    "entities": [],
    "text": "test",
    "project": "test_1",
    "model": "fallback" # This should be model_1
}
```
It works when I define "model" in the JSON body, however the way our application works I'd have to run an extra query (`/status`) to identify the latest model before every `/parse`. 

I've trained the model before using `curl -XPOST -H "Content-Type: application/x-yml" localhost:5000/train?project=project_1&model=model_1` (and model config above), it returned:
```
{
    "info": "new model trained",
    "model": "1"
}
```

The `curl localhost:5000/status` after training was:
```
{
    "max_training_processes": 1,
    "current_training_processes": 0,
    "available_projects": {
        "default": {
            "status": "ready",
            "error_message": null,
            "current_training_processes": 0,
            "available_models": [
                "fallback"
            ],
            "loaded_models": [
                "fallback"
            ]
        },
        "test_1": {
            "status": "ready",
            "error_message": null,
            "current_training_processes": 0,
            "available_models": [
                "fallback",
                "1"
            ],
            "loaded_models": [
                "fallback"
            ]
        }
    }
}
```
