### ISSUE TITLE
What path to load for nlu.server?

### ISSUE THREAD

**Issue by Spenhouet** [RasaHQ/rasa_nlu#1769]
**Rasa NLU version**: 0.14.3
**Operating system**: Windows 10

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

**Issue**:

Until know training nlu and core as well as starting core with connector works absolutely fine.
Today I wanted to test Rasa UI for which I have to start the `rasa_nlu.server`.
I did read the documentation but I don't get what the `path` should be?

The documentation is talking about `projects` and requests something like this:

```
- <path>
 - <project_A>
  - <model_XXXXXX>
  - <model_XXXXXX>
   ...
 - <project_B>
  - <model_XXXXXX>
   ...
  ...
```

But we have nothing like that in our code base and never did read the `projects` term in relation to rasa.

The path created by rasa for the core and nlu training looks like this:

```
- models
  - current
    - dialogue
      - domain.json
      - domain.yml
      - ....
    - nlu
      - checkpoint
      - crf_model_pkl
      - ....
```

So where should this project structure come from? Did I miss something?
