### ISSUE TITLE
how to config OOV_token

### ISSUE THREAD

**Issue by red-frog** [RasaHQ/rasa_nlu#1779]
**Rasa NLU version**:
0.14.4
**Operating system** (windows, osx, ...):
linux 16.04
**Content of model configuration file**:
```yml
language: "zh"

pipeline:

# spacy+sklearn

- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "jieba_pseg_extractor"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  OOV_token: oov
  token_pattern: '(?u)\b\w+\b'
- name: "intent_classifier_tensorflow_embedding"
```

**Issue**:
when train the nlu_module, appear the warning, how i can solve it, and i don't know the effect about OOV_token. Please give me some examples. Thanks!

WARNING:rasa_nlu.featurizers.count_vectors_featurizer:OOV_token='oov' was given, but it is not present in the training data. All unseen words will be ignored during prediction.
