### ISSUE TITLE
Lookup Table File Version UnicodeError

### ISSUE THREAD

**Issue by demongolem** [RasaHQ/rasa_nlu#1781]
**Rasa NLU version**:
0.14.4

**Operating system** (windows, osx, ...):
Windows 10

**Content of model configuration file**:
```yml
language: en
pipeline:
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

**Issue**:
When I create a Lookup Table in the format 
```
## lookup:currencies   <!-- lookup table list -->
- Yen
- USD
- Euro
```
training is successful.  (This is not my real lookup table, it contains 65,000 entries, some of the characters are utf-8).  When I have the same content, but I use the filename version (and this is the actual content of my .md file below)
```
## lookup:client   <!-- no list to specify lookup table file -->
entities/Client.txt
```
I get   

> File "C:\Users\gwerner004\eclipse-workspace\RasaKickTheTires\Camunda.py", line 135, in <module>
>     num_threads=1)
>   File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\train.py", line 154, in do_train
>     interpreter = trainer.train(training_data, **kwargs)
>   File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 196, in train
>     **context)
>   File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\featurizers\regex_featurizer.py", line 53, in train
>     self._add_lookup_table_regexes(training_data.lookup_tables)
>   File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\featurizers\regex_featurizer.py", line 76, in _add_lookup_table_regexes
>     regex_pattern = self._generate_lookup_regex(table)
>   File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\featurizers\regex_featurizer.py", line 126, in _generate_lookup_regex
>     for line in f:
>   File "C:\Users\gwerner004\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5770: character maps to <undefined>

My first version, the list version is created from these same files.  But when I call do_train on the second version, the encoding is mixed up.  What can I do so that the filename version works?
