### ISSUE TITLE
Support slot values in utter templates

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#1816]
There should be a simple way to access the slot values from a template (e.g. by making them always available). Example:

```yml
slots:
  username:
     type: "text"
templates:
  utter_hello:
    - "Hello, {username}"
```

When the template `utter_hello` is used, the value for the slot should be filled in.
