### ISSUE TITLE
Moodbot Story ends with BYE always

### ISSUE THREAD

**Issue by philixta** [RasaHQ/rasa_nlu#1873]
**Rasa Core version**:
rasa_core-0.7.9
**Python version**: 
2.7
**Operating system** (windows, osx, ...):
OSX
**Issue**:

Moodbot Story always ends with Bye 

Philixs-MacBook-Air:moodbot philixta$ python -m rasa_core.run -d models/dialogue -u models/nlu/current
INFO:root:Rasa process starting
Using TensorFlow backend.
dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /usr/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
2017-12-15 22:26:47.884862: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
hi
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
INFO:root:Finished loading agent, starting input channel & server.
Bot loaded. Type a message and press enter : 
DEBUG:rasa_core.tracker_store:Creating a new tracker for id 'default'.
DEBUG:rasa_core.processor:Received user message 'hi' with intent '{u'confidence': 0.3066724927468702, u'name': u'greet'}' and entities  '[]'
DEBUG:rasa_core.processor:Logged UserUtterance - tracker now has 2 events
DEBUG:rasa_core.processor:Current slot values: 

DEBUG:rasa_core.policies.memoization:Current tracker state [
	None
	None
	[(u'intent_greet', 1), (u'prev_action_listen', 1)]]
DEBUG:rasa_core.policies.ensemble:Predicted next action #6 with prob 0.37.
Bye
DEBUG:rasa_core.processor:Bot utterance 'BotUttered(text: Bye, data: null)'
DEBUG:rasa_core.processor:Action 'utter_goodbye' ended with events '[]'
DEBUG:rasa_core.policies.memoization:Current tracker state [
	None
	[(u'intent_greet', 1), (u'prev_action_listen', 1)]
	[(u'intent_greet', 1), (u'prev_utter_goodbye', 1)]]
DEBUG:rasa_core.policies.ensemble:Predicted next action #0 with prob 0.95.
DEBUG:rasa_core.processor:Action 'action_listen' ended with events '[]'
DEBUG:rasa_core.processor:Current topic: None

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://cdn77.eatliver.com/wp-content/uploads/2017/10/trump-frog.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

actions:
  - utter_greet
  - utter_cheer_up
  - utter_did_that_help
  - utter_happy
  - utter_goodbye
```
