### ISSUE TITLE
Unable to update slots through SlotSet return in actions.py

### ISSUE THREAD

**Issue by foxjr** [RasaHQ/rasa_nlu#1878]
**Rasa Core version**: 0.7.9

**Python version**: 2.7.13

**Operating system** (windows, osx, ...): Linux - Fedora 25

**Issue**: `return [SlotSet(key, value)]` does not update slots. In my actions.py, I do a query that returns a list of results that I am able to utter via the dispatcher, but I am unable to save those results to a slot. I have also tried manipulating the slots directly via the tracker, but that did not work, either. I'm wondering whether the slots are being continually overwritten through some policy. I'm using the default Keras and Memoization policies. 

**Content of domain file** (if used & relevant):
```yaml
entities:
 - key1
 - value1
 - key2
 - value2
 - key3
 - value3
 - op

slots:
  results:
    type: list
  key1:
    type: categorical
    values:
      - OgreId
      - date
  value1:
    type: text
  key2:
    type: categorical
    values:
      - Latitude
      - Longitude
  value2:
    type: float
  key3:
    type: categorical
    values:
      - Latitude
      - Longitude
  value3:
    type: float
  op:
    type: text

intents:
 - greet
 - thankyou
 - goodbye
 - search_1
 - search_2
 - search_2_3
 - decline

templates:
  utter_greet:
    - "Hello, OGREbot user!"
    - "Hello, there!"
    - "Hey!"
    - "Hey, user!"
  utter_goodbye:
    - "Goodbye!"
    - "Thanks for using OGREbot!"
    - "See you later!"
    - "See you next time!"
    - "Bye!"
  utter_help:
    - "What can I help you with today?"
    - "How can I help you?"
    - "What can I do for you?"
    - "How can I be of service?"
  utter_youarewelcome:
    - "You're very welcome!"
    - "No problem!"
    - "Not a problem!"
    - "You're welcome!"
  utter_morehelp:
    - "What else can I help you with?"
    - "Is there anything else I can do?"
    - "Can I do anything else?"
    - "Let me know if there's anything else I can help you with!"

actions:
  - utter_greet
  - utter_youarewelcome
  - utter_help
  - utter_morehelp
  - utter_goodbye
  - actions.ActionSearch1
  - actions.ActionSearch2
  - actions.ActionSearch2_3
```
**Example from actions.py file**:
```actions.py

class ActionSearch1(Action):
    def name(self):
        return 'action_search_1'

    def run(self, dispatcher, tracker, domain):
        if tracker.get_slot("key1") is not None and tracker.get_slot("value1") is not None:
            connection = urlopen('{}q={}:{}&rows=9999&wt=json'.format(url, tracker.get_slot("key1"), tracker.get_slot("value1").upper()))
            response = eval(connection.read()) 
            response = response['response']['docs']
            if response is None or response == 0:
                dispatcher.utter_message("I didn't find any results.")
            else:
                if len(response) == 1:
                    dispatcher.utter_message("I found 1 result.")
                elif len(response) < 11:
                    dispatcher.utter_message("I found " + str(len(response)) + " results.")
                else:
                    dispatcher.utter_message("I found " + str(len(response)) + " results. I'll display 10 of them.")
                    response = response[:11]
                dispatcher.utter_message(response)
                result = [SlotSet("results", response)]
                
        else:
            dispatcher.utter_message("I can't run a query with that.")
            result = [SlotSet("key1", None), SlotSet("value1", None)]
        return result

```
