### ISSUE TITLE
handle emoji in domain.yml

### ISSUE THREAD

**Issue by tycho01** [RasaHQ/rasa_nlu#1907]
**Rasa Core version**: 0.8.0a4
**Python version**: 2.7.14
**Operating system**: ubuntu
**Issue**:
Using emoji in `domain.yml`, training fails with `yaml.reader.ReaderError: unacceptable character #x1f607: special characters are not allowed`, a [known issue](https://stackoverflow.com/questions/44875403/loading-special-characters-with-pyyaml) with PyYaml.
Interestingly, Rasa also uses `ruamel.yaml`, which does not have this limitation. However, it appears the switch to this is yet incomplete.

**Content of domain file**:
```yaml
intents:
  - greet
templates:
  hi:
  - text: Hi. 🙂
actions:
  - hi
```
