### ISSUE TITLE
Categorical slots values are assigned incorrectly

### ISSUE THREAD

**Issue by nachoaguadoc** [RasaHQ/rasa_nlu#1955]
**Rasa Core version**: 0.8.2

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): OSX

**Issue**: 

Hello there,

I'm having a small issue with the slot filling of Rasa Core. When you create a categorical slot, the value of the slot is filled if the entity is recognized in the NLU, independently of whether the entity value is between the list of possible values of the categorical slot. 

The hot label encoding assigned to the Slot is updated properly (all of their elements remain as 0.0 if the entity is not in the list of allowed values), but this doesn't seem to be taken into account to update the value of the slot.

I can make it work by reading the hot label encoding array instead of the value, but doesn't seem to be working as intended.

I add at the end of the text the way I defined the slot that it's causing the problem. Whenever the entity "expenses_category" is found by the NLU, the slot gets assigned the value found, even if it's not in this list. 

Let me know if I'm missing something that might cause this to fail and it's not an actual bug.

Thanks!

**Content of domain file**:
```yaml
slots:
  expenses_category:
    type: categorical
    values:
      - utility
      - travel
      - investment
      - grocery
      - fuel
      - education
      - dining
```
