### ISSUE TITLE
Update slot value with entity value from Rasa NLU only after verifying if it is in the list of candidates

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa_nlu#1958]
This is relevant (as specified in #254) when a slot is defined with a set of possible values in the domain file, like below.

```yaml
slots:
  expenses_category:
    type: categorical
    values:
      - utility
      - travel
      - investment
      - grocery
      - fuel
      - education
      - dining
```

Rather than blindly update the slot value with that of the entity, a check should be performed if the entity value belongs to the set of candidate values.

Perhaps, raise a warning or exception?
