### ISSUE TITLE
WARNING:rasa_core.featurizers:Couldn't set most probable feature, it wasn't found in the feature list of the domain. Make sure you added all intents and entities to the domain.

### ISSUE THREAD

**Issue by artiberde27** [RasaHQ/rasa_nlu#1961]
**Rasa Core version**:0.7.9

**Python version**: 3.6

**Operating system** (windows, osx, ...):Ubuntu 16.04

**Issue**:
I am getting below waring when i trained dialog
**WARNING:rasa_core.featurizers:Couldn't set most probable feature 'intent_person_category_info{"person_category":"non salaried"}', it wasn't found in the feature list of the domain. Make sure you added all intents and entities to the domain.**

_I am getting this type of warning for all entities_ 

Below is my domain.yml file

```
slots:
  loan_type:
    type: categorical
    values:
    - Home loan
    - Car loan
    - Personal loan
  person_category:
    type: categorical
    values:
    - salaried
    - Non salaried
  loan_amount:
    type: text

intents:
  - greet
  - thankyou
  - goodbye
  - request_loan
  - request_specific_loan
  - loan_amount_info
  - loan_category_info
  - person_category_info

entities:
  - loan_type
  - loan_amount
  - person_category

action_factory: remote

actions:
  - default
  - greet1
  - goodbye
  - ask_helpmore
  - show_list_of_loan_type
  - ask_for_loan_amount
  - ask_for_person_category_info
  - show_list_of_document_for_salaries
  - show_list_of_document_for_non_salaries
```

```yaml

```

And stories.md file

```
## story_00001
* _greet
 - greet1
* _request_loan
 - show_list_of_loan_type
* _loan_category_info
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"salaried"}
 - show_list_of_document_for_salaries
* _thankyou
 - ask_helpmore

## story_00002
* _greet
 - greet1
* _request_loan
 - show_list_of_loan_type
* _loan_category_info
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"Non salaried"}
 - show_list_of_document_for_non_salaries
* _thankyou
 - ask_helpmore


## story_00003
* _greet
 - greet1
* _request_specific_loan{"loan_type":"Home loan"}
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"salaried"}
 - show_list_of_document_for_salaries
* _thankyou
 - ask_helpmore

## story_00004
* _greet
 - greet1
* _request_specific_loan{"loan_type":"Car loan"}
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"salaried"}
 - show_list_of_document_for_salaries
* _thankyou
 - ask_helpmore

## story_00005
* _greet
 - greet1
* _request_specific_loan{"loan_type":"Personal loan"}
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"salaried"}
 - show_list_of_document_for_salaries
* _thankyou
 - ask_helpmore


## story_00006
* _greet
 - greet1
* _request_specific_loan{"loan_type":"Home loan"}
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"Non salaried"}
 - show_list_of_document_for_non_salaries
* _thankyou
 - ask_helpmore

## story_00007
* _greet
 - greet1
* _request_specific_loan{"loan_type":"Car loan"}
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"Non salaried"}
 - show_list_of_document_for_non_salaries
* _thankyou
 - ask_helpmore

## story_00007
* _greet
 - greet1
* _request_specific_loan{"loan_type":"Personal loan"}
 - ask_for_loan_amount
* _loan_amount_info
 - ask_for_person_category_info
* _person_category_info{"person_category":"Non salaried"}
 - show_list_of_document_for_non_salaries
* _thankyou
 - ask_helpmore
```

I have define all intent and entities in my domain.
Could anyone please explain why i am getting this warning and what it exact mean?
