### ISSUE TITLE
Slots not populating

### ISSUE THREAD

**Issue by dejanmarich** [RasaHQ/rasa_nlu#1987]
**Rasa Core version**: 0.8.3 

**Python version**:  3.6.3

**Operating system** (windows, osx, ...): OSX 10.11.16 (El Capitan)

**Issue**: When using train_online.py script for dialogue training, when i enter my answer, slots does not fill. Slot "person" is filled most of the time, slot "currency" never and slot "amount" always. Wish I can figure out what is wrong, because they are all the same name as entities in NLU model.

**Content of domain file** (if used & relevant):
```yaml
slots:
  person:
    type: text
  value:
    type: float
  currency:
    type: text

entities:
  - value
  - currency
  - person

intents:
  - pay
  - greet
  - bye

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_bye:
    - 'Glad I could help! Bye!'
  utter_ask_person:
    - 'To whom you want to pay?'
  utter_ask_value:
    - 'How much would you like to pay?'
  utter_ask_currency:
    - 'In which currency'
  utter_ask_payconfirm:
    - 'Are you sure you want to pay VALUE: {value} CURRENCY: {currency} to PERSON: {person}'
  utter_payconfirmed:
    - 'You succesfuly paid VALUE: {value} CURRENCY: {currency} to PERSON: {person}'
  utter_anythingelse:
    - 'Can I help with anything else?'

actions:
    - utter_bye
    - utter_greet
    - utter_ask_value
    - utter_ask_person
    - utter_ask_currency
    - utter_ask_payconfirm
    - utter_payconfirmed
    - utter_anythingelse
```

![screen shot 2018-03-20 at 11 58 42](https://user-images.githubusercontent.com/30664809/37650762-1fa83426-2c36-11e8-8cf5-21c0372aa521.png)
