### ISSUE TITLE
Slot value not getting set

### ISSUE THREAD

**Issue by venkat915213** [RasaHQ/rasa_nlu#1990]
**Rasa Core version**: 0.8.2

**Python version**: 3.6

**Operating system** (windows, osx, ...): Osx

**Issue**: Slot value not getting set

**Content of domain file** (if used & relevant):
```
yaml file
slots:
  relationship:
    type: text
  channel:
    type: text
entities:
 - relationship
 - channel
intents:
 - greet
 - affirm
 - deny
 - inform
 - goodbye
 - default

templates: (not everything in included)
utter_relationship_info:
    - text: "Let me know your relationship to the child:"
      buttons:
      - title: "Parent"
        payload: "parent"
      - title: "Guardian"
        payload: "guardian"
```
Training data
```
"rasa_nlu_data": {
    "common_examples": [
     {
        "text": "parent", 
        "intent": "inform", 
        "entities": [
          {
            "start": 0, 
            "end": 6, 
            "value": "parent", 
            "entity": "relationship"
          }  
        ]
     }, and more
```
Story
```
## story_00000100
* greet
 - utter_ask
 - utter_relationship_info
* inform{"relationship": "parent"}
```
So when I start the bot, it utters for the relationship info. I enter "parent".  if my understanding is correct, inform intent uses the information passed in the to story to set the entity which in turn sets the slot value.

I created an action to check for the slot value by using this    dispatcher.utter_message(tracker.get_slot("relationship"))
 and i get the following error which i know is due to value is not being set.
```
2018-03-21 09:31:37 ERROR    rasa_core.processor - Encountered an exception while running action 'action_get_slot_info'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2018-03-21 09:31:37 ERROR    rasa_core.processor - 'NoneType' object has no attribute 'split' 
```
If I force it in my action to set the slot value using update method for the slotvalue, then I value is getting set.

Any help would be greatly appreciated. I am new this.

Thanks
Venkat
