### ISSUE TITLE
dispatcher.utter_message("searching") is not working

### ISSUE THREAD

**Issue by akshaydeeti1996** [RasaHQ/rasa_nlu#2026]
**Rasa Core version**:
0.8.5
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
windows 7
**Issue**:
The following code is not sending response "searching" to the bot ,when the ActionSearching is executed which has the intension of search
 
from rasa_core.actions import Action
class ActionSearching(Action):
    def name(self):
        return 'action_searching'

    def run(self, dispatcher, tracker, domain):
    	dispatcher.utter_message("searching")
    	return []

**Content of domain file** (if used & relevant):
```yaml

intents:
 - greet
 - goodbye
 - search

templates:
  utter_greet:
    - "hey there!"
    - "hey , how are you"
  utter_goodbye:
    - "goodbye :("
    - "Bye-bye"

actions:
- utter_greet
- utter_goodbye
- actions.ActionSearching
```
stories:
## s123               
* greet              
  - utter_greet
* search               
  - action_searching
* goodbye
  - utter_goodbye

## s15               
* greet              
  - utter_greet
* search               
  - action_searching
* goodbye
  - utter_goodbye

## s1657               
* greet              
  - utter_greet
* search               
  - action_searching
* goodbye
  - utter_goodbye

## s156788               
* greet              
  - utter_greet
* search               
  - action_searching
* goodbye
  - utter_goodbye

## s18788               
* greet              
  - utter_greet
* search               
  - action_searching
* goodbye
  - utter_goodbye
