### ISSUE TITLE
Dialogue transaction failed 

### ISSUE THREAD

**Issue by praveenrengarajan** [RasaHQ/rasa_nlu#2039]
**Rasa Core version**: 0.8

**Python version**:  3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**: Checking Simple conversation story to know about employee leave balance. 
![rasa-core-dialogue](https://user-images.githubusercontent.com/2884636/38496348-d8680ea2-3c1a-11e8-8237-9b139315bad8.png)

(1) First 3 times, transaction went as per the dialogue story. 
(2) After that, it's not pointed to the correct transactions. 

**_stories.md_**
## story_001
* greet
 - utter_greet
* leave_info
 - action_leave_info
* thank_you
 - utter_goodbye

## story_002
* greet 
 - utter_greet
* leave_info{"info_leave_type": "annual"}
 - action_leave_info
* thank_you
 - utter_goodbye`

**Content of domain file** (if used & relevant): but not used all, for testing used only 3
```yaml
slots:
  info_leave_type:
    type: text
  leave_day:
    type: text
  leave_type:
    type: text
  leave_applied_result:
    type: categorical
    values:
     - unknown
     - applied
     - already-taken
     - rejected

intents:
 - greet
 - thank_you
 - good_bye
 - leave_info
 - leave_request
 - deny
 - reject
 - accept

entities:
 - leave_day
 - leave_type
 - info_leave_type

templates:
  utter_greet:
    - "hey there!"
  utter_goodbye:
    - "goodbye :("
  utter_thank_you:
    - "you're welcome"
  utter_default:
    - "default message"
  utter_youarewelcome:
    - "you're very welcome"
  utter_ask_howcanhelp:
    - "how can I help you?"
  utter_leavetype:
    - text: "which leave type?"
      buttons:
        - title: "annual leave"
          payload: "annual"
        - title: "sick leave"
          payload: "sick"
        - title: "maternity leave"
          payload: "maternity"
        - title: "paternity leave"
          payload: "paternity"
  utter_leave_day:
    - "for which day?"
  utter_on_it:
    - "I'm on it"
  utter_apply_leave_notcompleted:
    - "Sorry, I am unable to complete your process."
  utter_leave_applied_successfully:
    - "Successfully, your leave request submitted."
  
actions:
  - utter_default
  - utter_thank_you
  - utter_apply_leave_notcompleted
  - utter_leave_applied_successfully
  - utter_on_it
  - utter_greet
  - utter_goodbye
  - utter_youarewelcome
  - utter_leavetype
  - utter_leave_day
  - utter_ask_howcanhelp
  - bot.ActionApplyLeave
  - bot.ActionLeaveInfo
```
**_bot.py_**
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import argparse
import logging
import warnings
import sys

from policy import RestaurantPolicy
from rasa_core import utils
from rasa_core.actions import Action
from rasa_core.agent import Agent
from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.events import SlotSet
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.policies.memoization import MemoizationPolicy

logger = logging.getLogger(__name__)

if not sys.warnoptions:
    warnings.simplefilter("ignore")
	
class ApplyLeaveAPI(object):
    def search(self, info):
        return "Leave applied successfully"

class ActionApplyLeave(Action):
    def name(self):
        return 'action_apply_leave'

    def run(self, dispatcher, tracker, domain):
        #dispatcher.utter_message("applying leave")
        #leave_api = ApplyLeaveAPI()
        return [SlotSet("leave_applied_result", "unknown")]
        

class ActionLeaveInfo(Action):
    def name(self):
        return 'action_leave_info'

    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message("To know more about your leave details: Visit leave portal")
        
        return []

def train_dialogue(domain_file="assistant_domain.yml",
                   model_path="models/dialogue",
                   training_data_file="data/stories.md"):
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(), RestaurantPolicy()])

    agent.train(
            training_data_file,
            max_history=3,
            epochs=400,
            batch_size=100,
            validation_split=0.2
    )

    agent.persist(model_path)
    return agent

def train_nlu():
    from rasa_nlu.converters import load_data
    from rasa_nlu.config import RasaNLUConfig
    from rasa_nlu.model import Trainer

    training_data = load_data('data/training_data.json')
    trainer = Trainer(RasaNLUConfig("nlu_model_config.json"))
    trainer.train(training_data)
    model_directory = trainer.persist('models/nlu/', fixed_model_name="current")

    return model_directory

def run(serve_forever=True):
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    agent = Agent.load("models/dialogue", interpreter=interpreter)

    if serve_forever:
        agent.handle_channel(ConsoleInputChannel())
    return agent

if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")

    parser = argparse.ArgumentParser(
            description='starts the bot')

    parser.add_argument(
            'task',
            choices=["train-nlu", "train-dialogue", "run"],
            help="what the bot should do - e.g. run or train?")
    task = parser.parse_args().task

    # decide what to do based on first parameter of the script
    if task == "train-nlu":
        train_nlu()
    elif task == "train-dialogue":
        train_dialogue()
    elif task == "run":
        run()
    else:
        warnings.warn("Need to pass either 'train-nlu', 'train-dialogue' or "
                      "'run' to use the script.")
        exit(1)
`
