### ISSUE TITLE
buttons- where to put the quotation marks?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#2042]
hi,

I struggle how to format buttons with intents and entities for slack.

```yaml
utter_bla
    - text: "balaba"
      buttons:
         - title: "yes"
           payload: "/affirm{entity: value}"
         - title: "No"
           payload: "/deny{entity: value}"

```
When I use this slack cannot parse the payload. It wants quotation marks. But if I do them there is an error with the domain.yml because of the quotation marks??!!

```yaml
utter_bla
    - text: "balaba"
      buttons:
         - title: "yes"
           payload: "/affirm{"entity":" value"}"
         - title: "No"
           payload: "/deny{"entity": "value"}"

```

Where doo you have to set the quotation marks?
