### ISSUE TITLE
how to navigate through a link when a button is choose by user? 

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_nlu#2081]
**Rasa Core version**:

**Python version**: 

**Operating system** (ubuntu):

**Issue**: I added up buttons in my yml file.In the example of mood bot buttons are implemented and image is displayed.I'm trying to do the same thing but instead of giving an image, I tried out a  link.
I'm not get any type of response when i give a link.when I replaced the link with image and put same info link , i'm getting only text response but not needed link and details of link.

**Content of domain file** (if used & relevant):
```yaml
 utter_mg_query:
    - text : "Sorry i can't help you on that info. Please provide your details here"
      link: "https://xxxxxxxx/contact-us-form/
```
I connected my bot model to slack and testing my bot, please let me know, how can I display link instead of image.
& one more problem , if i'm trying to fix more than 5 buttons, then none of the buttons are shown in the slack,I'm just getting text message. 

Thanks in advance
