### ISSUE TITLE
Temporary field 

### ISSUE THREAD

**Issue by fdevillard** [RasaHQ/rasa_nlu#2089]
**Rasa Core version**: 0.9.0a3

**Python version**: Python 3.5.2

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**: I try to handle a form-filling like dialogue where API calls are used in order to disambiguate the user's query. And typically, I would need to store intermediate results from the API and, typically, this information should be clean when a given slot change of value.

The idea being:

- The user search for a term (let say that this search terms are stored in a slot which is called `search_keywords`)
- The action find the most relevant search result, and stores it in a temporary slot
- User/actions can play with this temporary data
- Once the user change the `search_keywords` slot, the temporary slot is cleaned 
- Typically, if this temporary slot is featurized, action that will re-fill the temporary slot is triggered and the value is presented

**Proposition**:

Update the domain's schema to support:

```yaml
slots:
  search_keywords:
    type: unfeaturized
  temporary:
    type: text
    depends_on: 
      - search_keywords
```

Which causes that whenever the system generate a `slot{search_keywords: any}` it'll generate `slot{temporary: null}` as well.

Concerning the domain file, the opposite way might be easier to implement:

```yaml
slots:
  search_keywords:
    type: unfeaturized
    cascade_on: temporary
  temporary:
    type: text
```

Does it make sense? Is this feature worth it for you?
