### ISSUE TITLE
how to make pre-filled (manually filled) slots to impact action prediction?

### ISSUE THREAD

**Issue by lisongshan** [RasaHQ/rasa_nlu#2094]
**Rasa Core version**:0.8.6

**Python version**: 3.6

**Operating system** (windows, osx, ...):osx

**Issue**: how to make pre-filled slots to impact action prediction

**Content of domain file** (if used & relevant):
```yaml
intents:
 - findWalmart
 - inform

entities:
 - location

slots:
  location:
    type: text

templates:
  action_findWalmart:
    - "here is the walmart store I found for location {location}!" 
  action_prompt_for_location:
    - "what is your location?"
    
actions:
  - action_findWalmart
  - action_prompt_for_location
```
``` story.md
```
***What  I want to achieve:***

```
## when location slot is not pre-filled:
* findWalmart
    - action_prompt_for_location
* inform{"location":"mylocation"}
    - action_findWalmart

## when location slot is pre-filled (using slotset event with location value from other source):
* findWalmart
    - action_findWalmart
```

I tried with this training stories, but it doesn't achieve my goal of not asking location when location slot is already filled.

``` attempted story files:
## st_1
* findWalmart{"location":"mylocation"}
    - action_findWalmart

## st_2
* findWalmart
    - action_prompt_for_location
* inform{"location":"mylocation"}
    - action_findWalmart
```
