### ISSUE TITLE
What to do if the intent isn't recognized ?

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/rasa_nlu#2143]
**Rasa Core version**:

```
(MoodbotEnv) mike@mike-thinks:~/Programing/Rasa_tutorial/moodbot4$ pip list :
...
rasa-core (0.9.0a3)
rasa-nlu (0.12.3)
```

**Python version**: 

```
(MoodbotEnv) mike@mike-thinks:~/Programing/Rasa_tutorial/moodbot4$ python -V 
Python 3.5.2
```

**Operating system** : Linux 16.04

**Issue**:

Having troubles with the tutorial, I followed the weather rasa chatbot one provided by [Justina Petraityte](https://vimeo.com/254777331), you can find the GitHub repository [here](https://github.com/JustinaPetr/Weatherbot_Tutorial). Yet my chatbot never recognizes the intent I try to provide him, which has to be the location,  and I don't know how to handle this case as far as it create an error when calling for the weather API, which is therefore empty.

For instance I tried to ask for a the weather in Italy but, as you can see [here](https://i.stack.imgur.com/Jubgb.png). It don't recognizes Italy as an intent even if it was in `data.json`.

Therefore, what to do when the intent isn't recognized ? Should we still save it to the stories.md ?

**Content of domain file** :
```
action_factory: null
action_names:
- utter_greet
- utter_goodbye
- utter_ask_location
- action_weather
actions:
- utter_greet
- utter_goodbye
- utter_ask_location
- actions.ActionWeather
config:
  store_entities_as_slots: true
entities:
- location
intents:
- greet
- goodbye
- inform
slots:
  location:
    initial_value: null
    type: rasa_core.slots.TextSlot
templates:
  utter_ask_location:
  - text: In what location?
  utter_goodbye:
  - text: Talk to you later.
  - text: Bye bye :(
  utter_greet:
  - text: Hello! How can I help?
topics: []
```
