### ISSUE TITLE
Bug in MemoizationPolicy? please give a quick fix.

### ISSUE THREAD

**Issue by lisongshan** [RasaHQ/rasa_nlu#2156]
**Rasa Core version**:0.8.6

**Python version**: 3.6

**Operating system** (windows, osx, ...):osx

**Issue**:
looks like there is a bug in MemoizationPolicy

**Content of domain file**:
```yaml
slots:
  city:
    type: text
  state:
    type: text

intents:
  - 1.u_inform
  - 1.u_request

entities:
  - city
  - state

templates:
  Action.b_prompt.city:
  - "dummy"
  Action.b_prompt.state:
  - "dummy"
  goal.1.1:
  - "dummy"

actions:
  - Action.b_prompt.city
  - Action.b_prompt.state
  - goal.1.1
```
**Problem details:
```yaml
I have two story files for training MemoizationPolicy

stories_1_only.md:
## story_60
  - slot{"city": "text"}
* 1.u_request
  - Action.b_prompt.state
* 1.u_inform{"state": "text"}
  - goal.1.1

stories_2_only.md:
## story_1
  - slot{"city": "text", "state": "text"}
* 1.u_request
  - goal.1.1

## story_2
  - slot{"city": "text"}
* 1.u_request
  - Action.b_prompt.state
* 1.u_inform{"state": "text"}
  - goal.1.1

I trained with these two training files with max_history = 1, here is the two memorized_turns.json files I got respectively:

File memorized_turns_1_only.json, result from stories_1_only.md:
{
  "lookup": {
    "eJyLjo4uzskviU/OLKmMN9BRMIyNjQUATzgHDw==": 0,
    "eJyLjo7OzCtJzSuJN9QrjS9KLSxNLS7RUTCM1VGILs7JL4lPziypjDeAihQUpZbFOyaXZObn6SXFFxTl5xaU6BWXJJakghTExgIASzobmA==": 0,
    "eJyLjo7OzCtJzSuJN9QrjS9KLSxNLS7RUTCM1VGILs7JL4lPziypjDeAihQUpZbFJyaXZObnxedkFgP1gSRiYwF43BjG": 3,
    "eJyLjo7OzCtJzSuJN9Qrjc/MS8svytVRMIzVUYgGCmaWVMYXlySWpEKFinPyS+KTQaIGyCJgJXChgqLUsvj0/MQcPUM9Q5BYbCwAJIciLQ==": 0,
    "eJyLjo7OzCtJzSuJN9Qrjc/MS8svytVRMIzVUYgGCmaWVMYXlySWpEKFinPyS+KTQaIGyCJgJXChgqLUsvjE5JLM/Lz4nMxioOEgidhYAObyJTg=": 4
  }
}

File memorized_turns_2_only.json, result from stories_2_only.md:
{
  "lookup": {
    "eJyLjo4uzskviU/OLKmMN9BRMIyNjQUATzgHDw==": 0,
    "eJyLjo7OzCtJzSuJN9QrjS9KLSxNLS7RUTCM1VGILs7JL4lPziypjDeAihQUpZbFp+cn5ugZ6hmCxGJjAfScFbs=": 0,
    "eJyLjo7OzCtJzSuJN9QrjS9KLSxNLS7RUTCM1VGILs7JL4lPziypjDeAihQUpZbFOyaXZObn6SXFFxTl5xaU6BWXJJakghTExgIASzobmA==": 0,
    "eJyLjo7OzCtJzSuJN9QrjS9KLSxNLS7RUTCM1VGILs7JL4lPziypjDeAihQUpZbFJyaXZObnxedkFgP1gSRiYwF43BjG": 4,
    "eJyLjo7OzCtJzSuJN9Qrjc/MS8svytVRMIzVUYgGCmaWVMYXlySWpEKFinPyS+KTQaIGyCJgJXChgqLUsvj0/MQcPUM9Q5BYbCwAJIciLQ==": 0,
    "eJyLjo7OzCtJzSuJN9Qrjc/MS8svytVRMIzVUYgGCmaWVMYXlySWpEKFinPyS+KTQaIGyCJgJXChgqLUsvjE5JLM/Lz4nMxioOEgidhYAObyJTg=": 4
  }
}
```
**What is the bug:
```yaml
index 3 (for key eJyLjo7OzCtJzSuJN9QrjS9KLSxNLS7RUTCM1VGILs7JL4lPziypjDeAihQUpZbFJyaXZObnxedkFgP1gSRiYwF43BjG), which corresponding to Action.b_prompt.state is gone in memorized_turns_2_only.json

please make sure to use max_history = 1 for reproduce the problem.
```
**Asking for help:
```yaml
This is a block for my current project, I am looking for a quick fix.  your help is greatly appreciated.
```
