### ISSUE TITLE
Understanding of dialogue generation

### ISSUE THREAD

**Issue by jahid-ict** [RasaHQ/rasa_nlu#2159]
**Rasa Core version**: 0.8.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Windows 10

**Issue**: 
I am trying to write a bot which will calculate withholding tax for two country. But I am facing problem in dialogue generation. I have read many resources but failed to understand. Here country is a list of all country of the world and payment types are interest and dividend. I am providing my domain file below. please help me by writing a story of the following use cases:
**Use case :**
_User: Hello
Bot: Hello!! Write something:
User: withholding tax between Bangladesh and USA.
Bot: What is the payment type:
User: interest
Bot: Result is:
User: Thanks you.
Bot: Thank you._

I am confused how to check if I got paying and receiving country in a single story for all country? What I need to append in the following story?

**## story 1**
_*greet
-utter_greet
*withholding_tax_

Thanks in advance.
**Content of domain file** (if used & relevant):
```
slots:
  paying_country:
    type: text
  receiving_country:
    type: text
  payment_type:
    type: text
  result:
    type: unfeaturized

entities:
- paying_country
- receiving_country
- paymeny_type

intents:
 - withholding_tax
 - greet

templates:
  utter_greet:
    - "Hello!! Write something:"
  utter_ask_paying_country:
    - "What is the paying country:"
  utter_ask_receiving_country:
    - "What is the receiving country:"
  utter_ask_payment _type:
    - "What is the payment type:"
  utter_show_result:
    - "{result}"
  utter_thankyou:
    - "Thank you."

actions:
- utter_greet
- utter_ask_paying_country
- utter_ask_receiving_country
- utter_ask_payment _type
- utter_show_result
- utter_on_it
- utter_thankyou
- bot.withholding_tax
   
```
