### ISSUE TITLE
How can I improve accuracy of matching action?

### ISSUE THREAD

**Issue by linanzhu** [RasaHQ/rasa_nlu#2164]
**Rasa Core version**: 0.9.0a6
**Python version**: 2.7.12
**Operating system** (windows, osx, ...): ubuntu 16.04

**Issue**:
I used online training and added output story to my "story.md".  And trained it.
Normally it works fine. But sometime(or often), it gives me wrong answer(action).
For example,  
   1. what is your name -->  it says name (correct)
   2. what time is it --> it says time (correct)
   3. play music --> it plays music (correct)
   4. what is your name --> it says age (**incorrect**)  
   5. what time is it --> it says time (correct)
   6. .....

Something like this.  It is affected by story use case?  Then if I add more use case(different question sequence), will it be better? 

**Parts of Story**:
```
## story_name
* personalInfo_name
 - utter_speak_name

## story_age
* personalInfo_physicalStatus_age
 - utter_speak_age

## Generated Story 5147528509296524160
* personalInfo_name
    - utter_speak_name
* personalInfo_physicalStatus_age
    - utter_speak_age
* personalInfo_physicalStatus_height
    - utter_speak_height
* personalInfo_physicalStatus_birthDate
    - utter_speak_birthdate
* personalInfo_physicalStatus_weight
    - utter_speak_weight
* personalInfo_physicalStatus_gender
    - utter_speak_gender
* personalInfo_physicalStatus_species
    - utter_speak_species
* personalInfo_residentialType_home
    - utter_speak_home
* personalInfo_family_sibling
    - utter_speak_sibling
* personalInfo_friend
    - utter_speak_friend

## Generated Story 5734599474132960291
* dailyInformation_time
    - action_time
* dailyInformation_weather
    - action_weather
    - slot{"city": null}
* dailyInformation_time
    - action_time
* dailyInformation_weather{"city": "london"}
    - slot{"city": "london"}
    - action_weather
    - slot{"city": null}
* dailyInformation_time
    - action_time
```

**Content of domain file** (if used & relevant):
```yaml

intents:
  - personalInfo_physicalStatus_age
  - personalInfo_physicalStatus_birthDate
  - personalInfo_physicalStatus_birthPlace
  - personalInfo_physicalStatus_height
  - personalInfo_physicalStatus_weight
  - personalInfo_physicalStatus_gender
  - personalInfo_physicalStatus_species
  - personalInfo_residentialType_home
  - personalInfo_family_parent
  - personalInfo_family_sibling
  - personalInfo_friend
  - personalInfo_name
  - dailyInformation_time
  - dailyInformation_weather
  - mediaService_music_play
  - mediaService_music_stop
  - mediaService_music_category
  - controlDevice_volume
  - controlDevice_takephoto
  - controlDevice_takevideo
  - controlDevice_move_forward
  - controlDevice_move_backwards
  - controlDevice_move_turnleft
  - controlDevice_move_turnright
  - controlDevice_setalarm
  - knowledgeInfo_translation
  - knowledgeInfo_wikipedia_object
  - knowledgeInfo_wikipedia_human
  - dailyInformation_calculation_plus
  - dailyInformation_calculation_minus
  - dailyInformation_calculation_multiply
  - dailyInformation_calculation_devide

slots:
  city:
    type: text
  vol_direction:
    type: text
  object_to_know:
    type: text
  someone_to_know:
    type: text
  music_category:
    type: text
  level:
    type: text
  calc_nums:
    type: list
  translation_text:
    type: text
  language:
    type: text

entities:
  - object_to_know
  - someone_to_know
  - vol_direction
  - level
  - music_category
  - city
  - calc_nums
  - translation_text
  - language


templates:
  utter_speak_age:
    - "I am 16"
    - "I am 16 years old"
  utter_speak_birthdate:
    - "I was just built up recently"
    - "I am very new to this world, kind of baby"
  utter_speak_birthplace:
    - "Well I can say a laboratory is my birthplace"
    - "I was built in a lab"
  utter_speak_height:
    - "My body is computer hardware. So 50 or 60 cm, I think"
    - "Around 50 cm"
  utter_speak_weight:
    - "Well just 5kg, I think"
    - "I am not that heavy, you know"
  utter_speak_gender:
    - "I am not animal nor plant. I am just robot"
    - "I am a robot. So I am not girl nor boy"
  utter_speak_species:
    - "I am a robot"
  utter_speak_home:
    - "My home is a lab in Ningbo city, China"
    - "I was built in Ninbo city, China"
  utter_speak_parent:
    - "I consider people who developed me as my parents"
    - "I have father and mother. They are engineers who made me"
  utter_speak_sibling:
    - "I don't have them yet. But my parents are making them"
    - "My parent said that I will have my clone soon"
  utter_speak_friend:
    - "I have many friends on the net. Alexa and Google home are also my friends"
    - "There are my friends on the net. And you are my friend too"
  utter_speak_name:
    - "My name is Genie"
    - "You can call me Genie"
  utter_ask_music_category:
    - "what kind of music do you want to listen ?"
    - "what music do you want ?"
  utter_speak_not_clear:
    - "Sorry, I didn't catch clearly"
    - "I missed some part what you said. Sorry"
  utter_ask_what_time:
    - "what time is ok for you ?"
    - "when do you want ?"
  utter_action_move_forward:
    - "i am moving forward"
  utter_action_move_backwards:
    - "i am moving backwards"
  utter_action_turn_left:
    - "i am turning to the left"
  utter_action_turn_right:
    - "i am turning to the right"
  utter_action_take_photo:
    - "i am taking photo"
  utter_action_take_video:
    - "i am taking video"


actions:
  - utter_speak_age
  - utter_speak_birthdate
  - utter_speak_birthplace
  - utter_speak_height
  - utter_speak_weight
  - utter_speak_gender
  - utter_speak_species
  - utter_speak_home
  - utter_speak_parent
  - utter_speak_sibling
  - utter_speak_friend
  - utter_speak_name
  - utter_ask_music_category
  - utter_speak_not_clear
  - utter_ask_what_time
  - utter_action_move_forward
  - utter_action_move_backwards
  - utter_action_turn_left
  - utter_action_turn_right
  - utter_action_take_photo
  - utter_action_take_video

  - actions.GetTime
  - actions.ActionWeather
  - actions.PlayMusic
  - actions.StopMusic
  - actions.ControlVolume
  - actions.GetObject
  - actions.GetHuman
  - actions.Plus
  - actions.Minus
  - actions.Multiplication
  - actions.Division
  - actions.Translation
  - actions.SetAlarm
```
