### ISSUE TITLE
http server, how to get rasa_core response message

### ISSUE THREAD

**Issue by Primtek** [RasaHQ/rasa_nlu#2166]
**Rasa Core version**:
0.9.0
**Python version**: 

python-2.7.5-68.el7.x86_64

**Operating system** (windows, osx, ...):
Linux centOS 7

**Issue**:
how to get response message from rasa_core?

I tried:
python -m rasa_core.server -d models/dialogue -u models/nlu/default/current/

and send http post to rasa_core it returns

{"next_action":"utter_on_it","tracker":{"events":null,"latest_event_time":1527258019.54365,"latest_message":{"entities":[],"intent":{"confidence":0.8640301001448453,"name":"greet"},"intent_ranking":[{"confidence":0.8640301001448453,"name":"greet"},{"confidence":0.0551844536047635,"name":"affirm"},{"confidence":0.031602866703251624,"name":"deny"},{"confidence":0.028090034883455364,"name":"inform"},{"confidence":0.014469431313454689,"name":"thankyou"},{"confidence":0.006623113350229745,"name":"request_info"}],"text":"hello there"},"paused":false,"sender_id":"default","slots":{"cuisine":null,"info":null,"location":null,"matches":null,"people":null,"price":null}}}

{"next_action":"utter_ask_cuisine","tracker":{"events":null,"latest_event_time":1527258149.995423,"latest_message":{"entities":[],"intent":{"confidence":0.8640301001448453,"name":"greet"},"intent_ranking":[{"confidence":0.8640301001448453,"name":"greet"},{"confidence":0.0551844536047635,"name":"affirm"},{"confidence":0.031602866703251624,"name":"deny"},{"confidence":0.028090034883455364,"name":"inform"},{"confidence":0.014469431313454689,"name":"thankyou"},{"confidence":0.006623113350229745,"name":"request_info"}],"text":"hello there"},"paused":false,"sender_id":"default","slots":{"cuisine":null,"info":null,"location":null,"matches":null,"people":null,"price":null}}}

{"next_action":"utter_on_it","tracker":{"events":null,"latest_event_time":1527258182.325367,"latest_message":{"entities":[],"intent":{"confidence":0.8640301001448453,"name":"greet"},"intent_ranking":[{"confidence":0.8640301001448453,"name":"greet"},{"confidence":0.0551844536047635,"name":"affirm"},{"confidence":0.031602866703251624,"name":"deny"},{"confidence":0.028090034883455364,"name":"inform"},{"confidence":0.014469431313454689,"name":"thankyou"},{"confidence":0.006623113350229745,"name":"request_info"}],"text":"hello there"},"paused":false,"sender_id":"default","slots":{"cuisine":null,"info":null,"location":null,"matches":null,"people":null,"price":null}}}

{"next_action":"utter_ask_cuisine","tracker":{"events":null,"latest_event_time":1527258203.972284,"latest_message":{"entities":[],"intent":{"confidence":0.8640301001448453,"name":"greet"},"intent_ranking":[{"confidence":0.8640301001448453,"name":"greet"},{"confidence":0.0551844536047635,"name":"affirm"},{"confidence":0.031602866703251624,"name":"deny"},{"confidence":0.028090034883455364,"name":"inform"},{"confidence":0.014469431313454689,"name":"thankyou"},{"confidence":0.006623113350229745,"name":"request_info"}],"text":"hello there"},"paused":false,"sender_id":"default","slots":{"cuisine":null,"info":null,"location":null,"matches":null,"people":null,"price":null}}}

{"next_action":"action_listen","tracker":{"events":null,"latest_event_time":1527258230.48621,"latest_message":{"entities":[],"intent":{"confidence":0.8640301001448453,"name":"greet"},"intent_ranking":[{"confidence":0.8640301001448453,"name":"greet"},{"confidence":0.0551844536047635,"name":"affirm"},{"confidence":0.031602866703251624,"name":"deny"},{"confidence":0.028090034883455364,"name":"inform"},{"confidence":0.014469431313454689,"name":"thankyou"},{"confidence":0.006623113350229745,"name":"request_info"}],"text":"hello there"},"paused":false,"sender_id":"default","slots":{"cuisine":null,"info":null,"location":null,"matches":null,"people":null,"price":null}}}

**Content of domain file** (if used & relevant):
```yaml
slots:
  cuisine:
    type: text
  people:
    type: text
  location:
    type: text
  price:
    type: text
  info:
    type: text
  matches:
    type: unfeaturized

entities:
- location
- info
- people
- price
- cuisine

intents:
 - greet
 - affirm
 - deny
 - inform
 - thankyou
 - request_info

templates:
  utter_greet:
    - "hey there!"
  utter_goodbye:
    - "goodbye :("
    - "Bye-bye"
  utter_default:
    - "default message"
  utter_ack_dosearch:
    - "ok let me see what I can find"
  utter_ack_findalternatives:
    - "ok let me see what else there is"
  utter_ack_makereservation:
    - text: "ok making a reservation"
      buttons:
        - title: "thank you"

```
