### ISSUE TITLE
Clarification of intent/entities

### ISSUE THREAD

**Issue by linazu** [RasaHQ/rasa_nlu#2176]
**Rasa Core version**: 0.9.0

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): -

**Issue**:

While working on a bot which handles date inputs, we realised that there are some ambiguous date formats which even for people are confusing and require clarification. For example, inputting "10-12" both dd-mm and mm-dd formats can be valid depending from where the person is coming from.

We have encountered other cases as well where our bot misunderstands the language. Another example is when user tells “end of the month” it assumes it’s 1st of the month and does not ask for confirmation or clarification of the input.

How would you do that in Rasa? Is that something that we should do ourselves or Rasa supports this type of situation?

If Rasa does not support it, we are afraid that this would pollute our stories with this clarification behaviour. Any advice would be welcome!

**Content of domain file** (if used & relevant):
```yaml
language: "en"

pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name: "ner_duckling"
  dimensions: ["time", "number"]

data: "resources/data/nlu.md"
```
