### ISSUE TITLE
Rasa Chat bot doesn't reply

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_nlu#2177]
**Rasa Core version**: 0.9.0

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX 10.11.6

**Issue**: Rasa Chatbot doesn't reply even the chatbot is loaded

**Content of domain file** (if used & relevant):
```yaml
intents:
 - greet
 - inform
 - confirm
 - goodbye

entities:
 - experienceYears
 - job
 - city

slots:
 experienceYears:
  type: text
 job:
  type: text
 city:
  type: text

templates:
 utter_greet:
  -"bonjour, comment puis-je vous aider?"
  -"bonjour"
 utter_ask_job:
  -"quel est votre travail?"
  -"Puis-je savoir quel travail?"
 utter_ask_experience:
  -"Depuis combien d'années travaillez-vous pour ce travail?"
 utter_ask_city:
  -"Où travailles-tu?"
 utter_answer_salary:
  -"votre salarie est 35000 euros par an"
 utter_goodbye:
  -"bye, c'est un plaisir de vous aider"

actions:
 - utter_greet
 - utter_ask_job
 - utter_ask_experience
 - utter_ask_city
 - utter_answer_salary
 - utter_goodbye
```
Hello, I am traing my chatbot in French. here is my config_spacy.yml file:
language: "fr"
pipeline:  
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"
- name: "ner_crf"
data: "./data/new_data.json"
path: "./projects"

I have trained successfully dialogue_model using: python3 -m rasa_core.train -s data/stories.md -d domain.yml -o projects/dialogue2
then python3 -m rasa_core.run -d projects/dialogue2 -u projects/default/model_20180529-105625
to run the chatbot. But it can not reply properly as the attached below: 
<img width="1244" alt="screen shot 2018-05-29 at 12 09 14 pm" src="https://user-images.githubusercontent.com/39526598/40656061-84f621a0-6343-11e8-889c-f183f53f6a07.png">
