### ISSUE TITLE
[FormAction] Variable in utterance not filled with previously set slot

### ISSUE THREAD

**Issue by franticBIT** [RasaHQ/rasa_nlu#2209]
**Rasa Core version**: 0.9.0a3

**Python version**: 3.6

**Operating system** (windows, osx, ...): macOS, Docker

**Issue**:
I'm trying to implement a FormAction in which the user should provide an email address and the confirm it. This works in general, but I am having trouble with the filling of the slot with the previously provided email address in the confirmation `utter_ask_*`. It is just not. Any idea, if this is expected behaviour or how I can fix it?

The variable is filled with the slot in a new utterance after the action is submitted.

**Extract from FormAction code**
```python
@staticmethod
def required_fields():
    return [
        EntityFormField("email", "new_email"),
        BooleanFormField("new_email_confirmed", "conversation_confirm", "conversation_cancel")
    ]
```

**Extract of domain file** (if used & relevant):
```yaml
slots:
  requested_slot:
    type: unfeaturized
  new_email:
    type: text
  new_email_confirmed:
    type: bool

entities:
  - email

intents:
  - conversation_confirm
  - conversation_cancel
  - account_change_email
  - account_provide_email

actions:
  - utter_conversation_canceled
  - utter_ask_new_email
  - utter_ask_new_email_confirmed
  - utter_account_changed_email
  - action.ActionEmailForm

templates:
  utter_conversation_canceled:
    - text: "Okay, I will not do that."

  utter_ask_new_email:
    - text: "What is the email address you want it to change to?"

  utter_ask_new_email_confirmed:
    - text: "Should I change your email to {new_email}?"
    - text: "I will change your email to {new_email}. Is that okay?"

  utter_account_changed_email:
    - text: "Okay, I changed your email address to {new_email}."
```

**Extract of Stories**
```markdown
## change email
* account_change_email
  - action_email_form
  - slot{"requested_slot": "new_email"}
* account_provide_email{"email": "name@domain.com"}
  - action_email_form
  - slot{"new_email": "name@domain.com"}
  - slot{"requested_slot": "new_email_confirmed"}
> cp_account_check_email

## confirm email
> cp_account_check_email
* conversation_confirm
  - action_email_form
  - slot{"new_email_confirmed": true}
  - utter_account_changed_email

## cancel email change
> cp_account_check_email
* conversation_cancel
  - action_email_form
  - slot{"new_email_confirmed": false}
  - utter_conversation_canceled
```
