### ISSUE TITLE
Adding a number as a slot

### ISSUE THREAD

**Issue by nahidalam** [RasaHQ/rasa_nlu#2210]
**Rasa Core version**: 0.9.0a6

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSx

**Issue**:
I need to add a number as a slot (it is a product SKU). For example, I have a product SKU called `900` and I added it in the slot like below:

```
900:
    type: text
```
Now when I train the dialogue management model, I get error

`TypeError: '<' not supported between instances of 'int' and 'str'`

What am I missing?

**Content of domain file** (if used & relevant):
```
slots:
  product:
    type: text
  router:
    type: text
  900:
    type: text


intents:
 - greet
 - goodbye
 - order_product


entities:
 - product
 - router

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye'
  utter_affirm:
    - 'Thats right'
    - 'You are correct'
  utter_ask_product_name:
    - 'Which product?'


actions:
 - utter_greet
 - utter_goodbye
 - utter_affirm
 - utter_ask_product_name
 - actions.ActionOrderProduct


```
