### ISSUE TITLE
Buttons and action

### ISSUE THREAD

**Issue by Graziella-Husson** [RasaHQ/rasa_nlu#2214]
**Rasa Core version**: master

**Python version**: 3.5

**Operating system** (windows, osx, ...): linux

**Issue**:

I wonder how to trigger a custom action with some buttons. What do I have to specify in the payload of my button?
```
  utter_ask_smthg:
  - text: "BLA"
    buttons:
    - title: "button1"
      payload: _action_name
```
In fact, among other things, I want to set a slot to None when the button is clicked
