### ISSUE TITLE
slot filling for same question but different entities

### ISSUE THREAD

**Issue by sumit6192** [RasaHQ/rasa_nlu#2225]
**Rasa Core version**: 0.9.3

**Python version**: 3.6

**Operating system** (windows, osx, ...):windows  10

**Issue**:

slot filling for same question but different entities

**Content of domain file** (if used & relevant):
```yaml
intents:
    - greet
    - dpo
        
entities:
    - year
    - vendor
    
slots:
    year:
        type: text
    vendor:
        type: text
 
templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_askslot:
        - 'Do you want it for Vendor category or for Year?'
    utter_askslots:
        - 'Do you want it for Vendor category or for Year?'
actions:
    - utter_greet
    - utter_askslot
   - actions.AskDpo 
    - utter_askslots
    - actions.Vendors
```

Hi Team ,
  i have two questions for same intent DPO  as follows:
what is my DPO for this year (or year value like 2018)?
what is my DPO for Advertising?

but when i try to perform slot filling using slots year and vendor its not working kindly guide me on this.

my stories.md
```md
## first story
* greet
    - utter_greet

## third story
* OverallSpend
	- overall_spend

## fourth story
* DisocuntCapturePercentage
	- discoount_capture_percentage

## fifth story
* dpo
    - action_askingDpo
* dpo
    - utter_askslot
	- action_askingDpo

## sixth story
* dpo_compare
	- action_comparingDpo

## seventh story
* dpo
    - action_askingVendor

* dpo
    - utter_askslots
    - action_askingVendor
## Generated Story 2226571628681787315
* dpo
    - utter_askslot
* dpo{"year": "2016"}
    - slot{"year": "2016"}
    - action_askingDpo
    - export

## Generated Story 8646781598051767970
* dpo
    - utter_askslot
* dpo{"year": "previous year"}
    - slot{"year": "previous year"}
    - action_askingDpo
    - export
```
