### ISSUE TITLE
Error when trying to run train.py file

### ISSUE THREAD

**Issue by rpeesapa** [RasaHQ/rasa_nlu#2232]
**Rasa Core version**: 0.9.5

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):Windows

**Issue**: I have been following a tutorial online and got to the point where I made stateless stories and copied the train.py code from rasa github to train my diagolue model. In my bot, I also have an action.py file that follows the exact same format as the examples provided. However, when I try to run the dialogue trainer, I get an error saying A"TypeError: ActionComInfo() missing 1 required positional argument: 'Action' "

**Content of domain file** (if used & relevant):
```
slots:
 company:
  type: text
 
intents:
 - greet
 - goodbye
 - Company_info
 
entities:
 - company
 
templates:
 utter_greet:
  - 'Hello. How can I help?'
 utter_goodbye:
  - 'Goodbye'
  - 'See you later'
 utter_ask_company:
  - 'What Company?'
actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_company
 - actions.ActionComInfo

```

**Content of Action file** (if used & relevant):
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core.actions.action import Action
from rasa_core.events import SlotSet

def ActionComInfo(Action): 
 def name(self):
  return "action_cominfo"
 
 def run(self, dispatcher, tracker, domain):
  response = ""
  with open("database.txt") as input_data:
    for line in input_data:
     if line.strip()== 'UBS-Company Info':
      break
    for line in input_data:
     if line.strip()== 'End':
      break
     else:
      response+=line  
  dispatcher.utter_message(response)
  return []
```

**Content of train_init.py file** (if used & relevant):
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")

    training_data_file = 'data/stories.md'
    model_path = 'models/dialogue'

    agent = Agent("chatbot_domain.yml",policies=[MemoizationPolicy(), KerasPolicy()])

    training_data = agent.load_data(training_data_file)

    agent.train(
            training_data,
            augmentation_factor=50,
            max_history=2,
            epochs=500,
            batch_size=10,
            validation_split=0.2
    )

    agent.persist(model_path)
```
