### ISSUE TITLE
Check if slot is filled and control the flow in stories

### ISSUE THREAD

**Issue by saivisal1** [RasaHQ/rasa_nlu#2239]
**Rasa Core version**: 0.9.6

**Python version**: 3.7

**Operating system** (windows, osx, ...): OS X

**Issue**: 

I have a slot city which is used for 2 custom actions weather check and petrol price check. If slot is not set before the custom action call for weather or price check it should do action utter_ask_city. if slot is filled with city name it should do the action requested. How can I handle this situation?

Can i call another custom action from a custom action?
or can have a checkpoint that checks if the slot is filled?

**Content of domain file** (if used & relevant):
```
slots:
    fuel:
        type: text
    city:
        type: text

    
intents:
    - greet
    - confirm
    - deny
    - goodbye
    - price_check
    - thankyou
    - restaurant_search
    - video_search
    - weather_check

entities:
    - fuel
    - city

templates:
    utter_greet:
        - 'Hello! How can I help?'
        - 'Hi! How can I help?'
        - 'Welcome, how may I assist you?'
    utter_goodbye:
        - 'Talk to you later.'
        - 'Bye bye'
    utter_thankyou:
        - 'Cool!!'
        - 'You are welcome!'
        - 'Its my pleasure'
    utter_deny:
        - 'Sorry!!'
    utter_affirm:
        - 'Ok'
        - 'Yes'
    utter_default:
        - 'I am not very sure what you said.'
        - "Maybe I didn't understand you properly. Could you please reword your question or type your complete query?"
        - "I didn't get what you said. Can you please rephrase the query?"
        - "A little lost. Apologies. Could you rephrase?"
        - "I've dropped the ball. Could you rephrase?"
        - "Oops. Signal fuzzy. Could you rephrase?"
        - "That request lies outside my powers, although I'm always learning. I can tell you about the fuel prices, suggest good restarants, updates on weather updates, and answer questions. And I'm always learning."
    
actions:
    - utter_greet
    - utter_goodbye
    - utter_thankyou
    - utter_deny
    - utter_default
    - utter_affirm
    - actions.AllSlotsReset
    - actions.ActionPriceCheck
    - actions.ActionAskCity
    - actions.ActionAskFuel
    - actions.ActionRestaurantSearch
    - actions.ActionVideoSearch
    - actions.ActionWeatherCheck
```
