### ISSUE TITLE
When Button is pressed want to display a message related to that button?

### ISSUE THREAD

**Issue by tushar1328** [RasaHQ/rasa_nlu#2243]
### Can we set condition in action on press of button? Please help in forming action.py 

**Python version**: 3.5
**Operating system** : Ubuntu 16.04 LTS

**Issue**:

**Content of domain file** (if used & relevant):

**domain.yml**
```
slots:
  device:
    type: text


intents:
 - greet
 - goodbye
 - question
 - answer


entities:
 - location

templates:
  utter_greet:
  - text: "Hey! How are you?"
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_select_device:
  - text: "Addhar Card can be linked in many ways how would you like to?"
  utter_select_mobile:
  - text: "Open Axis App"
  - text: "Login to Your Account"
  utter_ask_for_method:
  - text: "Here are the following:"
    buttons:
    - title: "Mobile"
      payload: "Mobile"
    - title: "Online"
      payload: "Online"
actions:
 - utter_greet
 - utter_goodbye
 - utter_select_device
 - utter_ask_for_method
 - utter_select_mobile
 - actions.Actiondevice

```
**Stories.md**
```
## Generated Story 00006
* greet
    - utter_greet
* question
    - utter_select_device
    - utter_ask_for_method
* question[location=Mobile]
	- slot{"location": "Mobile"}
	- check_mobile
	- utter_select_mobile
* goodbye
	- utter_goodbye
	- export
```

## Please help me with coding the same and action.py
