### ISSUE TITLE
How to use the same processing pipeline component for multiple slots

### ISSUE THREAD

**Issue by ikhatri** [RasaHQ/rasa_nlu#2246]
**Rasa Core version**:
0.9.6

**Python version**: 
3.6.5

**Operating system** (windows, osx, ...):
Windows 10 x64

**Issue**:
Essentially I'm trying to use the same component `ner_duckling` in this case, to extract data for multiple slots. For example, I have intents for setting alarms and setting reminders. But both of these require a date/time entity to be extracted. I am using FormActions for both actions (so time is a required slot) however if a user sets an alarm and then tries to set a reminder without filling the time, the Form Action will execute and use the time slot from the previous alarm intent. Is there any way for one to use the components to extract entities and then assign them to a slot of my choosing?

For example. Extract the time entity from an intent, and then manually tell Rasa which slot this goes to (because the default behavior of the entity & slot name just matching isn't able to handle this scenario as far as I'm aware).

**Content of domain file** (if used & relevant):
```yaml
# This file is most definitely not set up correctly to do what I've mentioned above
# Any suggestions would be appreciated
slots:
  PERSON:
    type: text
  time:
    type: text

entities:
  - time
  - reminderText

intents:
  - greet
  - welcome
  - provide_name
  - set_alarm
  - reminder

actions:
  - utter_welcome
  - utter_greet
  - utter_alarmtime
  - actions.SetAlarm
  - actions.GetAlarm
  - actions.SetReminder
```

**Processing Pipeline**
```yaml
language: "en"

pipeline:
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_spacy"
- name: "ner_duckling"
  dimensions: ["time", "number"]
```
