### ISSUE TITLE
Problem with intent repeats and not predict right next action

### ISSUE THREAD

**Issue by reza-ebrahimi** [RasaHQ/rasa_nlu#2260]
**Rasa Core version**: master branch

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Environment**: https://github.com/reza-ebrahimi/rasa_venv

**Issue**:
intents repeats with jumping over them and executing their actions continuously without waiting for user response. it is also doesn't predict right next intent.

**Content of domain file** (if used & relevant):
```yaml
language: "en"
pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"
    intent_tokenization_flag: true
    intent_split_symbol: "_"
```

The example conversation:
```console
User: hi
Bot: how can I help you?
Bot: which cuisine do you need?
Bot: where?
Bot: OK, can I start to search?
```

```console
Bot loaded. Type a message and press enter: 
hi
how can I help you?
pizza
I'm on it
what kind of cuisine would you like?
pizza
I'm on it
where?
3
I'm on it
I'm on it
what kind of cuisine would you like?
I'm on it
I'm on it
I'm on it
I'm on it
I'm on it
I'm on it
I'm on it
I'm on it
I'm on it
I'm on it
2018-06-26 14:06:03 WARNING  rasa_core.processor  - Circuit breaker tripped. Stopped predicting more actions for sender 'default'
```
