### ISSUE TITLE
Multiple followup questions for each query

### ISSUE THREAD

**Issue by sumit6192** [RasaHQ/rasa_nlu#2262]
**Rasa Core version**: 0.9.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows 10

**Issue**:

Multiple followup questions for each question.

i have 2 questions : 
1) what is my dpo this year?
2) what is my dpo for advertising?

i can use the 2nd question as followup question to 1st question using affirm_yes and affirm_no intent.
but how would i make more than 1 followup questions . for example if i want to give the user an option for the followup questions : 
a)"Would you like to know for advertising?"
b) "Would you like to know for Packaging?"

so the user have the option to either select any of the followup question which will trigger a custom action written for the followup question.

**Content of domain file** (if used & relevant):
```yaml
intents:
    - greet
    - affirm_yes
    - affirm_no
    - dpo

entities:
    - year
    - vendor

slots:
    year:
        type: text
    vendor:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_askdpo:
        - 'May i know for which year u need the DPO ?'
    utter_follow:
        - "Would you like to know for advertising?"
    utter_respond:
        - "Bye Bye!!"

actions:
    - utter_greet
    - utter_askdpo
    - utter_follow
    - utter_respond
    - actions.AskDpo  
    - actions.Vendors
```
