### ISSUE TITLE
Working with Stories and Entities (Rasa Core not giving correct response)

### ISSUE THREAD

**Issue by bobyongwork** [RasaHQ/rasa_nlu#2276]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I'm still new to Rasa and I've been trying to get Rasa Core to work properly. I've set up and trained the NLU side of things and it works well. But when it comes to training and using Core, I can't seem to get accurate responses.

I'm training using the default parameters, just specifying my own paths
```
python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --verbose
python -m rasa_core.server -d models/dialogue -u models/default/model_20180702-160100/ -o out.log --debug
```

And I'm using this set of questions to test out the responses given by Rasa Core:
> Q: I can't upload file (Correct Answer)
> Q: I can't upload a video file (Correct Answer)
> Q: I can't upload a music file (Wrong Answer - Gives Video Reply)
> Q: I can't upload a mp3 file (Wrong Answer - Gives Video Reply)
> Q: I can't upload a mp4 file (Correct Answer)

It seems I'm doing something wrong as once I ask a question on "video", the next few questions will just give the response for video despite them being related to an "audio" file instead. And looking at the _parse_ results, the NLU is able to detect the intent and entities correctly, so I'm not sure what I'm doing wrong.

**Result of POST request:**
![Image](https://i.imgur.com/pMN9MKE.png)

**Content of domain file**:
```yaml
slots:
  typeOfFile:
    type: text
    
intents:
  - greeting
  - uploadProblem

entities:
  - typeOfFile
  
templates:
  utter_greeting:
    - "Hello, how may I help you today?"
  utter_uploadProblem:
    - "Which file are you trying to upload?"
  utter_uploadProblem-Music:
    - "For audio files, we only allow mp3 and flac"
  utter_uploadProblem-Video:
    - "For video issues, please make sure your file is in mp4 or mkv"

actions:
  - utter_greeting
  - utter_uploadProblem
  - utter_uploadProblem-Music
  - utter_uploadProblem-Video
```

**Content of story file**:
```yaml
## story 1
* greeting
    - utter_greeting

## story 2
* uploadProblem
    - utter_uploadProblem

## story 3
* uploadProblem{"typeOfFile": "music"}
    - utter_uploadProblem-Music

## story 4
* uploadProblem{"typeOfFile": "video"}
    - utter_uploadProblem-Video
```

**Content of data file**:
```json
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "Hi",
        "intent": "greeting",
        "entities": []
      },
      {
        "text": "Hello",
        "intent": "greeting",
        "entities": []
      },
      {
        "text": "Good day",
        "intent": "greeting",
        "entities": []
      },
      {
        "text": "I can't upload my mp3 file today",
        "intent": "uploadProblem",
        "entities": [
          {
            "start": 18,
            "end": 21,
            "value": "music",
            "entity": "typeOfFile"
          }
        ]
      },
      {
        "text": "I am unable to put up my music album on the website",
        "intent": "uploadProblem",
        "entities": [
          {
            "start": 25,
            "end": 30,
            "value": "music",
            "entity": "typeOfFile"
          }
        ]
      },
      {
        "text": "Why can't I submit my video to the app?",
        "intent": "uploadProblem",
        "entities": [
          {
            "start": 22,
            "end": 27,
            "value": "video",
            "entity": "typeOfFile"
          }
        ]
      },
      {
        "text": "Are mp4 supported as an upload format on the website?",
        "intent": "uploadProblem",
        "entities": [
          {
            "start": 4,
            "end": 7,
            "value": "video",
            "entity": "typeOfFile"
          }
        ]
      },
      {
        "text": "I can't upload my file to your website",
        "intent": "uploadProblem",
        "entities": []
      }
    ]
  }
}
```
