### ISSUE TITLE
how to get what user's text entered and show the entered text

### ISSUE THREAD

**Issue by Primtek** [RasaHQ/rasa_nlu#2281]
**Rasa Core version**:
0.9.0
**Python version**: 
2.7.5
**Operating system** (windows, osx, ...):
centOS 7

**Issue**:
Hello,
I am new with rasa core.. I am in the progress to create my 1st bot, with the following scenario:
when users say hey.. 
the bot will ask user's name
after user entered his name
the bot will show .. hey.. your name is .... (my case is utter_greet2)

my question is .. how to save user's entered text and show it to user like the scenario above?

please help

thanks a lot in advance

Regards
Win

**Content of domain file** (if used & relevant):
```yaml
domain.yml
intents:
  - greet
  - goodbye


templates:
  utter_greet1:
    - "Hey, I am bot, what is your name?"
  utter_greet2:
    - "Hey, your name is "

actions:
  - utter_greet1
  - utter_greet2
  - utter_goodbye

[root@ai nluEZ]# vi config.yml
language: "en"
pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

data/nlu_data.md
## intent: greet
- Hi
- hey

## intent: goodbye
- Bye
- Goodbye

data/stories.md
* greet1
    - utter_greet1
* greet2
    - utter_greet2
* thanks+goodbye
        - utter_thanks
        - utter_goodbye
```
