### ISSUE TITLE
Getting wrong actions predictions even after adding a lot of stories.

### ISSUE THREAD

**Issue by devansh1497** [RasaHQ/rasa_nlu#2288]
**Rasa Core version**:0.8.0

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):OSX

**Issue**:So, I have a couple of slots where in I am storing **priorities - (low, medium and high)**, name of the project and type of the **issue('bugs', 'stories')**. I **cannot use categorical slot** because the user can choose **more than 1 type of the same value**...So he can choose both 'low' and 'medium' as the priorities.. Now ideally, I needed to extract the priorities as a list but since atm rasa doesn't append the slot values to a list, I have used 3 different slots for these priorities. Now what I want is that all the priorities that the user has talked about in his message should be used to retrieve information. However, if the user has not talked about any priorities in his current message, then I would like to use his previous priority preferences(using slots). What I did was I created actions to set and reset these priority slots and I tried to train the model so that it learns which slots to set and which slots to reset depending upon what slots have currently been extracted from the users message. But its still now working.
I think its not working because the action flow is controlled by slots...Now if there is a case where my 'medium' and 'high' slots are set due to users previous message and then the user asks for low priority...In this case, ideally my medium and high priority slots should be re-set since the user doesn't want them in the query...But if I don't have the exact flow of slots, then it wouldn't work...so suppose, in my training stories, if I had an example where only low slot was set and then i trained it for the above query...so this story would be different than the user's message because of the previous set slots...Am i right or am I missing something?If I am right, then there would be 100+ combinations for such a small part of the bot that I am building...Then is it even possible to cover all these possibilities?

**Content of domain file** (if used & relevant):
```yaml

slots:
  all_issues:
    type: bool
    initial_value: False
  bugs:
    type: bool
    initial_value: False
  stories:
    type: bool
    initial_value: False
  project_name:
    type: text
  med_pri:
    type: bool
  low_pri: 
    type: text
  high_pri:
    type: text
  
intents:
 - greet
 - goodbye
 - inform
 - anything_else

entities:
 - all_issues
 - bugs
 - stories
 - project_name
 - low_pri
 - med_pri
 - high_pri

templates:
  utter_greet:
    - 'Hello!How can I help?'
    - 'Hi!'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye!'
  utter_anything_else:
    - "Can I help you with anything else?"
    - "Anything else?"
    - "Do you need anything else?"
    
  utter_ask_project_name:
    - "Which project?"

actions:
 - utter_greet
 - utter_goodbye
 - utter_anything_else
 - utter_ask_project_name
 - actions.ActionSetIssuesSlot 
 - actions.ActionSetBugsSlot 
 - actions.ActionSetStoriesSlot 
 - actions.ActionSetBugsStoriesSlot 
 - actions.ActionResetIssuesSlot 
 - actions.ActionResetBugsSlot 
 - actions.ActionResetStoriesSlot 
 - actions.ActionResetBugsStoriesSlot
 - actions.ActionResetStoriesIssuesSlot
 - actions.ActionResetBugsIssuesSlot
 - actions.ActionSetLowSlot 
 - actions.ActionSetMediumSlot 
 - actions.ActionSetHighSlot 
 - actions.ActionSetLowMedSlot 
 - actions.ActionSetMedHighSlot 
 - actions.ActionReSetLowSlot 
 - actions.ActionReSetMediumSlot 
 - actions.ActionReSetHighSlot 
 - actions.ActionReSetLowMediumSlot 
 - actions.ActionReSetMediumHighSlot 
 - actions.ActionReSetLowHighSlot 
 - actions.ActionIssue 


```
**Content of stories file** (if used & relevant):
* inform{"project_name": "fae"}
    - slot{"project_name": "fae"}
    - action_issue
* inform{"project_name": "tpo"}
    - slot{"project_name": "tpo"}
    - action_issue
* inform{"bugs": "bugs", "project_name": "fae"}
    - slot{"bugs": "bugs"}
    - slot{"project_name": "fae"}
    - action_reset_stories_issues
    - slot{"stories": null}
    - slot{"all_issues": null}
    - action_issue
* inform{"stories": "stories", "project_name": "tpo"}
    - slot{"stories": "stories"}
    - slot{"project_name": "tpo"}
    - action_reset_bugs_issues
    - slot{"bugs": null}
    - slot{"all_issues": null}
    - action_issue
* inform{"all_issues": "issues", "project_name": "fae"}
    - slot{"all_issues": "issues"}
    - slot{"project_name": "fae"}
    - action_issue
* inform{"bugs": "bugs", "stories": "stories", "project_name": "fae"}
    - slot{"bugs": "bugs"}
    - slot{"stories": "stories"}
    - slot{"project_name": "fae"}
    - action_reset_issues
    - slot{"all_issues": "all issues"}
    - action_issue
    - export

## Generated Story -4993798069511925315
* inform{"bugs": "bugs", "stories": "stories", "project_name": "fae"}
    - slot{"bugs": "bugs"}
    - slot{"stories": "stories"}
    - slot{"project_name": "fae"}
    - action_issue
* inform{"low_pri": "low"}
    - slot{"low_pri": "low"}
    - action_issue
* inform{"med_pri": "med"}
    - slot{"med_pri": "med"}
    - action_issue
* inform{"high_pri": "high"}
    - slot{"high_pri": "high"}
    - action_issue
    - export

## Generated Story -2794009131783263642
* inform{"bugs": "bugs", "project_name": "fae", "low_pri": "low"}
    - slot{"bugs": "bugs"}
    - slot{"project_name": "fae"}
    - slot{"low_pri": "low"}
    - action_reset_stories_issues
    - slot{"stories": null}
    - slot{"all_issues": null}
    - action_reset_medium_high
    - slot{"med_pri": null}
    - slot{"high_pri": null}
    - action_issue
* inform{"bugs": "bugs", "med_pri": "medium", "project_name": "tpo"}
    - slot{"bugs": "bugs"}
    - slot{"med_pri": "medium"}
    - slot{"project_name": "tpo"}
    - action_reset_stories_issues
    - slot{"stories": null}
    - slot{"all_issues": null}
    - slot{"high_pri": null}
    - action_reset_low_high
    - slot{"low_pri": null}
    - slot{"high_pri": null}
    - action_issue
```
Consider this story that I have in my stories.md
```
## Generated Story 9065223767094896892
* inform{"low_pri": "low", "stories": "stories", "project_name": "fae"}
    - slot{"low_pri": "low"}
    - slot{"stories": "stories"}
    - slot{"project_name": "fae"}
    - action_reset_bugs_issues
    - slot{"bugs": null}
    - slot{"all_issues": null}
    - action_reset_medium_high
    - slot{"med_pri": null}
    - slot{"high_pri": null}
    - action_issue
```
Now, even though I am typing the exact sentence as the above query, I am getting the correct entity extraction but wrong action prediction.This is the result

<img width="1056" alt="screen shot 2018-07-03 at 23 50 43" src="https://user-images.githubusercontent.com/29357469/42237827-96511866-7f1c-11e8-921c-2bdae55d72f0.png">
