### ISSUE TITLE
ActionForm not working as expected!

### ISSUE THREAD

**Issue by Primtek** [RasaHQ/rasa_nlu#2289]
**Rasa Core version**:
0.9.7
**Python version**: 
2.7.5
**Operating system** (windows, osx, ...):
centOS 7
**Issue**:
Why it does not go to next question (keep asking the 1st question (claim_report))?
like this:

Bot loaded. Type a message and press enter:
user: hey
Bot: Hey, I m bot
user: accident
Bot: To claim, I will ask you some questions
Bot: What is your vehicle plate number?
B123
Bot: What is your vehicle plate number?
B123
Bot: What is your vehicle plate number?
B123

**Content of domain file** (if used & relevant):
```yaml
=== domain.yml === 
[root@ai nluEZ]# vi domain.yml
slots:
  claim_report_nopol:
    type: text
  claim_report_dol:
    type: text
  claim_report_chronology:
    type: text
  claim_report_data_confirmed:
    type: bool
  requested_slot:
    type: unfeaturized
  matches:
    type: unfeaturized


intents:
  - greet
  - goodbye
  - thanks
  - thanks+goodbye
  - claim_report
  - claim_status
  - authorised_workshop
  - deny
  - claim_report_nopol
  - claim_report_dol
  - claim_report_chronology

entities:
  - claim_report_nopol
  - claim_report_dol
  - claim_report_chronology

templates:
  utter_greet:
    - text: "Hey, I m bot"
  utter_goodbye:
    - text: "Bye!"
  utter_claim_report:
    - text: "To claim, I will ask you some questions"
  utter_ask_claim_report_nopol:
    - text: "What is your vehicle plate number?"
  utter_ask_claim_report_dol:
    - text: "Date of loss?"
  utter_ask_claim_report_chronology:
    - text: "Chronology?"
  utter_claim_report_data_summary:
    - text: "Please confirm"
      buttons:
        - title: "Yes"
          payload: "True"
        - title: "No"
          payload: "False"
```
=== config.yml  ===
pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

=== stories.md ===
## find_claim_report
* greet
    - utter_greet
* claim_report
   -  utter_claim_report
    - action_claim_report_form
    - slot{"requested_slot": "claim_report_nopol"}
* inform{"action_claim_report_nopol":"claim_report_nopol"}
    - action_claim_report_form
    - slot{"claim_report_nopol":"B123"}
    - slot{"requested_slot":"cliam_report_dol"}
* inform{"action_claim_report_dol":"claim_report_dol"}
    - action_claim_report_form
    - slot{"claim_report_dol":"21-12-2000"}
    - slot{"requested_slot":"claim_report_chronology"}
* inform{"action_claim_report_chronology":"claim_report_chrnology"}
    - action_claim_report_form
    - slot{"claim_report_chronology":"blah blah blah"}
* thanks+goodbye
    - utter_thanks
    - utter_goodbye

==== actions.py ====

class PrimtekAPI(object):
    def search(self, info):
        return "hello world from primtek"

class Claim_Report_Form(FormAction):
    RANDOMIZE = False
    @staticmethod
    def required_fields():
       return [
           EntityFormField("claim_report_nopol", "claim_report_nopol"),
           EntityFormField("claim_report_dol", "claim_report_dol"),
           EntityFormField("claim_report_chronology", "claim_report_chronology")
       ]
    def name(self):
       return 'action_claim_report_form'

    def submit(self, dispatcher, tracker, domain):
       results = PrimtekAPI().search(
            tracker.get_slot("claim_report_nopol"),
            tracker.get_slot("claim_report_dol"),
            tracker.get_slot("claim_report_chronology"))
       return []
