### ISSUE TITLE
dialogue model can't handle more than 3 steps

### ISSUE THREAD

**Issue by nahidalam** [RasaHQ/rasa_nlu#2330]
**Rasa Core version**: 0.9.0a6

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSx

**Issue**:
My bot needs to go through 5 stages of communication [nothing to remember at this point]. When I test my bot, it only works till stage 3. For stage 4, it doesn't generate any response. Any suggestion?

Screenshot (https://imgur.com/a/XnPtZ2E) of the bot in action. See how it is not replying anything after I typed the last sentence 

**Content of domain file** (if used & relevant):
```
intents:
 - start_process
 - offer_services
 - generate_proposal
 - submit_for_approval
 - negotiate


templates:
  utter_recommend:
    - 'Great, Let me discover customer priority. Based on our analysis, Apple IT is looking for below services. 1)automatic network perforamence optimization, 2)realtime predictive modeling of network outage, 3)realtime security threat detection and prevention. Do you want to offer those services in the renewed contract?'
  utter_calculate_price:
    - 'Sure, based on the non discounting pricing, we can offer a 2 year service renewal for 2MM USD. Do you want to generate a proposal?'
  utter_generate_proposal:
    - 'Thanks, please see the proposal attached. Do you want to submit the proposal for approval?'
  utter_submit_for_approval:
    - 'Okay, the proposal is submitted to xyz@cisco.com for review'
  utter_negotiate:
    - "Your proposal is approved by xyz@cisco.com. Your Apple IT contact person for the service renewal is Tom Jones. Do you want to reach out for negotiation?"


actions:
 - utter_recommend
 - utter_calculate_price
 - utter_generate_proposal
 - utter_submit_for_approval
 - utter_negotiate

```
