### ISSUE TITLE
Buttons with Payloads / Titles containing "Yes" or "No" get transformed incorrectly 

### ISSUE THREAD

**Issue by m90** [RasaHQ/rasa_nlu#2344]
**Rasa Core version**: 0.10.1

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:

After upgrading from 0.9 to 0.10.1 I noticed the following phenomenon when running my unit tests: a button utterance defined like this:

```yml
  utter_buttons:
  - text: "Buttons, there will be buttons:"
    buttons:
      - title: "Yes"
        payload: "Yes"
      - title: "No"
        payload: "No"
```

Will be serialized like this when using a `CollectingOutputChannel`:

```json
{
    "messages": [
        {
            "data": [
                {
                    "payload": true,
                    "title": true
                },
                {
                    "payload": false,
                    "title": false
                }
            ],
            "recipient_id": "xxx",
            "text": "Buttons, there will be buttons:"
        }
    ]
}
```

when using 0.9 would do the expected:

```json
{
    "messages": [
        {
            "data": [
                {
                    "payload": "Yes",
                    "title": "Yes"
                },
                {
                    "payload": "No",
                    "title": "No"
                }
            ],
            "recipient_id": "xxx",
            "text": "Buttons, there will be buttons:"
        }
    ]
}
```

Any string that is not **"Yes"** or **"No"** will still work as expected in 0.10.1
