### ISSUE TITLE
Slot will not be filled - every time None

### ISSUE THREAD

**Issue by mrRobot62** [RasaHQ/rasa_nlu#2348]
**Rasa Core version**:
$ >pip list | grep rasa
rasa-core                     0.9.8      
rasa-nlu                      0.12.3  

**Python version**: 
3.6.6

**Operating system** (windows, osx, ...):
mac os 
Darwin MacBook-Pro-4.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
**Issue**:

**Content of domain file** (if used & relevant):
```
intents:
- greet
- goodbye
- user_need_help
- inform

entities:
- user_need_help
- username

actions:
- utter_user_authorization
- utter_greet
- utter_goodbye
- coco.ActionHelp
- utter_greet_user

templates:
    utter_user_authorization:
        - "I have to authorize you. Please enter your first name"

    utter_greet:
        - "Nice to meet you. What can I do for you?"

    utter_goodbye:
        - "Hope, I could help you. Good bye"

    utter_greet_user:
        - "Hi {username}"
slots:
    username:
        type: text
```

as an example from data.json
...
      {
        "text": "my name is peter",
        "intent": "inform",
        "entities": [
          {
            "start": 11,
            "end": 16,
            "value": "peter",
            "entity": "username"
          }
        ]
      },
      {
        "text": "here is frank",
        "intent": "inform",
        "entities": [
          {
            "start": 8,
            "end": 13,
            "value": "frank",
            "entity": "username"
          }
        ]
      },
      {
        "text": "here is marie-luise",
        "intent": "inform",
        "entities": [
          {
            "start": 8,
            "end": 19,
            "value": "marie-luise",
            "entity": "username"
          }
        ]
      },
...

## Story 01a
* greet
    - utter_greet
    - utter_user_authorization
* inform
    - utter_greet_user
* goodbye
    - utter_goodbye

# story 02
* goodbye
  - utter_goodbye

** Problem: **

I trained NLU and rasa_core-dialog - no error messages
Than I started training_online

Example (during online training)
user: hi
Bot: utter_greet (ok)
Bot: utter_user_authorization (ok) => action_listen (ok)
user: my name is bernd
bot:
	user said:	my name is bernd

		 whose intent is:	inform

we currently have slots: username: None

------
The bot wants to [utter_greet_user] due to the intent. Is this correct?

Itent : OK
Action: ok
Seems entity will not be recognized
and is username not filled?
Entity (see above) is "username"

I believe it's a rookie error - but I worked a couple of hours on it :-( - hope somebody give me a kick :-)

Cheers
