### ISSUE TITLE
TypeError when running train_online.py file

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_nlu#2360]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX

**Issue**: When I try to run online training on my dialogue model, I get the following error:

```
Traceback (most recent call last):
  File "core_model.py", line 65, in <module>
    run()
  File "core_model.py", line 42, in run
    agent = Agent.load('models/dialogue', interpreter = interpreter)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/agent.py", line 75, in load
    action_factory)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/domain.py", line 421, in load
    **additional_arguments
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/domain.py", line 493, in __init__
    action_factory, action_classes, action_names, templates)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/domain.py", line 502, in instantiate_actions
    ensure_action_name_uniqueness(actions)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa_core/actions/factories.py", line 30, in ensure_action_name_uniqueness
    if a.name() in actual_action_names:
TypeError: unhashable type: 'list'
```
I've tried using pdb and I think the error occurs at agent instantiation but I can't seem to figure out what exactly is causing this error. Any help is greatly appreciated!

`train_online.py:`

```
# online training of dialogue model
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter

logger = logging.getLogger(__name__)


def run_bedtimebot_online(input_channel, interpreter,
                          domain_file="domain.yml",
                          training_data_file='data/stories.md'):
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history = 3), KerasPolicy()],
                  interpreter=interpreter)

    training_data = agent.load_data(training_data_file)
    agent.train_online(training_data,
                       input_channel=input_channel,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)

    return agent


if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")
    nlu_interpreter = RasaNLUInterpreter('./models/current/nlu/default/bedtime_nlu')
    run_bedtimebot_online(ConsoleInputChannel(), nlu_interpreter)

```

**Content of domain file** (if used & relevant):
```yaml
---
slots:
  PERSON:
    type: text
    initial_value: "human"
  avg_bedtime:
    type: text
  goal_bedtime:
    type: text
  timezone:
    type: text

  early_option:
    type: text
  late_option:
    type: text
  prev_early_option:
    type: text
  prev_late_option:
    type: text

  successful_weeks:
    min_value: 0
    type: float
    initial_value: 0
  total_weeks:
    min_value: 0
    type: float
    initial_value: 0

  user_freq:
    max_value: 6
    min_value: 0
    type: float
    initial_value: 0
  weekly_goal_freq:
    max_value: 6
    min_value: 1
    type: float

  weekly_goal_freq_less:
    max_value: 6
    min_value: 1
    type: float
    initial_value: 2
  weekly_goal_freq_more:
    max_value: 6
    min_value: 1
    type: float
    initial_value: 3

  weekly_goal_choice:
    type: text
  weekly_goal:
    type: text

  late_reasons:
    type: text
  requested_slot:
    type: unfeaturized

entities:
- PERSON
- avg_bedtime
- goal_bedtime
- timezone
- user_freq
- weekly_goal_choice
- late_reasons
- requested_slot

intents:
- bedtime_attempt
- greet
- affirm
- deny
- inform

templates:
  utter_greet_afternoon:
    - "Good afternoon, {PERSON}!"
    - "Bonjour, {PERSON}!"
    - "Hey, {PERSON}! I hope your day is off to a fantastic start!"

# setup utterances
  utter_greet_introduction:
    - "Hi, it's Emile! Sleep serves to reenergize the body's cells, clear waste from the brain, and support learning and memory. I'm here to help you get better, more consistent sleep as well as answer any questions you might have about sleep science!"
  utter_ask_PERSON:
    - "First things first: what is your name?"
  utter_ack_PERSON:
    - "Well, {PERSON}, it's very nice to meet you!"
  utter_ask_goal_bedtime:
    - "What time would you ideally get to bed on weekdays?"
  utter_ack_general:
    - "Noted."
    - "Gotcha! I'll make note of that."
  utter_ask_avg_bedtime:
    - "On average, what time have you been getting to bed these last few weeks?"
  utter_last_question:
    - "Last question!"
  utter_ask_timezone:
    - "What's your time zone?"

# setting first weekly_goal
  utter_make_first_weekly_goal:
    - "Awesome! Remember, if your first week's goal seems too easy- that's on purpose.
     Think of it as the bare minimum toward building momentum for harder goals ahead.
     That said, you've got options for the coming week:
     A. In bed by {late_option} {weekly_goal_freq_more} times.
     B. In bed by {early_option} {weekly_goal_freq_less} times."
  utter_ask_first_weekly_goal:
    - text: "A or B?"
      buttons:
      - title: "A"
        payload: "A"
      - title: "B"
        payload: "B"
  utter_ack_first_weekly_goal:
    - "Perfect! I'll send reminders + check-ins starting tonight. If you hit your first goal, next week will be harder and so on until you're at your ideal schedule!"

# reminder utterances
  utter_reminder:
    - "Remember, bedtime tonight is {weekly_goal}."
    - "Don't forget: bedtime tonight is {weekly_goal}!"
  utter_edit_reminder:
    - "Btw if this bedtime reminder feels too late/early you can text 'edit reminder' to adjust it or add another one (default is one reminder ~1 hr before bedtime)."
  utter_ask_on_time:
    - "Did you get to bed by {weekly_goal} last night?"
    - "Were you able to get to bed by {weekly_goal} last night?"
    - "Did you get it last night, by any chance?"

# questions asking for late_reasons
  utter_ask_late_reasons_first:
    - "No worries! In one word (or a few if you must), what was the main reason for missing your bedtime last night?"
  utter_ask_late_reasons:
    - "No worries! Pick or add a reason:
       A. In bed but couldn't fall asleep
       B. It's a secret!"
# C. {late_reasons}
  utter_ack_late_reasons_first:
    - "Once the reasons surface you will feel more empowered to break habits that keep you from your sleep.
       Got it! I'll ask this from time to time and keep a tally to help identify what gets in the way.
       It might look something like this:
       Here are the top reasons you missed your bedtime/waketime this month:

       Netflix (4)
       Facebook (3)
       Out with Friends (3)"

# motivational/reward utterances
  utter_ack_success:
    - "Nicely done! Keep at it, {PERSON}!"
    - "Great job! Keep it up, {PERSON}!"
  utter_ack_almost_achieve_goal:
    - "Excellent! Get it again tonight and you'll hit your goal for the week!"
    - "Well done! Get it again tonight and you'll hit your goal for the week!"
  # PROBABLY NEED TO MAKE THIS A CUSTOM ACTION:
  # utter_motivate:
  #   - "Back on track! {user_freq} down, ({weekly_goal_freq} - {user_freq}) to go!"
  utter_ack_achieve_weekly_goal:
    - "Aand just like that you've achieved your goal!"
  utter_ack_surpass_weekly_goal:
    - "Way to go! You officially finished the week in Bonusland! I'll reach out on Sunday with a slightly harder goal for the coming week. Take care til then!"
  utter_reward:
    - "Props again on exceeding last week's goal!"

# attempted early bedtime utterances
  utter_ack_attempt:
    - "That's alright! As long as you stay accountable to a weekly goal, you're bound to improve. These check-ins and reminders are designed to bring intentionality to your bedtime, so prioritizing your sleep should get easier every week! Since you made the effort to get to bed, I'd say it counts. What do you think, shall we count it?"
  utter_ack_attempt_deny:
    - "Gotcha! I won't count it then. Back at it tonight!"

# setting weekly_goal / start-of-week utterances
  utter_greet_sunday:
    - "Happy Sunday, Emile here!"
    - "Hey, it's Emile! I hope you had a restful weekend :)"
  utter_make_weekly_goal:
    - "Here are your options for the upcoming week:
      A. In bed by {weekly_goal_late_option} {weekly_goal_freq_more} times.
      B. In bed by {weekly_goal_early_option} {weekly_goal_freq_less} times.
      C. Customize or skip this week."
  utter_ask_weekly_goal:
    - text: "A, B, or C?"
      buttons:
      - title: "A"
        payload: "A"
      - title: "B"
        payload: "B"
#      - title: "C"
#        payload : "C"
  utter_ack_weekly_goalAB:
    - "Excellent choice! Goals with {weekly_goal_freq_less} or more days are great for building consistent habits. Good luck, I'll be rooting for ya!"
    - "Sounds good! Good luck and I'll talk to you soon!"
    - "Noted. Good luck, you've got this in the bag!"
#  utter_ask_weekly_goalC:
#    - "What time would you like to get to bed by this week?"
  utter_ask_weekly_goal_freq:
    - "How many times would you like to get to bed by {weekly_goal} this week?"

# extension / end-of-week utterances
#  utter_ask_extend:
#    - "Wanna extend check-ins through the weekend or start fresh next week?"
#  utter_ack_extend:
#    - "Sounds good! Talk to you tomorrow!"
  utter_end_of_week:
    - "You've finished the week {user_freq} for {weekly_goal_freq} on your goal."

actions:
- utter_greet_afternoon

# setup utterances
- utter_greet_introduction
- utter_ask_PERSON
- utter_ack_PERSON
- utter_ask_goal_bedtime
- utter_ack_general
- utter_ask_avg_bedtime
- utter_last_question
- utter_ask_timezone

# setting first weekly_goal
- utter_make_first_weekly_goal
- utter_ask_first_weekly_goal
- utter_ack_first_weekly_goal

# reminder utterances
- utter_reminder
- utter_edit_reminder
- utter_ask_on_time

# questions asking for late_reasons
- utter_ask_late_reasons_first
- utter_ask_late_reasons
- utter_ack_late_reasons_first

# motivational/reward utterances
- utter_ack_almost_achieve_goal
# - utter_motivate
- utter_ack_achieve_weekly_goal
- utter_ack_surpass_weekly_goal
- utter_reward

# attempted early bedtime utterances
- utter_ack_attempt
- utter_ack_attempt_deny

# setting weekly_goal / start-of-week utterances
- utter_greet_sunday
- utter_make_weekly_goal
- utter_ask_weekly_goal
- utter_ack_weekly_goalAB
#- utter_ask_weekly_goalC
- utter_ask_weekly_goal_freq

# extension / end-of-week utterances
#- utter_ask_extend
#- utter_ack_extend
- utter_end_of_week

- actions.ActionSetup
- actions.ActionSetWeeklyGoalOptions
- actions.ActionAskWeeklyGoal
- actions.ActionSetWeeklyGoal
- actions.ActionTriggerBedtimeReminder
- actions.ActionBedtimeReminder
- actions.ActionTriggerDailyCheckIn
- actions.ActionDailyCheckIn
- actions.ActionUpdateLateReasons
- actions.ActionUpdate
- actions.ActionUpdateOverall

```
