### ISSUE TITLE
Incorrect dialogue order

### ISSUE THREAD

**Issue by nahidalam** [RasaHQ/rasa_nlu#2375]
**Rasa Core version**: 0.9.8

**Python version**:  3.6

**Operating system** (windows, osx, ...): OSx

**Issue**:

I have trained NLU and Dialogue model for a customer service bot. The NLU is working fine but when I run the bot, the conversation order changes. If you look at below `domain` file and `stories.md `file, if I have `offer_services` intent, then it should return the contents of `utter_calculate_price`. But instead it returns the content of `utter_negotiate`. 

Please suggest.

This is how I train the dialogue model:

```
def train_dialogue(domain_file, model_path,training_data_file):

	agent = Agent(domain_file, policies=[AugmentedMemoizationPolicy(max_history=3), KerasPolicy()])

	agent.train(
				training_data_file,
				epochs = 300,
				batch_size = 50,
				validation_split = 0.2)

	agent.persist(model_path)
	return agent
```

**Content of domain file** (if used & relevant):
```
intents:
 - start_process
 - offer_services
 - generate_proposal
 - submit_for_approval
 - negotiate


templates:
  utter_recommend:
    - 'Great, Let me discover customer priority...... Do you want to offer those services in the renewed contract?'
  utter_calculate_price:
    - 'Sure, based on the pricing, we can offer a 2 year contract for 2MM USD. Do you want to generate a proposal?'
  utter_generate_proposal:
    - 'Thanks, please see the proposal attached. Do you want to submit the proposal for approval?'
  utter_submit_for_approval:
    - 'Okay, the proposal is submitted to xyz@abc.com for review'
  utter_negotiate:
    - "Your proposal is approved by xyz@abc.com. Your customer IT contact person for the service is Tom Jones. Do you want to reach out for negotiation?"


actions:
 - utter_recommend
 - utter_calculate_price
 - utter_generate_proposal
 - utter_submit_for_approval
 - utter_negotiate
```

**Content of stories.md file**

```
## story_001
* start_process
   - utter_recommend
* offer_services
   - utter_calculate_price
* generate_proposal
   - utter_generate_proposal
* submit_for_approval
   - utter_submit_for_approval
* negotiate
   - utter_negotiate
```
