### ISSUE TITLE
There is no memorised next action

### ISSUE THREAD

**Issue by elixias** [RasaHQ/rasa_nlu#2377]
**Rasa Core version**:
0.12.3
**Python version**: 
Python 3.6.5
**Operating system** (windows, osx, ...):
Linux 98d9549c495f 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linux

**Issue**:
On certain inputs, the model predicts 'action_listen' with  'no memorised next action'.
```
2018-07-30 03:09:37 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2018-07-30 03:09:37 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_1_KerasPolicy
```

Subsequently, for any other inputs (including previously working inputs), it no longer responds but gives the same 'action_listen' prediction.

**Content of domain file** (if used & relevant):
```yaml
config:
  store_entities_as_slots: true
slots:
  (service_entity):
    type: text
  (action_entity):
    type: text
entities:
- (service_entity)
- (action_entity)
intents:
- How_To_Intent
- General_Intent
- intent_greet
- intent_bye
templates:
  how_to_action:
    - "how to triggered: action={(action_entity)} for service={(service_entity)}"
  general_action:
    - "General enquiry of service={(service_entity)}"
  utter_default:
    - "default message"
  utter_greet:
    - "Hey, how can I help you?"
  utter_bye:
    - "Goodbye"
actions:
  - general_action
  - how_to_action
  - utter_greet
  - utter_bye

```
