### ISSUE TITLE
dispatcher.utter_message("some message") is not printing the message in the consoleoutput 

### ISSUE THREAD

**Issue by Sayanjitdas** [RasaHQ/rasa_nlu#2390]
**Rasa Core version**:0.9.8

**Python version**: 3.6.5

**Operating system** ( osx):

**Issue**:

**Hello.
I am having an issue in Custom Actions 
Below is my domain file**

```yaml
intents:
  - greet
  - goodbye
  - crying

entities:
  - activity_with_cry


templates:
  utter_greet:
    - text : "Hello, choose the problem from below!"
      buttons :
      - title : "Crying"
        payload: "crying"
      - title : "Peeing"
        payload : "peeing"
      - title : "Pooping"
        payload : "pooping"
  utter_goodbye:
    - text : "ok. Hope I have helped you to find the solution you need!

actions:
  - utter_greet
  - utter_goodbye
  - utter_crying
  - core.bot.actionToResponse
```

Below is my action script named bot.py for core.bot.actionToResponse

`
from rasa_core.actions import Action
from rasa_core.events import SlotSet

class actionToResponse(Action):
    def name(self):
        return "action_to_response"

    def run(self,tracker,dispatcher,domain):
        dispatcher.utter_message("This is the message")
        return []
`
below is my stories.md

`
## story_1
* greet
  - utter_greet
* crying
  - action_to_response
* goodbye
  - utter_goodbye

## story_2
* greet
  - utter_greet
* goodbye
  - utter_goodbye

`
**when I am running the model  after training and interacting with the bot there is no output when the bot recognises the custom action(core.bot.actionToResponse).The message I gave in the dispatcher
is not printing in the console.**
