### ISSUE TITLE
All slots in FormAction get filled except timezone

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_nlu#2392]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX

**Issue**:
Everytime I run an online training session, only three out of the four required slots that are defined in my `action_setup` class get filled successfully and I'm not sure why. I always have to explicitly state the following when the bot is doing an `action_listen`: 
`/inform_timezone[timezone=Pacific]` 
even though the utterance utilizes button payloads. 
Is there a way for it to successfully extract the timezone entity if I simply type in `Pacific`? I have already added all possible timezones to the `rasa_nlu_data json` file. 

Here is a snippet of the online training:
```
The bot wants to [action_setup]. Is this correct?

	1.	Yes.
	2.	No, the action is wrong.
	0.	Export current conversations as stories and quit
1
From the following list, select the option that best describes your timezone:
1: Atlantic (Atlantic)
2: Central (Central)
3: East-Saskatchewan (East-Saskatchewan)
4: Eastern (Eastern)
5: Mountain (Mountain)
6: Newfoundland (Newfoundland)
7: Pacific (Pacific)
8: Saskatchewan (Saskatchewan)
9: Yukon (Yukon)
------
Chat history:

	bot did:	action_listen

	user did:	inform_time

	with CARDINAL:	2

	with time:	2018-08-01T02:00:00.000Z

	bot did:	utter_last_question

	bot did:	action_setup

we currently have slots: PERSON: Andrea, avg_bedtime: 2018-08-01T02:00:00.000Z, early_option: None, goal_bedtime: 2018-08-01T23:30:00.000Z, requested_slot: timezone, timezone: None

------
The bot wants to [action_listen]. Is this correct?

	1.	Yes.
	2.	No, the action is wrong.
	0.	Export current conversations as stories and quit
1
Next user input:
Pacific
------
Chat history:

	bot did:	utter_last_question

	bot did:	action_setup

	bot did:	action_listen

	user said:	Pacific

		 whose intent is:	inform_timezone

we currently have slots: PERSON: Andrea, avg_bedtime: 2018-08-01T02:00:00.000Z, goal_bedtime: 2018-08-01T23:30:00.000Z, requested_slot: timezone, timezone: None

```
**Content of domain file** (if used & relevant):
```yaml
---
slots:
  PERSON:
    type: text
  goal_bedtime:
    type: text
  avg_bedtime:
    type: text
  timezone:
    type: text

  requested_slot:
    type: unfeaturized

entities:
- PERSON
- avg_bedtime
- goal_bedtime
- timezone
- requested_slot

intents:
- bedtime_attempt
- greet
- affirm
- deny
- inform_name
- inform_timezone
- inform_time
- inform_choice
- inform_freq
```
