### ISSUE TITLE
Display buttons using rest api

### ISSUE THREAD

**Issue by chinnusujitha** [RasaHQ/rasa_nlu#2412]
**Rasa Core version**: 0.8.3

**Python version**: python 3.6.3

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
I wrote a rest api which is defined in #119 
Now i want to display buttons that are defined in my yaml file using rest api, (OR) is there any way to return the response through rest api in this format:
{
type : "text",
message : "how can i help you"
}
{
type : "buttons",
message : "we are providing options for : ",
options : ["option1", "option2" ]
}

**Content of domain file** (if used & relevant):
```yaml
  utter_greet:
    - text : "Hey! How are you?"
      buttons:
      - title: "great"
        payload: "great"
      - title: "super sad"
        payload: "super sad"
```
