### ISSUE TITLE
Using templates through external endpoint does not pick images from template

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa_nlu#2419]
**Rasa Core version**: `master`

**Python version**:  `3.6`

**Operating system** (windows, osx, ...): `osx`

**Issue**:
When using templates from domain.yml, image urls are transformed into attachments, but using templates through external endpoint does not pick images from templates.

**Content of domain file** (if used & relevant):
```yaml

utter_with_image:
    - text: "some url to an image below"
      image: "https://i.imgur.com/..."

```
