### ISSUE TITLE
In case of multiple variables, flow defined in stories.md not being followed

### ISSUE THREAD

**Issue by conversationsman** [RasaHQ/rasa_nlu#2426]
**Rasa Core version**: 0.10.4
**Rasa NLU version**: 0.13.1

**Python version**:  3.6.4

**Operating system** (windows, osx, ...): Debian GNU/Linux 8 (jessie)

**Issue**:
If user follows the below flow:
1. User utters 'Hi'. User is responding with string to ask for 'vegetables' or 'fruits'
2. User utters 'vegetables'. User is asked for the vegetable name. This vegetable name is expected to be stored in a slot name 'vegetableName'
3. User utters name of the fruit which is defined as a sample in nlu.md for 'fruitName' slot

Achieved result: Rasa picks slot 'fruitName' as the value uttered and not respect the position it was in stories flow.
Expected result: Since vegetableName is of type 'text', Rasa should be picking any value uttered by user irrespective if it is defined as a sample for any other variable. The flow in stories.md should have been followed.

[vegetableOrfruit3.zip](https://github.com/RasaHQ/rasa_core/files/2297925/vegetableOrfruit3.zip)

**Content of domain file** (if used & relevant):
```yaml
actions:
- fruit_intent_response
- fruit_ask
- vegetable_intent_response
- vegetable_ask
- welcome_response
entities:
- fruitName
- vegetableName
intents:
- welcome
- fruits
- vegetables
slots:
  fruitName:
    type: text
  vegetableName:
    type: text
templates:
  fruit_ask:
  - Which fruit would you like?
  fruit_intent_response:
  - You are looking for Fruit - {fruitName}?
  vegetable_ask:
  - Which vegetable would you like?
  vegetable_intent_response:
  - You are looking for Vegetable - {vegetableName}?
  welcome_response:
  - Hey. Good to see you. Would like Fruits or Vegetables?
```
