### ISSUE TITLE
unfeaturized slot/entity not working as expected

### ISSUE THREAD

**Issue by lisongshan** [RasaHQ/rasa_nlu#2428]
**Rasa Core version**: 0.10.4

**Python version**:  3.6

**Operating system** (windows, osx, ...): 0sx

**Issue**:
unfeaturized slot/entity not work

I am expecting utterance u_request{"city": "text", "state":"text"} will match exactly to story_0, because "state" is specified as "unfeaturized"

My intention:  I want "city" is required, and "state" is optional and  I don't want optional entity/slot impacting dialogue flow, and I don't need stories involving optional entities.

**Content of domain file** (if used & relevant):
```yaml
slots: 
  city:
    type: text
  state:
    type: unfeaturized

intents: 
  - u_inform
  - u_request

entities: 
  - city
  - state:
      type: unfeaturized

templates: 
  goal.club_hours:
  - "dummy"
  Action.b_prompt.city:
  - "what is your city"

actions: 
  - Action.b_prompt.city
  - goal.club_hours
```
**Content of story file** (if used & relevant):
```md
## story_0
* u_request{"city": "text"}
  - goal.club_hours

## story_1
* u_request
  - Action.b_prompt.city
* u_inform{"city": "text"}
  - goal.club_hours
```
