### ISSUE TITLE
Buttons not getting displayed on UI

### ISSUE THREAD

**Issue by Priya-ch** [RasaHQ/rasa_nlu#2431]
**Rasa Core version**: 0.10.3

**Python version**:  2.7

**Operating system** (windows, osx, ...): Ubuntu 16.04
**Issue**:

I am new to rasa and trying to run first example with image and buttons.  I tried given code with buttons but in my UI nothing is displayed except text

**Content of domain file** (if used & relevant): domain.yml
```yaml
templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

 utter_happy:
  - text: "Great carry on!"

 utter_cheer_up:
  - text: "Here is something to cheer you up"
```
stories.md
##story_greet
* greet
   - utter_greet
* mood_great
  - utter_happy

## sad path 
* greet
  - utter_greet
* mood_unhappy
  - utter_cheer_up

nlu.md
## intent:greet
- hey
- hallo
- hey!
- helloe
- heyyy
- helloo
- hey
- hallo
- hiey!
- hellloe
- heiyyy
- helloo!
- ola
- hilo
- heyya
- hiiiiiii
- heyyyyyyyy
- hi

## intent:mood_great
- perfect
- very good
- great
- amazing
- wonderful
- I am feeling very good
- I am great
- I'm good

## intent:mood_unhappy
- sad
- very sad
- unhappy
- bad
- very bad
- awful
- terrible
- not very good
- extremly sad
- so sad

Also I tried the same thing with image:

domain.yml

 utter_greet:
  - text: "Hey! How are you?"
     image: "https://i.imgur.com/nGF1K8f.jpg"

even now only text is getting displayed. Kindly help if it is need to defined anywhere else as well
