### ISSUE TITLE
bot is not responding as per userStory

### ISSUE THREAD

**Issue by GurdeepSS** [RasaHQ/rasa_nlu#2438]
**Rasa Core version**:core is .8 and nlu .11

**Python version**: 2.7

**Operating system** (windows, osx, ...): unix

**Issue**:
bot is not responding as per userStory

**Content of domain file** (if used & relevant):
```yaml

domain.yaml
intents:
- greeting
- update_contact
- update_name
- shall_connect
- approve
- disapprove

entities:
  - user_email
  - user_number
  - user_firstname
  - user_lastname

slots:
  user_email:
    type: text
  user_number:
    type: text
  is_connected:
    type: bool
  
actions:
- utter_greeting
- utter_knowing_customer
- utter_ask_email
- utter_ask_firstname
- utter_ask_lastname
- utter_understand_issue
- utter_thanks
- utter_ask_number
- utter_want_to_buy
- utter_let_me_connect
- utter_what_product
#- actions.OpenSessionAgent
- open_session_agent

templates:
  utter_greeting:
  - text: "Hi, I will help you redirect to the right person, whatever your issue."

  utter_ask_firstname:
  - text: "What is your firstname.?"
  
  utter_ask_lastname:
  - text: "What is your lastname.?"

  utter_what_product:
  - text: "which product information you are looking for?."

  utter_knowing_customer:
  - text: "First, let me ask you few questions to help you redirect to the right person."

  utter_ask_email:
  - text: "what is your mail address please?"

  utter_understand_issue:
  - text: "I understand your issue, and will do everything i can to redirect you to the right information."

  utter_thanks:
  - text: "Thank you a lot."

  utter_ask_number:
  - text: "what is your phone number please?"

  utter_want_to_buy:
  - text: "Let me know how I can help you?"
  
  utter_let_me_connect:
  - text: "Sure, I can help you with that. Let me connect you to Cisco Sales team."

  utter_redirect_right:
  - text: "I have all the information I need, let me redirect you to the right person."

  open_session_agent:
  - text: "Connecting you to the Pre Sale Agent..."

Story.md
<!-- here contain example of conversation of the front end -->
## story0
* greeting
    - utter_greeting
    - utter_ask_firstname
* update_name{"user_firstname":"gurdeep"}
    - utter_ask_lastname
* update_name{"user_lastname":"singh"}
    - utter_thanks
    - utter_what_product
* shall_connect 
    - utter_let_me_connect
* approve
    - open_session_agent

## story1
* greeting
    - utter_greeting
    - utter_ask_firstname
* update_name{"user_firstname":"baljeet"}
    - utter_ask_lastname
* update_name{"user_lastname":"kour"}
    - utter_thanks
    - utter_what_product
* shall_connect 
    - utter_let_me_connect
* approve
    - open_session_agent

## story2
* greeting
    - utter_greeting
    - utter_ask_firstname
* update_name{"user_firstname":"jaskaran"}
    - utter_ask_lastname
* update_name{"user_lastname":"singh"}
    - utter_thanks
    - utter_what_product
* shall_connect 
    - utter_let_me_connect
* approve
    - open_session_agent

## story3
* greeting
    - utter_greeting
    - utter_ask_firstname
* update_name{"user_firstname":"jasraj"}
    - utter_ask_lastname
* update_name{"user_lastname":"sabarwal"}
    - utter_thanks
    - utter_what_product
* shall_connect 
    - utter_let_me_connect
* approve
    - open_session_agent

nlu.json
{
    "rasa_nlu_data": {
        "common_examples": [
            {
                "text": "Cisco Routers",
                "intent": "shall_connect"
            },
            {
                "text": "Routers",
                "intent": "shall_connect"
            },
            {
                "text": "information on Cisco Routers",
                "intent": "shall_connect"
            },
            {
                "text": "info on Cisco Routers",
                "intent": "shall_connect"
            },
            {
                "text": "Yea please, I want some information on Cisco Routers ",
                "intent": "shall_connect"
            },
            {
                "text": "hey",
                "intent": "greeting"
            },
            {
                "text": "hello",
                "intent": "greeting"
            },
            {
                "text": "hi",
                "intent": "greeting"
            },
            {
                "text": "hello there",
                "intent": "greeting"
            },
            {
                "text": "good morning",
                "intent": "greeting"
            },
            {
                "text": "good evening",
                "intent": "greeting"
            },
            {
                "text": "greetings!",
                "intent": "greeting"
            },
            {
                "text": "greetings!",
                "intent": "greeting"
            },
            {
                "text": "my first name is gurdeep",
                "intent": "update_name",
                "entities": [
                  {
                    "start": 17,
                    "end": 24,
                    "value": "gurdeep",
                    "entity": "user_firstname"
                  }
                ]
                },
                {
                    "text": "first name  gurdeep",
                    "intent": "update_name",
                    "entities": [
                      {
                        "start": 12,
                        "end": 19,
                        "value": "gurdeep",
                        "entity": "user_firstname"
                      }
                    ]
                 },
                {
                "text": "my last name is singh",
                "intent": "update_name",
                "entities": [
                  {
                    "start": 16,
                    "end": 21,
                    "value": "singh",
                    "entity": "user_lastname"
                  }
                ]
                },
                {
                    "text": "last name singh",
                    "intent": "update_name",
                    "entities": [
                      {
                        "start": 10,
                        "end": 15,
                        "value": "singh",
                        "entity": "user_lastname"
                      }
                    ]
                    },
                {
                "text": "gurdeep",
                "intent": "update_name",
                "entities": [
                  {
                    "start": 0,
                    "end": 7,
                    "value": "gurdeep",
                    "entity": "user_firstname"
                  }
                ]
                },
                {
                "text": "singh",
                "intent": "update_name",
                "entities": [
                  {
                    "start": 0,
                    "end": 5,
                    "value": "singh",
                    "entity": "user_lastname"
                  }
                ]
            },                             
            {
                "text": "xchemla@cisco.com",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 0,
                      "end": 17,
                      "value": "xchemla@cisco.com",
                      "entity": "user_email"
                    }
                  ]
            },
            {
                "text": "my email address is xchemla@cisco.com",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 20,
                      "end": 37,
                      "value": "xchemla@cisco.com",
                      "entity": "user_email"
                    }
                  ]
            },
            {
                "text": "my email is chemla.xavier@gmail.com",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 12,
                      "end": 35,
                      "value": "chemla.xavier@gmail.com",
                      "entity": "user_email"
                    }
                  ]
            },
            {
                "text": "xchemla@cisco.com is my email adress",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 0,
                      "end": 17,
                      "value": "xchemla@cisco.com",
                      "entity": "user_email"
                    }
                  ]
            },
            {
                "text": "xchemla@cisco.com is my email adress",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 0,
                      "end": 17,
                      "value": "xchemla@cisco.com",
                      "entity": "user_email"
                    }
                  ]
            },
            {
                "text": "628-234-7432 is my phone number",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 0,
                      "end": 12,
                      "value": "628-234-7432",
                      "entity": "user_number"
                    }
                  ]
            },
            {
                "text": "628-234-7432",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 0,
                      "end": 12,
                      "value": "628-234-7432",
                      "entity": "user_number"
                    }
                  ]
            },
            {
                "text": "my phone number is 628-234-7432",
                "intent": "update_contact",
                "entities": [
                    {
                      "start": 19,
                      "end": 31,
                      "value": "628-234-7432",
                      "entity": "user_number"
                    }
                  ]
            },
            {
                "text": "yes",
                "intent": "approve"
            },
            {
                "text": "yes please",
                "intent": "approve"
            },
            {
                "text": "yep",
                "intent": "approve"
            },
            {
                "text": "it is",
                "intent": "approve"
            },
            {
                "text": "yes it is!",
                "intent": "approve"
            },
            {
                "text": "indeed!",
                "intent": "approve"
            }         
        ],
        "regex_features" : [
            {
                "name": "user_email",
                "pattern": "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*)@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])"
            },
            {
                "name": "user_number",
                "pattern": "(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}"
            }
        ],
        "entity_synonyms": [
           
        ]
    }
}


```
