### ISSUE TITLE
How to train concertbot?

### ISSUE THREAD

**Issue by Waterbyte** [RasaHQ/rasa_nlu#2443]
**Rasa Core version**: Latest - 0.10.4 
**Python version**:  python 3.4

**Operating systes** (windows, osx, ...): ubuntu 14.04

**Issue**: I git cloned the rasa_core to get the examples files and installed rasa_core,rasa_nlu[tensorflow] and rasa_core_sdk from pip. Then I tried to train ConcertBot but on using the command : make train-core, i got the following issue :
```
ValueError: Action 'action_search_concerts' doesn't correspond to a template / action. Module doesn't contain a class with this name. Remember to prefix actions that should utter a template with `utter_`.
Error: 'action_search_concerts'
make: *** [train-core] Error 1
```

I haven't changed anything in Concertbot files.

**Content of domain file** (if used & relevant):
```yaml
slots:
  concerts:
    type: list
  venues:
    type: list

intents:
 - greet
 - thankyou
 - goodbye
 - search_concerts
 - search_venues
 - compare_reviews

entities:
 - name

templates:
  utter_greet:
    - "hey there!"
  utter_goodbye:
    - "goodbye :("
  utter_default:
    - "default message"
  utter_youarewelcome:
    - "you're very welcome"

actions:
  - utter_default
  - utter_greet
  - utter_goodbye
  - utter_youarewelcome
  - action_search_concerts
  - action_search_venues
  - action_show_concert_reviews
  - action_show_venue_reviews

```
