### ISSUE TITLE
AttributeError: 'Agent' object has no attribute 'train_online'

### ISSUE THREAD

**Issue by neerajb1** [RasaHQ/rasa_nlu#2472]
**Rasa Core version**: 0.11.3

**Python version**:  3.5

**Operating system** (windows, osx, ...): Windows

**Issue**:  agent.train_online( training_data_file,
AttributeError: 'Agent' object has no attribute 'train_online'

**Content of domain file** (if used & relevant):
```yaml
language: "en"

pipeline:
 - name: "nlp_spacy"
 - name: "tokenizer_spacy"
   model: "en"
 - name: "ner_crf"
 - name: "intent_featurizer_spacy"
 - name: "intent_classifier_sklearn"
```
