### ISSUE TITLE
action_listen always used as the next predicted action and bot not working as per stories

### ISSUE THREAD

**Issue by arpit-ism** [RasaHQ/rasa_nlu#2478]
**Rasa Core version**:0.8.2

**Python version**: python 3.6.5 Anaconda. Inc

**Operating system** (windows, osx, ...):OSX

**Issue**:I am unable to understand what went wrong whenever the bot predicts the next action. Its always action_listen and that too terminates  very quickly. Also, the desired actions according to stories do not work. The following is the log containing the run command execution of my bot with --debug

![screen shot 2018-09-07 at 2 18 00 pm](https://user-images.githubusercontent.com/16225168/45208737-f3d6f180-b2a8-11e8-9601-b75e6b4c7167.png)
![screen shot 2018-09-07 at 2 17 16 pm](https://user-images.githubusercontent.com/16225168/45208738-f3d6f180-b2a8-11e8-9b5e-85360f614c58.png)

**Content of domain file** (if used & relevant):
```yaml
--- 
actions: 
  - utter_greet
  - utter_help
  - ask_reg_details
  - confirm_call_again
  - accept_response
  - utter_goodbye
  - utter_vcnum
  - custom_actions.ActionValidateRegDetails
entities: 
  - vcnum
intents: 
  - greet
  - goodbye
  - affirm
  - deny
  - call_request
  - provide_reg_details
  - define_VCnum
templates: 
  accept_response: 
    - 
      text: Alright
  ask_reg_details: 
    - 
      text: "Could you please share your VC number or registered mobile number?"
  confirm_call_again: 
    - 
      text: "Confirm if you want a callback on your registered phone number"
  utter_goodbye: 
    - 
      text: "Goodbye! Have a nice day"
  utter_greet: 
    - 
      text: "Hello! I am ADI, your personal assistant"
  utter_help: 
    - 
      text: "Let me help you with that"
  utter_vcnum: 
    - 
      text: "VC number is a unique customer identification number alloted to every Dishtv user and can be found written on your Viewing Card."
slots:
  vcnum:
    type: float
    min_value: 1000000000
    max_value: 99999999999


stories.md file is:



## start up
  - utter_greet

## greetings path
* greet
  - utter_greet


## call customer path 1
* greet
  - utter_greet
* call_request
  - utter_help
  - ask_reg_details
* provide_reg_details{"vcnum":"23098493232"}
  - confirm_call_again
* affirm
  - accept_response

## call customer path 2
* greet
  - utter_greet
* call_request
  - utter_help
  - ask_reg_details
* define_VCnum
  - utter_vcnum
  - ask_reg_details
* provide_reg_details{"vcnum":"23098493232"}
  - confirm_call_again
* affirm
  - accept_response

## call customer path 3
* greet
  - utter_greet
* call_request
  - utter_help
  - ask_reg_details
* provide_reg_details{"vcnum":"23098493232"}
  - confirm_call_again
* deny
  - accept_response
* goodbye
  - utter_goodbye

## call customer path 4
* greet
  - utter_greet
* call_request
  - utter_help
  - ask_reg_details
* define_VCnum
  - utter_vcnum
  - ask_reg_details
* provide_reg_details{"vcnum":"23098493232"}
  - confirm_call_again
* deny
  - accept_response
* goodbye
  - utter_goodbye

## say goodbye
* goodbye
  - utter_goodbye


and the nlu.md file is:


## intent:greet
 - hey
 - hello
 - hi
 - good morning
 - good evening
 - hey there
 - Hiee
 - Are you up?
 - Hey buddy
 - Whats up adi?
 - good morning
 - good evening
 - hello bot
 - hey ADI
 - hi adi
 - hiee there
 - can we chat
 - whats up adi?
 - are you available now adi?
 - Hi
 - can you help me?
 - greetings
 - helloooo
 - heelooo
 - hiii
 - heee
 - helloooo
 - hi there buddy
 - hello buddy
 - hey man
 - hey how are you
 - hi, can you help me
 - hellooos
 - hy
 - hye
 - there?
 - is someone online?
 - are you available
 - can you help me, hi btw
 - good afternoon
 - are you up?
 - can we chat?
 - is someone there?
 - i need help
 - hey pal
 - hello pal


## intent:goodbye
 - bye
 - take care
 - go away
 - see you soon
 - ok now shut up
 - bye bye
 - goodbye
 - see you around
 - see you later
 - tata
 - tada
 - go away
 - fuck off
 - shut down
 - bbye
 - I am done
 - take care
 - now we can stop 
 - you are irritating me
 - go away adi
 - leave me


## intent:call_request
 - call me
 - I want a call back
 - Ring me on my phone
 - Can we move this conversation over mobile phone
 - I want to talk to your customer executive
 - Talk on phone
 - Can I call you
 - i want to talk on phone
 - call me on my registered phone number
 - want a callback
 - Are you a customer executive, can we talk
 - I dont want to chat, can we talk on phone
 - phone me
 - call on my mobile phone
 - move this conversation on call
 - ring me
 - ring me on my registered mobile number
 - call me on my mobile
 - can we talk 


## intent:provide_reg_details
 - it is [9101345641](vcnum)
 - my vc number [0002343239](vcnum)
 - it's [8989232418](vcnum)
 - ohh, thats [9320493823](vcnum)
 - ok, [01510026564](vcnum)
 - could you check if this is the one [02434958045](vcnum)
 - its [02434958045](vcnum)
 - yeah, [02434958045](vcnum)
 - ok , [02434958045](vcnum)
 - [02434934245](vcnum)
 - [34534958045](vcnum)
 - [02443495985](vcnum)
 - [98764958045](vcnum)
 - [90904958045](vcnum)
 - [00004958045](vcnum)
 - [35434958045](vcnum)
 - [02434958543](vcnum)
 - [02434967333](vcnum)
 - [02434958090](vcnum)
 - [02434951354](vcnum)
 - [02434090909](vcnum)
 - [02675438045](vcnum)
 - [02496448045](vcnum)
 - [02434999999](vcnum)
 - [02434945674](vcnum)
 - [02434967676](vcnum)
 - [02434900090](vcnum)


## intent:define_VCnum
 - what is vc number
 - What do you mean by vc number
 - vc number?
 - does this mean registration ID
 - where do I find vc number
 - what is that now
 - I cannot understand what vc number is 


## intent:deny
 - no
 - no thanks
 - nope
 - nahi
 - nooo
 - naah
 - do not
 - don't
 - dont
 - dont want 
 - nahi yaar
 - no man
 - cant you understand i said no
 - naa
 - not now
 - please no
 - no thank you
 - I refused it already 

## intent:affirm
 - yes
 - yeah
 - of course
 - ok
 - yes plese
 - yaah
 - yessss
 - yup
 - sure thing
 - sure
 - go ahead
 - as you wish
 - surely
 - ohh yes yes
 - hmm
 - hmmmmmm
 - yes please




```
