### ISSUE TITLE
Slot variable in payload of button

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_nlu#2501]
Hey,

this here http://rasa.com/docs/core/0.10.4/domains/#variables is not working when you have the varibale inside payload title of button. Is this correct? Would be nice if so...

Core 10.4

**Comment by selphe** [comment]
I can confirm this issue.
I use it with botframework api (button with link)

**Rasa version:**
rasa-core               0.13.7
rasa-core-sdk           0.13.0
rasa-nlu                0.14.6


**domain.yml**
```
utter_request_created:
    - text: "Your request {request_id}"
      buttons:
        - title: "{request_id}"
          value: 'https://path/to/request/{request_id}'
          type: "openUrl"
```

**Result:**
Bot says:
Text: Your request 123456
Button title: {request_id}
Button link: broken

**Expected result:**
Bot says:
Text: Your request 123456
Button title: 123456
Button link: https://path/to/request/123456

Btw, this could be solved with actions.
