### ISSUE TITLE
Using categorical slot values in different context

### ISSUE THREAD

**Issue by ramgesg** [RasaHQ/rasa_nlu#2518]
**Rasa Core version**: master

**Python version**: 3x

**Operating system** (windows, osx, ...): ubuntu

**Issue**:
Can categorical slots be used in different context. For example in the below domain file toppings slots will have different actions to be taken for each of items. The ask is can it be a generic story or it needs to be in serial.

say.. 
## main menu
* order{"item":"pizza"}
- utter_toppingneeded
## topping menu
* inform{"toppings":"mushroom"}
- slot{"item":"pizza"}
- do_pizza

## topping menu
* inform{"toppings":"mushroom"}
- slot{"item":"pasta"}
- do_pasta

**Content of domain file** (if used & relevant):
```yaml
slots:
  item:
    type: categorical
    values:
    - pasta
    - pizza
    - sandwich
  toppings:
    type: categorical
    values:
    - mushroom
    - onion
    - tomato
```
