### ISSUE TITLE
policy / ensemble configurable via file

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_nlu#2530]
policy / ensemble configurable via file, similar to rasa nlu pipeline. Would be great to be able to specify the model and policies in a yaml file that we read in. The file format could look like this:
```yaml
batch_size: 20
epochs: 30
policies:
- name: KerasPolicy
- name: FallbackPolicy
  intent_threshold: 0.3
  action_threshold: 0.4
```
