### ISSUE TITLE
interactive learning error

### ISSUE THREAD

**Issue by e8180kimo** [RasaHQ/rasa_nlu#2534]
**Rasa Core version**: 0.13.1

**Python version**:  0.13.1

**Operating system** (windows, osx, ...): OS High Sierra

**Issue**:
When I tried to run interactive learning by input: `python -m rasa_core.train   --online -o models/current/dialogue   -d domain.yml -s data/stories.md   --endpoints endpoints.yml`
It returns `Can not access action 'action_topic', as that name is not a registered action for this domain. `
But I did have that in the `actions.py`
```

/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
2018-09-20 20:00:31 WARNING  rasa_core.training.dsl  - Found unknown intent 'Learner_type_topic' on line 75. Please, make sure that all intents are listed in your domain yaml.
Processed Story Blocks:   0%|               | 0/5 [00:00<?, ?it/s, # trackers=1]2018-09-20 20:00:31 WARNING  rasa_core.domain  - Failed to use action 'action_topic' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
2018-09-20 20:00:31 WARNING  rasa_core.domain  - Failed to use action 'action_topic' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
2018-09-20 20:00:31 WARNING  rasa_core.domain  - Failed to use action 'action_topic' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
...
Processed Story Blocks: 100%|██████| 5/5 [00:00<00:00, 38.18it/s, # trackers=23]
Processed actions: 0it [00:00, ?it/s, # examples=7]Traceback (most recent call last):
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 251, in index_for_action
    return self.action_names.index(action_name)
ValueError: 'action_topic' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wisionlearning/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/train.py", line 239, in <module>
    additional_arguments)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/train.py", line 186, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/agent.py", line 510, in train
    **kwargs)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 66, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/policies/memoization.py", line 152, in train
    self._add(trackers_as_states, trackers_as_actions, domain)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/policies/memoization.py", line 108, in _add
    feature_item = domain.index_for_action(action)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 253, in index_for_action
    self._raise_action_not_found_exception(action_name)
  File "/Users/wisionlearning/anaconda3/lib/python3.6/site-packages/rasa_core/domain.py", line 261, in _raise_action_not_found_exception
    "Available actions are: \n{}".format(action_name, action_names))
Exception: Can not access action 'action_topic', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - utter_greet
	 - utter_type_of_paper
	 - utter_choose_topic
	 - utter_ask_essay_topic
	 - utter_access_reading
	 - utter_skim_articles
	 - utter_read_highlight_topic_of_choice
	 - utter_show_highlights
	 - utter_ask_Learner_argument_after_highlight_slot_1
	 - utter_knowledge_what_thesis_statement
	 - utter_definition_thesis_statement
	 - utter_need_example_thesis_statement
	 - utter_ask_Learner_type_thesis_slot_1
	 - utter_confirm_thesis_arguable
	 - utter_whether_knowing_arguable
	 - utter_confirm_thesis_focused
	 - utter_whether_knowing_focused
	 - utter_definition_arguable_thesis
	 - utter_definition_focused_thesis
	 - utter_request_help_teacher
	 - utter_good_bye
	 - actions.ActionTopic
	 - actions.ActionArgument
	 - actions.ActionThesis
	 - utter_default
```

actions.py
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import argparse
import logging
import warnings
import os

from policy import ridePolicy
from rasa_core import utils
from rasa_core.actions import Action
from rasa_core.agent import Agent
from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.events import SlotSet
from rasa_core.featurizers import (
    MaxHistoryTrackerFeaturizer,
    BinarySingleStateFeaturizer)
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.policies.memoization import MemoizationPolicy

from rasa_core.actions.forms import (
    BooleanFormField,
    EntityFormField,
    FormAction,
    FreeTextFormField
)

logger = logging.getLogger(__name__)

class BookingInfo(object):
    def save(self, essay_topic):
        logger.debug("-------essay_topic---------")
        logger.debug(format(essay_topic))
        logger.debug("-------essay_topic---------")

        return
class ArgumentafInfo(object):
    def save(self, Learner_argument_after_highlight_slot_1):

        logger.debug("-------Learner_argument_after_highlight_slot_1---------")
        logger.debug(format(Learner_argument_after_highlight_slot_1))
        logger.debug("-------Learner_argument_after_highlight_slot_1---------")
        return
class ThesisInfo(object):
    def save(self, Learner_type_thesis_slot_1):

        logger.debug("-------Learner_type_thesis_slot_1---------")
        logger.debug(format(Learner_type_thesis_slot_1))
        logger.debug("-------Learner_type_thesis_slot_1---------")
        return		
class ActionTopic(FormAction):

    RANDOMIZE = False
    

    @staticmethod
    def required_fields():
        return [
            EntityFormField("essay_topic", "essay_topic")
            
        ]

    def name(self):
        return 'action_topic'

    def submit(self, dispatcher, tracker, domain):
        
        Bookinginfo = BookingInfo()
        booking = Bookinginfo.save(tracker.get_slot("essay_topic"))
        #indexFile_topic = open('C:/Users/e8180/Documents/sfu/py_rasabot/dd0628/dd/' + 'testextract.txt', 'a+')
        #indexFile_topic.write(tracker.get_slot("essay_topic") + str('\n\n'))
        #indexFile_topic.close()
        #return[SlotSet("matches", booking)]
        return
class ActionArgument(FormAction):

    RANDOMIZE = False
    

    @staticmethod
    def required_fields():
        return [
            FreeTextFormField("Learner_argument_after_highlight_slot_1")
            
        ]

    def name(self):
        return 'action_argument'

    def submit(self, dispatcher, tracker, domain):
        
        Argumenta_Info = ArgumentafInfo()
        booking = Argumenta_Info.save(tracker.get_slot("Learner_argument_after_highlight_slot_1"))
       
        return

class ActionThesis(FormAction):

    RANDOMIZE = False
    

    @staticmethod
    def required_fields():
        return [
            FreeTextFormField("Learner_type_thesis_slot_1")
            
        ]

    def name(self):
        return 'action_thesis'

    def submit(self, dispatcher, tracker, domain):
        
        Thesis_info = ThesisInfo()
        booking = Thesis_info.save(tracker.get_slot("Learner_type_thesis_slot_1"))
       
        return
		
def train_dialogue(domain_file="domain.yml",
                   model_path="models/current/dialogue",
                   training_data_file="data/stories.md"):
    from rasa_core.policies.fallback import FallbackPolicy
    from rasa_core.policies.keras_policy import KerasPolicy
    from rasa_core.agent import Agent

    fallback = FallbackPolicy(fallback_action_name="action_default_fallback", core_threshold=0.5, nlu_threshold=0.5 )
    agent = Agent(domain_file,
                  policies=[KerasPolicy(), fallback, MemoizationPolicy(max_history=3),
                            ])

    training_data = agent.load_data(training_data_file)
    agent.train(
            training_data,
            epochs=200,
            batch_size=100,
            validation_split=0.2
    )

    agent.persist(model_path)
    return agent

def train_nlu():
    from rasa_nlu.training_data import load_data
    from rasa_nlu import config
    from rasa_nlu.model import Trainer

    training_data = load_data('data/nlu_data.md')
    trainer = Trainer(config.load("config_spacy.yml"))
    trainer.train(training_data)
    model_directory = trainer.persist('models/nlu/', fixed_model_name="current")

    return model_directory

def run(serve_forever=True):
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    agent = Agent.load("models/current/dialogue", interpreter=interpreter)

    if serve_forever:
        agent.handle_channel(ConsoleInputChannel())
    return agent


if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")

    parser = argparse.ArgumentParser(
            description='starts the bot')

    parser.add_argument(
            'task',
            choices=["train-nlu", "train-dialogue", "run"],
            help="what the bot should do - e.g. run or train?")
    task = parser.parse_args().task

    # decide what to do based on first parameter of the script
    if task == "train-nlu":
        train_nlu()
    elif task == "train-dialogue":
        train_dialogue()
    elif task == "run":
        run()
```
**Content of domain file** (if used & relevant):
domain
```yaml
intents:
  - greet
  - request_essay_help
  - choose_argument
  - choose_no
  - confirm_completion
  - learner_typetopic
  - learnertype_argumentafterhighlights
  - learnertype_thesis
  - goodbye
  - out_of_scope
  
actions:
- utter_greet
- utter_type_of_paper
- utter_choose_topic
- utter_ask_essay_topic
- utter_access_reading
- utter_skim_articles
- utter_read_highlight_topic_of_choice
- utter_show_highlights
- utter_ask_Learner_argument_after_highlight_slot_1
- utter_knowledge_what_thesis_statement
- utter_definition_thesis_statement
- utter_need_example_thesis_statement
- utter_ask_Learner_type_thesis_slot_1
- utter_confirm_thesis_arguable
- utter_whether_knowing_arguable
- utter_confirm_thesis_focused
- utter_whether_knowing_focused
- utter_definition_arguable_thesis
- utter_definition_focused_thesis
- utter_request_help_teacher
- utter_good_bye
- actions.ActionTopic
- actions.ActionArgument
- actions.ActionThesis
- utter_default 

entities:
  - essay_topic
  - Learner_argument_after_highlight_slot_1
  - Learner_type_thesis_slot_1

slots:
  essay_topic:
    type: text
  Learner_argument_after_highlight_slot_1:
    type: text
  Learner_type_thesis_slot_1:
    type: text  
  requested_slot:
    type: unfeaturized
    
templates:
  utter_default :
  - text: "Sorry, I didn’t understand that"
  utter_greet:
  - text: "How may I help you?"
  utter_type_of_paper:
  - text: "Okay, what type of paper? Here are some options of different types of essays that I can help you with"
    buttons:
    - title: "Compare & Contrast Essay"
      payload: "compare_contrast"
    - title: "Argumentative Essay"
      payload: "argue"
    - title: "Cause and Effect Essay"
      payload: "cause"
    - title: "Problem & Solution Essay"
      payload: "problem"
  utter_choose_topic:
  - text: "Okay, do you have a topic in mind?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_ask_essay_topic:
  - text: "What is your topic?"
  utter_access_reading:
  - text: "Access reading resources provided by your instructor ..link to canvas.. As you can see the articles are grouped into different modules. choose one or two modules you would be interested in. Let me know when you are done."
    buttons: 
    - title: "I am done"
      payload: "done"
  utter_skim_articles:
  - text: "Now skim the titles of articles under each module. Choose 3 to 4 articles under each module. Read each article. Let me know when you are done."
    buttons: 
    - title: "I am done"
      payload: "done"
  utter_read_highlight_topic_of_choice:
  - text: "Now go back to the module with articles about {essay_topic}. Start hghlighting parts that interest you. Let me know when you are done."
    buttons: 
    - title: "I am done"
      payload: "done"
  utter_show_highlights:
  - text: "Now Hers is the list of all the highlights you made. ..link to highlights... Now review the highlights to decide whether your position is for or against the topic about {essay_topic}. Let me know when you are done."
    buttons: 
    - title: "I am done"
      payload: "done"
  utter_ask_Learner_argument_after_highlight_slot_1:
  - text: "Now tell me something you can argue for/or argue against {essay_topic}"  
  utter_knowledge_what_thesis_statement:
  - text: "very good. It's time to construct a thesis statement ? Do you know what a thesis statement is?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_definition_thesis_statement:
  - text: "A thesis statement is a statement of position. In university writing, it is typically a sentence or two which establishes your argument and forecasts the main points that your paper will argue. It is the backbone of your paper because everything that follows should support this central argument. A thesis has to be arguable/contestable and cannot be a statement of fact. Does this make sense? "
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_need_example_thesis_statement:
  - text: "Do you need an example?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_ask_Learner_type_thesis_slot_1:
  - text: "O.K. Now let's work on your thesis statemnt. From the conversation we had, you said that {Learner_argument_after_highlight_slot_1}. Now think about it and try to fill in the sentence: {Learner_argument_after_highlight_slot_1} because X, Y, and Z." 
  utter_confirm_thesis_arguable:
  - text: "This is your {Learner_type_thesis_slot_1}. Now think about this: Is your thesis statement arguable/contestable?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_whether_knowing_arguable:
  - text: "Do you know what arguable is?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_confirm_thesis_focused:
  - text: "Is your thesis statement focused?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_whether_knowing_focused:
  - text: "Do you know what a focused thesis means?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_definition_arguable_thesis:
  - text: "Your thesis is probably not contestable if it is a neutral statement, it is a fact, or it only answers the questions 'what'. Do you need more help from your teacher?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_definition_focused_thesis:
  - text: "a focused thesis statement means that you includes brief reasons for your argument. Do you need more help from your teacher?"
    buttons:
    - title: "Yes"
      payload: "yes"
    - title: "No"
      payload: "no"
  utter_request_help_teacher:
  - text: "Okay, now I recommend you go to your TA or professor for clarifications. Let me know when you are done."
    buttons: 
    - title: "I am done"
      payload: "done"
  utter_good_bye:
  - text: "This is your thesis statement {Learner_type_thesis_slot_1}. It is now arguable and focused. Do you need any other help?" 
```
