### ISSUE TITLE
Mapping same entity to different slots

### ISSUE THREAD

**Issue by sabyasachee** [RasaHQ/rasa_nlu#2554]
rasa_core: 0.11.4
python: 3.6.6
OS: macOS 10.14

I am building a flight information retrieval system. I have an entity type: location and two slots, origin and destination. The system can ask the user about the city of origin: utter_ask_origin and also ask about the city of destination: utter_ask_destination. In both cases, the user might give a simple answer like Los Angeles or New York. The intent of this message is inform_location with location entity: [Los Angeles](location) or [New York](location). In the first case, I need it to be mapped to slot: origin and in the second case I need it to be mapped to slot: destination. What is the best way to do that?

domain.yml
```
intents:
  - greet
  - goodbye
  - ask_flights
  - inform_origin
  - inform_dest
  - inform_location
  - inform_date
  - inform_airline
  - easter_egg
  - affirm
  - negate

slots:
  origin:
    type: text
  destination:
    type: text
  date:
    type: text
  airline:
    type: text

entities:
  - origin
  - destination
  - location
  - date
  - airline

templates:
  utter_greet:
    - "Hello! How can I help you?"
    - "Welcome! What can I do for you?"
  utter_goodbye:
    - "Bye!"
    - "Goodbye!"
  utter_ask_origin:
    - "What is your origin city?"
    - "Where do you want to travel from?"
    - "Name the city from where you want to start?"
  utter_ask_destination:
    - "What is your destination city?"
    - "Where do you want to travel to?"
    - "Name the city you want to reach?"
  utter_ask_date:
    - "What is your date of journey?"
    - "When do you want to travel?"
  utter_ask_airline:
    - "Which airline do you want to travel with?"
  utter_easter_egg:
    - "Fight on for ol’ SC!"

actions:
  - utter_greet
  - utter_goodbye
  - utter_ask_origin
  - utter_ask_dest
  - utter_ask_date
  - utter_ask_airline
  - utter_easter_egg
  - action_time

```
