### ISSUE TITLE
Resolve environment variables in endpoints.yml

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa_nlu#2571]
**Rasa Core version**:0.11.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): linux

**Issue**:
In my endpoints.yml
```
nlu:
  url: ${NLU_URL}
  params:
    - model_name: ${NLU_MODEL}
    - project_name: ${AGENT}
nlg:
  url: ${NLG_URL}
```
I have environment values. I have also tried directly putting the URL, model name and project name. 
NLG started working but not the NLU, is there something wrong with the params?
