### ISSUE TITLE
tracker.get_slot returning None

### ISSUE THREAD

**Issue by hd016** [RasaHQ/rasa_nlu#2638]
Rasa Core version:
rasa-core==0.11.11
rasa-core-sdk==0.11.5
rasa-nlu==0.13.6

Python version: 3.6.3

Operating system (windows, osx, ...): Mac OSX 10.11.16

**bot.py**
```
import logging,  warnings
import rasa_core

from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.utils import EndpointConfig
from rasa_core.run import serve_application



logging.basicConfig(level="INFO")
warnings.filterwarnings('ignore')
logger = logging.getLogger(__name__)


def train_dialogue(domain_file = "/Users/x/PycharmProjects/x/x/domain.yml",
                   model_path="/Users/x/PycharmProjects/x/x/models/dialogue",
                   training_data_file="/Users/x/PycharmProjects/x/x/stories.md"):

    agent = Agent(domain_file, policies=[KerasPolicy()])
    data = agent.load_data(training_data_file)
    agent.train(
            data,
            validation_split=0.2,
            epochs=400,
            batch_size=50,
    )

    agent.persist(model_path)

    return agent

def run_bot(serve_forever=True):

    interpreter = RasaNLUInterpreter('/Users/x/PycharmProjects/x/x/models/current/nlu/default/nlu')
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent.load('/Users/x/PycharmProjects/x/x/models/dialogue', interpreter=interpreter, action_endpoint=action_endpoint)
    rasa_core.run.serve_application(agent, channel="cmdline")

    return agent


if __name__ == '__main__':
    train_dialogue()
    run_bot()

```
**actions.py**
```
from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

import requests

class ActionCheckStatus(Action):
    def name(self):
        return "action_check_status"

    def run(self, dispatcher, tracker, domain):
        r = requests.get('https://myorg.com')
        status = r.status_code
        if status == 200:
            dispatcher.utter_message("myorg.com looks up from here.")
        else:
            dispatcher.utter_message("myorg.com looks down from here.")
            return []


class ActionWeather(Action):
    def name(self):
        return 'action_check_weather'

    def run(self, dispatcher, tracker, domain):

        loc = tracker.get_slot('location')

        response = "Response: {}".format(loc)

        dispatcher.utter_message(response)

        return [SlotSet('location',loc)]

```

**nlu_model.py**
```
from rasa_nlu.training_data import load_data
from rasa_nlu import config
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata, Interpreter

def train_nlu(data, configs, model_dir):
	training_data = load_data(data)
	trainer = Trainer(config.load(configs))
	trainer.train(training_data)
	model_directory = trainer.persist(model_dir, fixed_model_name = 'nlu')

def run_nlu():
	interpreter = Interpreter.load('/Users/x/PycharmProjects/x/x/models/current/nlu')
	print(interpreter.parse(u"I am planning my holiday to Lithuania. I wonder what is the weather out there."))

if __name__ == '__main__':
	train_nlu('/Users/x/PycharmProjects/x/x/nlu.md',
              '/Users/x/PycharmProjects/x/x/config_spacy.json',
              '/Users/x/PycharmProjects/x/x/models/current/nlu')
	run_nlu()
```

**stories.md**
```
## Weater1
* greet
  - utter_greet
* inform
  - utter_ask_location
* inform[location=Berlin]
  - action_check_weather
  - slot{"location": "Berlin"}
```

**domain.yml**
```
slots:
  location:
    type: text

intents:
  - greet
  - goodbye
  - tell_joke
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy
  - _is_down
  - inform

entities:
 - location

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_joke
- utter_down
- action_check_status
- action_check_weather
- utter_ask_location

templates:
  utter_greet:
  - text: "Hey!"
  - text: "Hi!"



  utter_ask_location:
  - text: "In what Location"
  - text: "From which Location do you would have the weather?"
```

**Run Bot.py**
```
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Hi
Hi!
127.0.0.1 - - [2018-10-19 11:27:34] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 203 0.165833
How is the weather?
From which Location do you would have the weather?
127.0.0.1 - - [2018-10-19 11:27:38] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 250 0.020365
Poland
The Weather in None is at the moment 34°.
127.0.0.1 - - [2018-10-19 11:27:41] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 246 0.039611
```

**Action Server:**
```
INFO:__main__:Starting action endpoint server...
INFO:rasa_core_sdk.executor:Registered function for 'action_check_status'.
INFO:rasa_core_sdk.executor:Registered function for 'action_check_weather'.
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
DEBUG:rasa_core_sdk.executor:Received request to run 'action_check_weather'
None
DEBUG:rasa_core_sdk.executor:Successfully ran 'action_check_weather'
127.0.0.1 - - [2018-10-19 11:27:41] "POST /webhook HTTP/1.1" 200 291 0.003555

```

I have short the domain and stories, because they have huge of lines.

Why I got the Response as "None" from the tracker.get_slot?
