### ISSUE TITLE
How to use 'inform' intent in FormAction SlotFilling??? Need example train.md file for 'inform' intent

### ISSUE THREAD

**Issue by stalinsabu** [RasaHQ/rasa_nlu#2652]
**Rasa Core version**: 0.10.4

**Rasa NLU version**: 0.13.7

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): windows 10

**Issue**:
I have been trying to work on a form filling bot but I am not able to understand the documentation, especially the **inform** intent. When the bot starts up it works as expected i.e. if the intent and entities are recognized, the action is performed. If the entities are not recognized it replies with `utter_ask_{slot}` but it doesn't understand the next intent which is, according to the documentation, `inform` intent.
How do we use **inform** intent? What is the training we have to provide for **inform** intent in the train.md file? and how can we make it in a way that after `utter_ask_{slot}` the user types in a text and that text will be taken as the intent. Is using `unfeaturised` type a solution? Because it has to take that **specific entity** and if it doesn't find it, it should ask `utter_ask_{slot}` again.
In the documentation it says create an intent `inform` and train it. Is the `inform` generalized i.e. can it be used for multiple slot filling like in restaurant bot user has to fill in cuisine, people, rating, nearest location, etc. do we have to give a one single common intent called `inform` or do we have to make multiple `inform_{entity}` for each entity? Making an intent `inform`, won't it affect the nlu? random words or text can be classified as **inform** intent which affects the dialogue as well?
In short I am just asking for a train.md example for `inform` intent for each slot coz I cant find any, that's all.
I am a student and a beginner, so RASA is very new to me. If its ok I would suggest that you make FormAction as a separate documentation rather than keeping it under SlotFilling. And in the examples a form filling bot would be really helpful.
_And regarding the rasa core version, I am still using the old one as there are more examples and the migration is not easy to understand for me, as I am still getting comfortable. I will upgrade it once I am able to understand the working completely. But let me just add RASA is a great tool and easy to use. Hats off to the team!_

**Content of domain file** (if used & relevant):
```yaml
intents:
  - bye
  - check
  - compliment
  - confirm
  - get_form
  - hello
  - how_are_you
  - how_to_contact
  - my_name_is
  - name_misc
  - nice_to_meet_you
  - nonsense
  - procedure
  - refute
  - thanks
  - whats_new
  - whats_the_weather
  - where_is

entities:
  - PERSON
  - location_value
  - GPE
  - contact_value
  - contact_item
  - procedure_item
  - procedure_value
  - procedure_value_extra
  - check_item

slots:
  Location:
    type: text
  PERSON:
    type: text
    initial_value: "human"
  GPE:
    type: text
    initial_value: "fujairah"
  contact_value:
    type: text
  contact_item:
    type: text
  form_item:
    type: text
  requested_slot:
    type: unfeaturized

templates:
  utter_ask_form_item:
    - Which form do you need?
    - Which form?
    - and name of the form?
    - which form is it?
    - I am sorry. Which form are you looking for?
    - I didn't get which form it is that you are looking for.
  utter_bye:
    - Bye.
    - Goodbye.
    - It was nice talking to you
    - I am glad to assist you
    - Talk to you later
    - Nice meeting you
    - See you soon
  utter_confirm_reply:
    - Great
    - OK
    - alright
  utter_hello:
    - Hi!
    - Hello, my friend.
    - Hi! How are you doing?
    - Hey! How can I be of service?
    - Hey!
    - How may I help you?
  utter_how_are_you:
    - How are you?
    - How are you doing?
    - Great day isn't it?
  utter_how_are_you_name:
    - How are you {PERSON}?
    - How are you doing {PERSON}?
    - Great day isn't it {PERSON}?
  utter_how_i_am:
    - I am great, thanks!
    - I am doing ok.
    - I am good.
    - Me and my friends 0 and 1 are doing great!
    - My system is up and running
    - Me == GREAT
  utter_intro:
    - Hey this is POF IntelliBot! How may I help you?
    - Hi!
    - My name is POF IntelliBot!
    - I am here to help you answer all your queries
  utter_nice_to_meet:
    - Hey it's nice to meet you!
    - Nice too meet you.
    - Pleasure!
  utter_nice_to_meet_name:
    - It's nice to meet you, {PERSON}.
    - Nice to meet you, {PERSON}.
    - Hi {PERSON}
    - That's a nice name! Great to meet you {PERSON}.
  utter_refute_reply:
    - Oh
    - Ok
    - alright
    - sorry
  utter_sorry:
    - I am sorry
    - Sorry about that
    - Sorry I wasn't much help
    - Forgive me. I am still learning.
    - Sorry
  utter_sorry_no_help:
    - I am sorry
    - Sorry about that
    - Sorry I wasn't much help
    - Sorry I don't know that.
    - Sorry I can't help you at the moment.
    - Sorry?
    - Sorry I didn't understand
    - I am not able to understand what you are saying
    - Could you be a little more clear please?
  utter_thank_you:
    - Gee thanks!
    - Thank you.
  utter_you_are_welcome:
    - The pleasure is all mine.
    - Happy to help.
    - Not a problem.
    - Just doing my job.
    - You are welcome!
    - Anytime!

actions:
  - utter_ask_form_item
  - utter_bye
  - utter_confirm_reply
  - utter_hello
  - utter_how_are_you
  - utter_how_are_you_name
  - utter_how_i_am
  - utter_intro
  - utter_nice_to_meet
  - utter_nice_to_meet_name
  - utter_refute_reply
  - utter_sorry
  - utter_sorry_no_help
  - utter_thank_you
  - utter_you_are_welcome
  - domain.actions.formAction.ActionGetForm

```

**Content of stories.md (form only) file**:
```md
## get_form_f00
* get_form
  - utter_ask_form_item
  - slot{"requested_slot": "form_item"}
* inform{"form_item": "a permit"}
  - action_get_form

## get_form_f01
* get_form
  - action_get_form
  - slot{"requested_slot": "form_item"}
* inform{"form_item": "another permit"}
  - action_get_form

## get_form_f02
* get_form
  - action_get_form
  - slot{"requested_slot": "form_item"}
* inform{"form_item": "PERMIT"}
  - action_get_form

## get_form_f03
* get_form
  - action_get_form
  - slot{"requested_slot": "form_item"}
* inform{"form_item": "PERMIT"}
  - action_get_form

## get_form_f04
* get_form
  - action_get_form
  - slot{"requested_slot": "form_item"}
* inform{"form_item": "Photography"}
  - action_get_form

## get_form_f05
* get_form{"form_item": "permit"}
  - action_get_form

## get_form_f06
* get_form{"form_item": "7m"}
  - action_get_form

```
