### ISSUE TITLE
Calling FormAction from ReminderScheduled executes the submit method directly

### ISSUE THREAD

**Issue by aanchan** [RasaHQ/rasa_nlu#2686]
<!-- THIS INFORMATION IS MANDATORY - YOUR ISSUE WILL BE CLOSED IF IT IS MISSING. If you don't know your Rasa Core version, use `pip list | grep rasa_core`. Removing the below information is allowed for FEATURE REQUESTS. --> 

**Rasa Core version**:
0.10.3
**Python version**: 
Python 3.5
**Operating system** (windows, osx, ...):
Ubuntu 18.04
**Issue**:
In calling a form action `action_trigger_checkin` from a `ReminderScheduled` calls the `submit` method of that action directly instead of asking the form questions.

***Relevant actions.py**
<pre>
class ActionInputPreferences(FormAction):
    RANDOMIZE = False

    def __init__(self):
        self.profile_dict =  { "whenAlert" : None,
                               "whenSleepy" : None,
                               "whenEnjoyWakeUp" : None,
                               "whenMostEnergy" : None,
                               "coffeeDrinker" : None,
                               "smoker" : None,
                               "drinks" : None,
                             }

        self.dict_options = {"whenAlert_a": "Morning",
                             "whenAlert_b": "Evening",
                             "whenSleepy_a": "Early Evening",
                             "whenSleepy_b" : "Past 11pm",
                             "whenEnjoyWakeUp_a": "6am or earlier",
                             "whenEnjoyWakeUp_b": "8am or later",
                             "whenMostEnergy_a" : "After waking",
                             "whenMostEnergy_b" : "Before bed",
                             "drinks_a" : "t",
                             "drinks_b" : "f",
                             "coffeeDrinker_a": "t",
                             "coffeeDrinker_b": "f",
                             "smoker_a" : "t",
                             "smoker_b" : "f"
                            }

    def name(self):
        return 'action_input_preferences'

    @staticmethod
    def required_fields():
        return[
            EntityFormField("choice","whenAlert"),
            EntityFormField("choice","whenSleepy"),
            EntityFormField("choice","whenEnjoyWakeUp"),
            EntityFormField("choice", "coffeeDrinker"),
            EntityFormField("choice", "whenMostEnergy"),
            EntityFormField("choice","smoker"),
            EntityFormField("choice", "drinks"),
            EntityFormField("time", "targetSleepTime")
        ]



    def submit(self, dispatcher, tracker, domain):

        for key, value in self.profile_dict.items():
            the_slot = tracker.get_slot(key)
            if the_slot == 'a':
                opt_str  = key + '_' + the_slot
                self.profile_dict[key] = self.dict_options[opt_str]
            elif the_slot == 'b':
                opt_str  = key + '_' + the_slot
                self.profile_dict[key] = self.dict_options[opt_str]

        from dateutil import parser
        from datetime import timedelta
        dt_target_sleep = parser.parse(tracker.get_slot('targetSleepTime'))
        dt_target_wakeup = parser.parse(tracker.get_slot('targetSleepTime')) + timedelta(hours=7, minutes=30)
        self.profile_dict['targetSleepTime'] = dt_target_sleep.isoformat()
        self.profile_dict['targetWakeUpTime'] = dt_target_wakeup.isoformat()
        if PROD:
            back_end = BackEnd(tracker.sender_id)
        elif DEV:
            back_end = BackEnd(TEST_PHONE)
        r = back_end.submit_sleep_preferences(self.profile_dict)
        return []


class ActionTriggerDailyCheckIn(Action):                                                                                                        
    def name(self):                                                                                                                             
        return 'action_trigger_daily_checkin'                                                                                                   
                                                                                                                                                
    def run(self, dispatcher, tracker, domain):                                                                                                 
        import datetime as dt                                                                                                                   
        from datetime import timedelta                                                                                                          
        if PROD:                                                                                                                                
            CHECK_IN_TIME = dt.time(hour=12)                                                                                                    
            tomorrow = dt.date.today() + timedelta(days=1)                                                                                      
        elif DEV:                                                                                                                               
            CHECK_IN_TIME = (dt.datetime.now() + timedelta(minutes=1)).time()                                                                   
            tomorrow = dt.datetime.now().date()                                                                                                 
                                                                                                                                                
        if PROD:                                                                                                                                
            back_end = BackEnd(tracker.sender_id)                                                                                               
        elif DEV:                                                                                                                               
            back_end = BackEnd(TEST_PHONE)                                                                                                      
        time_zone = back_end.get_time_zone()                                                                                                    
        tomorrow_noon = dt.datetime.combine(tomorrow, CHECK_IN_TIME)                                                                            
        tomorrow_noon = tomorrow_noon.replace(tzinfo=time_zone)                                                                                 
        date_of_sleep = back_end.query_sleep_api()                                                                                              
        print(date_of_sleep)                                                                                                                    
        return [ReminderScheduled('action_daily_checkin', tomorrow_noon, kill_on_user_message=False), SlotSet('dateOfSleep', date_of_sleep) ]   

class ActionDailyCheckIn(FormAction):                                        
    RANDOMIZE = False                                                        
                                                                             
    def name(self):                                                          
        return 'action_daily_checkin'                                        
                                                                             
                                                                             
    @staticmethod                                                            
    def required_fields():                                                   
        return [                                                             
            EntityFormField("number", "sleepQualityRating"),                 
            EntityFormField("number", "refreshQualityRating")                
        ]                                                                    
                                                                             
    def submit(self, dispatcher, tracker, domain):                           
        if PROD:                                                             
            back_end = BackEnd(tracker.sender_id)                            
        elif DEV:                                                            
            back_end = BackEnd(TEST_PHONE)                                   
        dict_to_send = {                                                     
            "sleepQualityRating" : tracker.get_slot("sleepQualityRating"),   
            "refreshQualityRating" : tracker.get_slot("refreshQualityRating")
            "dateOfSleep" : tracker.get_slot('dateOfSleep')                  
        }                                                                    
        back_end.submit_quality_rating(dict_to_send)                         
        <b>tracker.follow_up_action = ActionTriggerBedtimeReminder()</b>            
        # update in 11.x FollowupAction('action_trigger_bedtime_reminder')   
        return []                                                            


</pre>

**Stories file**
```
## story 01
* start
  - utter_start
* affirm 
  - action_input_preferences
  - slot{"requested_slot": "whenAlert"}
* inform{"choice" : "a"}
  - action_input_preferences
  - slot{"whenAlert" : "a"}
  - slot{"requested_slot": "whenSleepy"}
* inform{"choice" : "b"}
  - action_input_preferences
  - slot{"whenSleepy" : "b"}
  - slot{"requested_slot": "whenEnjoyWakeUp"}  
* inform{"choice": "b"}
  - action_input_preferences
  - slot{"whenEnjoyWakeUp":"b"}
  - slot{"requested_slot" : "whenMostEnergy"}  
* inform{"choice":"b"}
  - action_input_preferences
  - slot{"whenMostEnergy" : "b"}
  - slot{"requested_slot" : "coffeeDrinker"}
* inform{"choice": "a"}
  - action_input_preferences
  - slot{"coffeeDrinker" : "a"}
  - slot{"requested_slot" : "smoker"}
* inform{"choice": "a"}
  - action_input_preferences
  - slot{"smoker" : "a"}
  - slot{"requested_slot" : "drinks"}
* inform{"choice" : "b"}
  - action_input_preferences
  - slot{"drinks" : "b"}
  - slot{"requested_slot" : "targetSleepTime"}
* inform{"time": "11:00pm"}
  - action_input_preferences  
  - slot{"targetSleepTime" : "11:00pm"}
  - utter_goodbye
  - action_trigger_bedtime_reminder


## story02 get feedback from user in the morning
  - action_bedtime_reminder
  - action_trigger_daily_checkin
  - slot{"dateOfSleep":"2018-10-12"}
  - utter_good_morning
* affirm
  - action_daily_checkin
  - slot{"requested_slot": "sleepQualityRating"}
* inform{"number" : 3}
  - action_daily_checkin
  - slot{"sleepQualityRating" : 3}
  - slot{"requested_slot" : "refreshQualityRating"}
* inform{"number" : 2}
  - action_daily_checkin
  - slot{"refreshQualityRating": 2}
  - action_trigger_bedtime_reminder
```

**Content of domain file** (if used & relevant):
```yaml
intents:
  - start
  - affirm
  - deny
  - goodbye
  - inform
  - goal_bedtime

slots:
 whenAlert:
   type: text
 whenSleepy:
   type: text
 whenEnjoyWakeUp:
   type: text
 whenMostEnergy:
   type: text
 coffeeDrinker:
   type: text
 smoker:
   type: text
 drinks:
   type: text
 requested_slot:
   type: unfeaturized
 targetSleepTime:
   type: text
 sleepQualityRating:
   type: float
   min_value: 0
   initial_value: 0
 refreshQualityRating:
   type: float
   min_value: 0
   initial_value: 0
 dateOfSleep:
    type: text

entities:
  - time
  - choice
  - number
  - requested_slot
  
actions:
  - utter_start
  - utter_goodbye
  - utter_thanks
  - utter_ask_whenAlert
  - utter_ask_whenSleepy
  - utter_ask_whenEnjoyWakeUp
  - utter_ask_whenMostEnergy
  - utter_ask_coffeeDrinker
  - utter_ask_smoker
  - utter_ask_drinks
  - utter_ask_cupsOfCoffeePerDay
  - utter_ask_cigarettesPerDay
  - utter_ask_alcoholPerWeek
  - utter_ask_targetSleepTime
  - utter_ask_sleepQualityRating
  - utter_ask_refreshQualityRating
  - actions.ActionInputPreferences
  - actions.ActionTriggerBedtimeReminder
  - actions.ActionBedtimeReminder
  - actions.ActionTriggerDailyCheckIn
  - actions.ActionDailyCheckIn
  #- actions.ActionQuerySleepAPI
templates:
 utter_start:
   - "Great, I'll start off by asking some basic questions to get to know you. Is that alright?"

 utter_ask_whenAlert:
   - "What time of the day do you generally feel alert \n A. Early in the morning. \n B. Late in the evening. \n Type in A or B."

 utter_thanks:
   - "Ok. Thank you."
 utter_goodbye:
    - "Thanks for taking the time to answer some basic questions. \n I will send you a reminder a couple of hours before your goal bedtime. In the morning, I'll follow up to ask how well you think you slept. Bye for now."
 utter_ask_whenSleepy:
   - "What time do you generally feel sleepy? \n A. In the early evening. \n B. Past 11 pm. \n Type in A or B."

 utter_ask_whenEnjoyWakeUp:
   - "When do you enjoy waking up? \n A. 6 am or earlier. \n B. 8am or later. \n Type in A or B."

 utter_ask_coffeeDrinker:
   - "Are you a coffee drinker? \n A. Yes, \n B. No. \n Type in A or B."

 utter_ask_whenMostEnergy:
   - "When do you have most energy? \n A. After waking \n B. Before Bed. \n Type in A or B."
 
 utter_ask_cupsOfCoffeePerDay:
   - "How many cups of coffee do you drink in a day?"

 utter_ask_smoker:
   - "Do you smoke? \n A. Yes. \n B. No. \n Type in A or B."

 utter_ask_cigarettesPerDay:
    - "How many cigarettes do you smoke per day (roughly)?"

 utter_ask_drinks:
   - "Do you drink? \n A. Yes B. No. \n Type in A or B."

 utter_ask_alcoholPerWeek:
   - "How many glasses of alcohol do you consume in a week?"

 utter_ask_targetSleepTime:
   - "What time would you ideally get to bed on weekdays? (Please make sure to include AM/PM!)"

 utter_reminder:
  - "Remember, bedtime tonight is {targetSleepTime}."
  - "Don't forget: bedtime tonight is {targetSleepTime}!"

 utter_ask_sleepQualityRating:
  - "How would you rate your sleep quality on a scale of 1-4? \n 1:Very Bad, 2: Fairly Bad, 3: Fairly Good, 4: Very Good."

 utter_ask_refreshQualityRating:
  - "How refreshed do you feel on a scale of 1-4? \n 1:Tired, 2: Sleepy, 3: Groggy, 4: Refreshed."
```
**Relevant debug mode output**
```
2018-11-01 22:44:47 DEBUG    rasa_core.processor  - Action 'action_daily_checkin' ended with events '[]'
2018-11-01 22:44:47 DEBUG    rasa_core.processor  - Current slot values: 
	sleepQualityRating: 0
	smoker: a
	refreshQualityRating: 0
	whenAlert: a
	requested_slot: targetSleepTime
	whenEnjoyWakeUp: a
	targetSleepTime: 11 pm
	whenSleepy: b
	dateOfSleep: 2018-10-23
	whenMostEnergy: a
	drinks: a
	coffeeDrinker: b
2018-11-01 22:44:47 DEBUG    rasa_core.policies.memoization  - Current tracker state [{'slot_coffeeDrinker_0': 1.0, 'slot_whenSleepy_0': 1.0, 'prev_action_trigger_daily_checkin': 1.0, 'slot_smoker_0': 1.0, 'slot_whenAlert_0': 1.0, 'slot_drinks_0': 1.0, 'slot_whenMostEnergy_0': 1.0, 'slot_dateOfSleep_0': 1.0, 'slot_targetSleepTime_0': 1.0, 'slot_whenEnjoyWakeUp_0': 1.0}, {'slot_coffeeDrinker_0': 1.0, 'slot_whenSleepy_0': 1.0, 'slot_whenAlert_0': 1.0, 'slot_smoker_0': 1.0, 'slot_drinks_0': 1.0, 'prev_action_listen': 1.0, 'slot_whenMostEnergy_0': 1.0, 'slot_dateOfSleep_0': 1.0, 'slot_targetSleepTime_0': 1.0, 'slot_whenEnjoyWakeUp_0': 1.0}, {'slot_coffeeDrinker_0': 1.0, 'slot_whenSleepy_0': 1.0, 'slot_whenAlert_0': 1.0, 'slot_smoker_0': 1.0, 'slot_drinks_0': 1.0, 'prev_action_daily_checkin': 1.0, 'slot_whenMostEnergy_0': 1.0, 'slot_dateOfSleep_0': 1.0, 'slot_targetSleepTime_0': 1.0, 'slot_whenEnjoyWakeUp_0': 1.0}]
2018-11-01 22:44:47 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2018-11-01 22:44:47 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_1_KerasPolicy
2018-11-01 22:44:47 DEBUG    rasa_core.policies.ensemble  - Predicted next action 'action_listen' with prob 0.94.
2018-11-01 22:44:47 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'
2018-11-01 22:44:47 INFO     apscheduler.executors.default  - Job "MessageProcessor.handle_reminder (trigger: date[2018-11-01 22:44:46 PDT], next run at: 2018-11-01 22:44:46 PDT)" executed successfully
```
**Edit 1**
I have an earlier FormAction that actually finishes much later. Its submit method calls an endpoint, and sometimes it calls that endpoint twice. Its really buggy. I've updated it with my earlier form action, and stories.
