### ISSUE TITLE
Sensitive information in the endpoint configuration file

### ISSUE THREAD

**Issue by leon0707** [RasaHQ/rasa_nlu#2699]
**Rasa Core version**:
0.12.0a4
**Python version**: 
3.6.6
**Operating system** (windows, osx, ...):
osx
**Issue**:
Saving sensitive information like user name, password in the yaml file is not a good idea. The user name and password should be saved in the environment variables.

Use `${XXX}` to represent an environment variable.
```yaml
tacker_store:
  mongo:
     host: http://localhost:27017
     db: rasa
     user: ${user}
     password: ${pass}
     collection: conversations
```

**Content of domain file** (if used & relevant):
```yaml
tacker_store:
  mongo:
     host: http://localhost:27017
     db: rasa
     user: user
     password: pass
     collection: conversations
```

credentials.yml
```yaml
facebook:
  verify: "rasa-bot"
  secret: "3e34709d01ea89032asdebfe5a74518"
  page-access-token: "EAAbHPa7H9rEBAAuFk4Q3gPKbDedQnx4djJJ1JmQ7CAqO4iJKrQcNT0wtD"
```
