### ISSUE TITLE
Erro in Training File

### ISSUE THREAD

**Issue by mk4224** [RasaHQ/rasa_nlu#2706]
**Rasa Core version**:  0.11.5

**Python version**:  2.7.12 

**Operating system** (windows, osx, ...): Unix

**Issue**:
When i am training the file i am getting the following error message in terminal:--
  warnings.warn(warning, RequestsDependencyWarning)
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
DEBUG:rasa_core_sdk.executor:Received request to run 'action_order_product'
ERROR:flask.app:Exception on /webhook [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/administrator/.local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/administrator/.local/lib/python2.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/administrator/.local/lib/python2.7/site-packages/rasa_core_sdk/endpoint.py", line 72, in webhook
    response = executor.run(action_call)
  File "/home/administrator/.local/lib/python2.7/site-packages/rasa_core_sdk/executor.py", line 170, in run
    "".format(action_name))
Exception: No registered Action found for name 'action_order_product'.
127.0.0.1 - - [2018-11-08 11:52:42] "POST /webhook HTTP/1.1" 500 412 0.018317

I have written python script "action.py" where i am trying to fetch data from the mongoDb data base which i have already designed.  I have made the data base and inserted the necessary documents. I think some error i am getting there only. please help me to fix it. I am attaching my " action.py " file here..

action.py::--
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

import pymongo

from rasa_core.actions.action import Action
from rasa_core.events import SlotSet

class ActionWeather(Action):
	def name(self):
		return 'action_order_product'

	def run(self, dispatcher, tracker, domain):
        #import pymongo
          myclient = pymongo.MongoClient("mongodb://localhost:27017/")
          mydb = myclient["mydigidata"]
          mycol = mydb["mydigicollection"]
          router = tracker.get_slot('location')
          myquery = { "Q": "router" }
          mydoc = mycol.find(myquery)
          for x in mydoc:
                res = x
          response = """Your question is: {}. Here is your answer- {}""".format(router, res)
          dispatcher.utter_message(response)
          return [SlotSet('location',router)]

**Content of domain file** (if used & relevant):
```yaml
slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform_ct


entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_keyword:
    - 'Please give keywords'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_keyword
 - action_order_product
 - action.ActionWeather
 - utter_ct

```
