### ISSUE TITLE
action_listen not being executed after an utter_ask_x action in a FormAction is executed.

### ISSUE THREAD

**Issue by ckomega** [RasaHQ/rasa_nlu#2750]
**Rasa Core version**: 0.12.1

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): CentOS 7

**Issue**: 
When running interactive learning, or after training the core model and just running it, core will always predict with probability 1.00 to rerun action_get_policy_by_topic instead of waiting after executing it once so that the user can respond with the required information. It's supposed to execute action_get_policy_by_topic, then execute the utter_ask_policy_topic, then execute action_listen. But instead of executing action_listen, it executes action_get_policy_by_topic again, and again, and again. This results in utter_ask_policy_topic also being called, but it won't ever execute action_listen.

**Content of stories file** (if used & relevant):
```
## greet
* greet
    - utter_greet
> check_hello

## goodbye
* goodbye
    - utter_goodbye
> check_goodbye

## happy
* thankyou
    - utter_youarewelcome
> check_thanks

## Find_policy 01
> check_hello
* find_policy{"policy_topic":"data breaches"}
    - slot{"policy_topic":"data breaches"}
    - action_get_policy_by_topic
> check_thanks

## Find_policy 02
> check_hello
* find_policy{"policy_topic":"us person"}
    - slot{"policy_topic":"us person"}
    - action_get_policy_by_topic
> check_thanks

## Find_policy 03
> check_hello
* find_policy{"policy_topic":"incidents"}
    - slot{"policy_topic":"incidents"}
    - action_get_policy_by_topic
> check_thanks

## Find_policy 04
> check_hello
* find_policy{"policy_topic":"cybersecurity"}
    - slot{"policy_topic":"cybersecurity"}
    - action_get_policy_by_topic
> check_thanks

## Find_policy 05
> check_hello
* find_policy{"policy_topic":"executive orders"}
    - slot{"policy_topic":"executive orders"}
    - action_get_policy_by_topic
> check_thanks

## Find_policy 06
> check_hello
* find_policy{"policy_topic":"data inquiries"}
    - slot{"policy_topic":"data inquiries"}
    - action_get_policy_by_topic

## Find_policy 07
* greet
    - utter_greet
* find_policy{"policy_topic": "US person identification"}
    - slot{"policy_topic": "US person identification"}
    - action_get_policy_by_topic
    - slot{"policy_topic": "US person identification"}
    - slot{"policy_topic": null}
* find_policy{"policy_topic": "compliance relating to software development"}
    - slot{"policy_topic": "compliance relating to software development"}
    - action_get_policy_by_topic
    - slot{"policy_topic": "compliance relating to software development"}
    - slot{"policy_topic": null}
* thankyou
    - utter_youarewelcome

## Find_policy 08
* greet
    - utter_greet
* find_policy{"policy_topic": "classification guidance"}
    - slot{"policy_topic": "classification guidance"}
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"policy_topic": "classification guidance"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* thankyou
    - utter_youarewelcome

## Find_policy // Inform 01
* find_policy
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"requested_slot": "policy_topic"}
* form: inform{"policy_topic": "Operational security and compliance"}
    - slot{"policy_topic": "Operational security and compliance"}
    - form: action_get_policy_by_topic
    - slot{"policy_topic": "Operational security and compliance"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* thankyou
    - utter_youarewelcome

## Find_policy // Inform 02
* greet
    - utter_greet
* find_policy{"policy_topic": "cryptographic algorithm evaluation"}
    - slot{"policy_topic": "cryptographic algorithm evaluation"}
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"policy_topic": "cryptographic algorithm evaluation"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* thankyou
    - utter_youarewelcome

## Find_policy // Inform 03
* greet
    - utter_greet
* find_policy
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"requested_slot": "policy_topic"}
* form: inform{"policy_topic": "application development environments"}
    - slot{"policy_topic": "application development environments"}
    - form: action_get_policy_by_topic
    - slot{"policy_topic": "application development environments"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* goodbye
    - utter_goodbye

## Find_policy // Inform 04
* find_policy
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"requested_slot": "policy_topic"}
* form: inform{"policy_topic": "search restrictions"}
    - slot{"policy_topic": "search restrictions"}
    - form: action_get_policy_by_topic
    - slot{"policy_topic": "search restrictions"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* thankyou
    - utter_youarewelcome

## Find_policy // Inform 05
* greet
    - utter_greet
* find_policy
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"requested_slot": "policy_topic"}
* form: inform{"policy_topic": "privacy laws and statutes"}
    - slot{"policy_topic": "privacy laws and statutes"}
    - form: action_get_policy_by_topic
    - slot{"policy_topic": "privacy laws and statutes"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* thankyou
    - utter_youarewelcome

## Find_policy // Inform 06
* greet
    - utter_greet
* find_policy
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"requested_slot": "policy_topic"}
* form: inform{"policy_topic": "Law and ethics pertaining to compliance"}
    - slot{"policy_topic": "Law and ethics pertaining to compliance"}
    - form: action_get_policy_by_topic
    - slot{"policy_topic": "Law and ethics pertaining to compliance"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* goodbye
    - utter_goodbye

## Find_policy // Inform 07
* find_policy
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"requested_slot": "policy_topic"}
* form: inform{"policy_topic": "personal location services"}
    - slot{"policy_topic": "personal location services"}
    - form: action_get_policy_by_topic
    - slot{"policy_topic": "personal location services"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* goodbye
    - utter_goodbye

## Find_policy // Inform 08
* find_policy
    - action_get_policy_by_topic
    - form{"name": "action_get_policy_by_topic"}
    - slot{"requested_slot": "policy_topic"}
* form: inform{"policy_topic": "cryptanalysis and computer network operations"}
    - slot{"policy_topic": "cryptanalysis and computer network operations"}
    - form: action_get_policy_by_topic
    - slot{"policy_topic": "cryptanalysis and computer network operations"}
    - slot{"policy_topic": null}
    - form{"name": null}
    - slot{"requested_slot": null}
* thankyou
    - utter_youarewelcome
```

**Content of domain file** (if used & relevant):
```
%YAML 1.1
---
actions:
- utter_default
- utter_youarewelcome
- utter_confused
- action_get_policy_by_topic
- utter_greet
- utter_ask_policy_topic
- utter_ask_policy_name
- utter_goodbye
config:
  store_entities_as_slots: true
entities:
- policy_topic
forms: []
intents:
- thankyou
- find_policy
- greet
- goodbye
- inform
slots:
  policy_topic:
    auto_fill: true
    type: rasa_core.slots.TextSlot
  requested_slot:
    auto_fill: true
    type: rasa_core.slots.UnfeaturizedSlot
templates:
  utter_ask_policy_name:
  - text: What is the name of the policy?
  utter_ask_policy_topic:
  - text: What is the topic of the policy/document you are looking for?
  - text: What kind of information are you looking for?
  - text: What information would you like to search for?
  utter_confused:
  - text: I'm not sure I understood your last message. Could you please try again?
  utter_default:
  - text: Welcome to the most awesomest chatbot ever!
  utter_goodbye:
  - text: Goodbye.
  - text: Farewell.
  - text: So long.
  - text: You will be missed.
  - text: See you later.
  utter_greet:
  - text: Hey there!
  - text: Greetings!
  - text: Hello.
  - text: Howdy
  - text: Hey!
  - text: Hello from the Other Side!
  utter_youarewelcome:
  - text: You're very welcome. What else can I help you with today?
```
