### ISSUE TITLE
slack channel connector stopped working after upgrading to 0.12.2

### ISSUE THREAD

**Issue by harshad2994** [RasaHQ/rasa_nlu#2787]
**Rasa Core version**: 0.12.2

**Python version**: 3.6

**Operating system** (windows, osx, ...):ubuntu 16.04 and MAC osx

**Issue**:
slack channel connector stopped working after upgrading to 0.12.2. It was working fine in 0.11.12.

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```
