### ISSUE TITLE
ruamel.yaml.reader.ReaderError: unacceptable character 

### ISSUE THREAD

**Issue by HRiv** [RasaHQ/rasa_nlu#2794]
**Rasa Core version**:
0.12.2
**Python version**: 
Python 3.6.7
**Operating system** (windows, osx, ...):
Windows 10 Pro
**Issue**:
Trying to train the example conversation from "Quick start" section in rasa core docs, the following issue is raised:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

This happens when I execute "python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue"

giving this error

![issue](https://user-images.githubusercontent.com/23371457/49469695-93d7e480-f7de-11e8-96bb-b672e696a6c3.png)

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```
