### ISSUE TITLE
Form Action does not ask to fill required slot

### ISSUE THREAD

**Issue by rameshjesswani** [RasaHQ/rasa_nlu#2820]
**Rasa Core version**:
0.11.7
**Python version**: 
3.5.2
**Operating system** (windows, osx, ...): ubuntu

**Issue**: Form Action does not ask to fill required slots 

**Content of domain file**:
```yaml


slots:

  requested_slot:
    type: unfeaturized

  location:
    type: text
    
  PERSON:
    type: text

  country:
    type: text

 place:
    type: text

address:
   type: unfeaturized

entities:

  - GPE
  - PERSON
  - location
  - address
  

intents:

  - greet
  - goodbye
  - search_place
  - save_information

actions:

- action_get_information
- utter_ask_field
- utter_submit

templates:

  utter_happy:
  - text: "I am happy"

  utter_ask_address:
  - text: "Address please ?"

  utter_goodbye:
  - "Bye"
  - "Tye Tye"
  - "Bye bye, see you soon :)"

  utter_submit:
  - text: "thanks for your information. "

forms:
  - action_get_information

```
**Content of story file**:

```  

## request information
* save_information
  - action_get_information
  - slot{"name": "action_get_information"}

## say goodbye
* goodbye
  - utter_goodbye

## find restaurant 
* restaurant_search
  - action_show_restaurants

```
**Content of actions file**:

```
class UniversityForm(FormAction):


   def name(self):
       # type: () -> Text
       """Unique identifier of the form"""

       return "action_get_information"

   @staticmethod
   def required_slots(tracker):
       # type: () -> List[Text]
       """A list of required slots that the form has to fill"""

       return ["address"]

   def submit(self, dispatcher, tracker, domain):
       # type: (CollectingDispatcher, Tracker, Dict[Text, Any]) -> List[Dict]
       """Define what the form has to do
           after all required slots are filled"""

       # utter submit template
       dispatcher.utter_template('utter_submit', tracker)
       return []
```

Can anyone help me to figure out why form action is not asking for required slots?
