### ISSUE TITLE
Intent classification fails when entity extraction is performed

### ISSUE THREAD

**Issue by DNCoelho** [RasaHQ/rasa_nlu#2822]
**Rasa Core version**:
0.12.3
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
ubuntu 18.04
**Issue**:
I'm pretty new to Rasa and was exploring its capabilities when a strange behavior occurred.
I had started by creating a nlu model capable of intent classification and entity extraction for my native language, which worked fine when made available through http.

Example: 
Request: 
`{"q":"Procuro um restaurante italiano em 12345"}`

Response:
`{
    "intent": {
        "name": "restaurant_search",
        "confidence": 0.7113155505293147
    },
    "entities": [
        {
            "entity": "cuisine",
            "value": "italiano",
            "start": 23,
            "end": 31,
            "confidence": null,
            "extractor": "ner_mitie"
        },
        {
            "entity": "location",
            "value": "12345",
            "start": 35,
            "end": 40,
            "confidence": null,
            "extractor": "ner_mitie"
        }
    ],
    "intent_ranking": [
        {
            "name": "restaurant_search",
            "confidence": 0.7113155505293147
        },
        {
            "name": "greet",
            "confidence": 0.15049657601423475
        },
        {
            "name": "affirm",
            "confidence": 0.0821662299874645
        },
        {
            "name": "goodbye",
            "confidence": 0.0560216434689861
        }
    ],
    "text": "Procuro um restaurante italiano em 12345",
    "project": "default",
    "model": "model_20181210-181406"
}`

However, when I used the model through a Rasa_core bot something unexpected happened the model everything is fine while no entities are present in a message, however whenever an entity is present no intent is detected.
As an example something like:
Procuro restaurante - Looking for a restaurant  Works
While:
Procuro restaurante mexicano - Looking for a mexican restaurant  Doesn't

**Content of domain file** (if used & relevant):
```yaml
language: "pt"

pipeline:
- name: "nlp_mitie"
  model: "data/total_word_feature_extractor_pt.dat"
- name: "tokenizer_mitie"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"

```

Any help regarding this issue would be greatly appreciated.
