### ISSUE TITLE
Failed to load model metadata from '/app/current/metadata.json'

### ISSUE THREAD

**Issue by stacybot123** [RasaHQ/rasa_nlu#2856]
Rasa Core version: 0.13.0a5

Python version: 3.5

Operating system** (windows, osx, ...): ubantu 16.04.5

Issue: 

I am following the exact steps at : 
https://rasa.com/docs/core/docker_walkthrough/#docker-walkthrough

when I run docker-compose up , I am getting error as : 
rasa_nlu.model.InvalidProjectError:
```
 Failed to load model metadata from '/app/current/metadata.json'. [Errno 2] No such file or directory: 'current/metadata.json'
```
Here is the  docker-compose.yml file: 

```
version: '2'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    ports:
      - 80:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/
  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models

```

I used the same exact command to train NLU and Core as in the tutorial

Do not know why it is looking for the metadata.json in current folder , while it should be looking the file in current/model_20181226-143707/

Here is  the screen sort of file structure in the container : 

![image](https://user-images.githubusercontent.com/26300235/50450185-3bfe4a80-0952-11e9-9e44-56ee73a30ded.png)
