### ISSUE TITLE
Troubles to get FormAction working

### ISSUE THREAD

**Issue by Junitinn** [RasaHQ/rasa_nlu#2915]
**Rasa Core version**: 0.11.1
**Python version**: 2.7.10
**Operating system** (windows, osx, ...): macOS

**Issue**: When I run 'train_initialize.py' in order to train my model I get this error:

Can not access action 'montoincrementos_form', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - utter_saludo
	 - utter_estado_animo
	 - utter_incrementos_personas_a_cargo
	 - definir_derecho_incrementos

I understand 'montoincrementos_form' is not an action but a FormAction and stories.md is using it as an action. I guess I am missing something but I do not know where

**Content of domain file** 
```yaml
slots:
    usuario_ley_de_pension:
        type: text
    numerohijos:
        type: float
    casado:
        type: bool
    requested_slot:
        type: unfeaturized
    
intents:
    - saludo
    - estado_animo
    - incrementos_personas_a_cargo
    - ley_pension
    - calcular_incrementos
entities:
     - usuario_ley_de_pension
     - numerohijos
     - casado
templates:
    utter_saludo:
        - 'Hola. '
    utter_estado_animo:
        - 'Me siento muy bien, estoy listo para ayudarte.'
    utter_incrementos_personas_a_cargo:
        - 'Si.'
    utter_calcular_incrementos:
        - 'Te puedo ayudar'
    utter_ask_numerohijos:
        - '¿Podrias decirme cuantos hijos tienes?'
    utter_ask_casado:
        - '¿Podrias decirme si estas casado?'

actions:
  - utter_saludo
  - utter_estado_animo
  - utter_incrementos_personas_a_cargo
  - definir_derecho_incrementos

forms: 
  - montoincrementos_form

```

**Content of actions.py file**

```yaml
logger = logging.getLogger(__name__)
FORM_SLOT_NAME = "requested_slot"
    
class Calcular_Monto_Incrementos(FormAction):

    def name(self):
       # type: () -> Text
       return "montoincrementos_form"

    @staticmethod
    def required_fields(tracker):
       # type: () -> List[Text]
       return [
            EntityFormField("numerohijos"),
            EntityFormField("casado")]
    

    def submit(self, dispatcher, tracker, domain):
       # type: (CollectingDispatcher, Tracker, Dict[Text, Any]) -> List[Dict]
        hijos = tracker.get_slot('numero_hijos')
        casado = tracker.get_slot('casado')
       # utter submit template
        if hijos == 3:
            dispatcher.utter_message("tienes 3")
        else:
            dispatcher.utter_message("no tienes 3")
        return []

```
 
**contain of stories.md file**

```
## Conversación 1
* saludo
  - utter_saludo
* estado_animo
  - utter_estado_animo
* incrementos_personas_a_cargo
  - utter_incrementos_personas_a_cargo
* ley_pension
  - slot{"usuario_ley_de_pension": "Acuerdo 049 de 1990"}
  - definir_derecho_incrementos
* calcular_incrementos
  - montoincrementos_form

```
