### ISSUE TITLE
Rasa isn't running custom actions

### ISSUE THREAD

**Issue by cigol1234** [RasaHQ/rasa_nlu#2923]
**Rasa Core version**: 0.12.3

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Rasa isn't returning anything associated with custom actions. Whenever the user sends a message associated with an intent that has an "utter_*" action it returns the response no problem, however when a user sends a message that is associated with an intent that has a custom action Rasa_Core just returns an empty list '[]' for agent.handle_text(message) with no error. The actions.py file is in the same folder as the domain file and it also has print messages to check if the relevant functions are being called however they never print anything when they should as if Rasa isn't even calling them. I ran "python3 -m rasa_core_sdk.endpoint --actions actions" to register the functions and it outputted:
```
INFO:__main__:Starting action endpoint server...
INFO:rasa_core_sdk.executor:Registered function for 'action_get_fee'.
INFO:rasa_core_sdk.executor:Registered function for 'action_get_description'.
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```
I then Ctrl-C'd to stop the running endpoint, I was told that the actions should still work in my own app now, despite Exiting this running process.

**Content of stories file**:
```
## greet 
* greet 
 - utter_greet 
 
## goodbye
* goodbye
 - utter_goodbye

## fee_check
* fee_check
 - utter_ask_student
* inform_student{"student": "eu"}
 - action_get_fee

## description_check
* description_check
 - action_get_description
 ```

**Content of actions.py file**:
```
from rasa_core_sdk import Action

class GetFees(Action):
    def name(self):
        return "action_get_fee"

    def run(self, dispatcher, tracker, domain):
        print("Checking Fees...")
        return "Checking Fees..."

class GetDescription(Action):
    def name(self):
        return "action_get_description"

    def run(self, dispatcher, tracker, domain):
        print("Checking Description...")
        return "Checking Description..."
```

**Content of domain file**:
```yaml
action_factory: remote

slots:
  course:
    type: text
  student:
    type: categorical
    values:
      — scottish
      — eu
      — international
      — other-uk

intents:
- greet
- goodbye
- fee_check
- description_check
- inform_student

entities:
- course
- student

actions:
- utter_greet
- utter_goodbye
- utter_fee_check
- utter_description_check
- utter_ask_student
- action_get_fee
- action_get_description

templates:
  utter_greet:
  - text: "Hello! How can I help?"
  
  utter_goodbye:
  - text: "Goodbye!"

  utter_fee_check:
  - text: "The {course} fees for {student} students are ..."

  utter_description_check:
  - text: "The course description for {course} is: ..."
  
  utter_ask_student:
  - text: "And are you a Scottish, EU, International, or Other-UK student?"
```
