### ISSUE TITLE
NameError: Cannot access action 'form("name": "candy_form"}', as that name is not a registered action for this domain. Available actions are:

### ISSUE THREAD

**Issue by elcolie** [RasaHQ/rasa_nlu#2942]
**Rasa Core version**:
```bash
rasa-core==0.13.0
rasa-core-sdk==0.12.1
rasa-nlu==0.14.1
```

**Python version**: 
`3.6.8`

**Operating system** (windows, osx, ...):
OSX `10.14.2`

**Issue**:
`make train-core` raises the error
```bash
NameError: Cannot access action 'form("name": "candy_form"}', as that name is not a registered action for this domain. Available actions are:
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - action_deactivate_form
	 - action_revert_fallback_events
	 - action_default_ask_affirmation
	 - action_default_ask_rephrase
	 - utter_greet
	 - utter_noworries
	 - utter_show_colors
	 - utter_show_prices
	 - utter_list_colors
	 - utter_list_prices
	 - action_list_colors
	 - action_list_pricing
	 - candy_form
```

I have checked with community forum, but no solution found there.

**Content of domain file** (if used & relevant):
`stories.md`
```yaml
## not_buy
* greet
  - utter_greet
* first_query
  - utter_show_colors
* deny
  - utter_noworries

## list candy and bye
* greet
  - utter_greet
* color_query
  - utter_show_colors
* detail_query
  - utter_show_prices
* deny
  - utter_noworries

## Generated Story 2476928141338771446
* greet
  - utter_greet
* color_query
  - utter_show_colors
* deny
  - utter_noworries

## Admin list colors from database not hardcode
* db_list_colors
  - action_list_colors
  - slot{"COLOR_LIST": "three colors"}
  - utter_list_colors
* db_list_prices
  - action_list_pricing
  - slot{"PRICE_LIST": "three colors"}
  - utter_list_prices

## Try form
* test_form
  - candy_form
  - form("name": "candy_form"}
  - form("name": null}
* deny
  - utter_noworries

```

`domain.yml`
```yaml
intents:
  - first_query:
      use_entities: false
  - chitchat:
      use_entities: false
  - bargain
  - inform
  - affirm
  - deny
  - stop
  - thankyou
  - greet
  - color_query
  - comment
  - detail_query
  - db_list_colors
  - db_list_prices
  - test_form

entities:
  - COLOR
  - QTY
  - COLOR_LIST

slots:
  QTY:
    type: unfeaturized
    auto_fill: false
  COLOR:
    type: unfeaturized
    auto_fill: false
  COLOR_LIST:
    type: unfeaturized
    auto_fill: false
  PRICE_LIST:
    type: unfeaturized
    auto_fill: false

templates:
  utter_ask_color:
    - text: "รับลูกอมสีอะไรดีครับ"
  utter_ask_qty:
    - text: "รับกี่เม็ดดีครับ"
  utter_ask_feedback:
    - text: "ขอคำติชมซักนิด เพื่อปรับปรุงการบริการครับ"
  utter_submit:
    - text: "เรียบร้อย"
  utter_confirm:
    - text: "สั่งของดังนี้น่ะครับ {COLOR} {QTY}"
  utter_noworries:
    - text: "ไม่มีปัญหาครับ มาได้ทุกเวลา"
  utter_chitchat:
    - text: "คุยเล่น"
  utter_ask_continue:
    - text: "ทำรายการต่อเถอะครับ"
  utter_wrong_color:
    - text: "ลูกอมสีนี้ ไม่มีในระบบครับ ขออภัย"
  utter_wrong_qty:
    - text: "ปริมาณต้องเป็นจำนวนเต็มบกวน่ะครับ"
  utter_default:
    - text: "ขออภัย ผมไม่เข้าใจครับ"
  utter_greet:
    - text: "สวัสดีครับ ผมคือ candybot โปรแกรมขายลูกอมสามสี"
  utter_show_colors:
    - text: "มีสีแดง, สีเขียว, และสีน้ำเงินครับ รับสีไหนดีครับ?"
  utter_show_prices:
    - text: "ขายปลีกเม็ดละ 50 สตางค์ ขายส่ง 12 เม็ดขึ้นไป ตกเม็ดล่ะ 1 สลึงครับ"
  utter_thk_you:
    - text: "ขอบคุณที่สละเวลาครับ"
  utter_slots_values:
    - text: "I got your order {color}"
  utter_list_colors:
    - text: "db colors are {COLOR_LIST}"
  utter_list_prices:
    - text: "db prices are {PRICE_LIST}"

actions:
- utter_greet
- utter_noworries
- utter_show_colors
- utter_show_prices
- utter_list_colors
- utter_list_prices
- action_list_colors
- action_list_pricing

forms:
  - candy_form
```

`actions.py`
```python
from typing import Dict, List, Text

from rasa_core_sdk import Action, Tracker
from rasa_core_sdk.events import SlotSet
from rasa_core_sdk.forms import FormAction

class CandyForm(FormAction):
    def name(self):
        return 'candy_form'

    @staticmethod
    def required_slots(tracker: Tracker) -> List[Text]:
        return ['color']

    def slot_mappings(self):
        return {
            'color': [self.from_entity(entity='color',
                                       not_intent=['chitchat', 'bargain']),
                      self.from_entity(entity='color',
                                       intent='inform',
                                       not_intent=['chitchat', 'bargain'])]
        }

    def submit(self, dispatcher, tracker, domain) -> List[Dict]:
        dispatcher.utter_template('utter_submit', tracker)
```

directories
```bash
.
├── Makefile
├── README.md
├── __init__.py
├── __pycache__
│   ├── actions.cpython-36.pyc
│   └── sentiment.cpython-36.pyc
├── actions.py
├── data
│   ├── nlu.md
│   └── stories.md
├── domain.yml
├── endpoints.yml
├── models
│   └── nlu
│       └── current
│           ├── checkpoint
│           ├── crf_model.pkl
│           ├── intent_classifier_tensorflow_embedding.ckpt.data-00000-of-00001
│           ├── intent_classifier_tensorflow_embedding.ckpt.index
│           ├── intent_classifier_tensorflow_embedding.ckpt.meta
│           ├── intent_classifier_tensorflow_embedding_encoded_all_intents.pkl
│           ├── intent_classifier_tensorflow_embedding_inv_intent_dict.pkl
│           ├── intent_featurizer_count_vectors.pkl
│           ├── metadata.json
│           └── training_data.json
├── nlu_tensorflow.yml
├── rasa_core.log
├── sentiment.py
└── story_graph.dot

5 directories, 24 files
```

`Makefile`
```bash
help:
	@echo "    train-core"
	@echo "        Train a dialogue model using Rasa core."
	@echo "    run-core"
	@echo "        Spin up the core server on the command line"
	@echo "    run-actions"
	@echo "        Spin up the action server"
	@echo "    run"
	@echo "        Spin up both core and the action server"
	@echo "    visualize"
	@echo "        Show your stories as a graph"


train-core:
	python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --debug

run-core:
	python -m rasa_core.run --core models/dialogue --nlu models/nlu/current --debug --endpoints endpoints.yml

run-actions:
	python -m rasa_core_sdk.endpoint --actions actions

run:
	make run-actions&
	make run-core

train-interactive:
	python -m rasa_core.train interactive -s data/stories.md -d domain.yml -o models/dialogue --debug   --nlu models/nlu/current --endpoints endpoints.yml

visualize:
	python -m rasa_core.visualize -s data/stories.md -d domain.yml -o story_graph.html

train-nlu:
	python -m rasa_nlu.train -c nlu_tensorflow.yml --fixed_model_name current --data data/nlu.md -o models --project nlu --verbose
```
