### ISSUE TITLE
How to extract entities when using multi intent pipeline?

### ISSUE THREAD

**Issue by Junitinn** [RasaHQ/rasa_nlu#2947]
Rasa Core version: 0.11.1
Python version: 2.7.10
Operating system (windows, osx, ...): macOS

**Issue**: Bot not able to recognize entities when using multi intent pipeline.

Hello everyone, 

I have got a pretty intelligent bot able to recognize entities, intends and reply back properly. I worked with this config.json

```yaml
{
  "pipeline":"tensorflow_embedding",
  "path":"./models/nlu",
  "data":"./data/data.json"
}   
```

But then I found this tutorial http://blog.rasa.com/how-to-handle-multiple-intents-per-input-using-rasa-nlu-tensorflow-pipeline/ about multi intend and they recommend to use this config.yml. 

**Content of domain file** (if used & relevant):
```yaml
pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

I managed to get my bot working with this one but it is not able to extract entities anymore. Any suggestion would be appreciated.
