### ISSUE TITLE
Categorical slot fails when value is either yes or no

### ISSUE THREAD

**Issue by Husamx** [RasaHQ/rasa_nlu#2952]
**Rasa Core version**: 0.13.1

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows

**Issue**: WARNING: rasa_core.slots:Categorical slot 'slot_name' is set to a value ('yes') that is not specified in the domain. Value will be ignored and the slot will behave as if no value is set. Make sure to add all values a categorical slot should store to the domain.

Training fails when in the domain a categorical slot is given the values yes/no 

domain.yml: 

```
slot_name: 
    type: categorical 
    values:
    - yes 
    - no

```
When checking the generated domain files in the model's directory, I noticed that yes and no were saved as 'true' and 'false'

```
slot_name:
    auto_fill: true
    initial_value: null
    type: rasa_core.slots.CategoricalSlot
    values:
    - 'true'
    - 'false'
```

to fix this i had to wrap the slot values with quotes (in domain.yml) 

```
slot_name:
    type: categorical
    values:
    - 'yes'
    - 'no'
```

Since the documentation does not mention this specific case, I think it should be worth noting.

**Content of domain file** (if used & relevant):
```yaml

```
