### ISSUE TITLE
No matching distribution found for robot.libraries when launching action server

### ISSUE THREAD

**Issue by antoinecomp** [RasaHQ/rasa_nlu#2985]
**Rasa Core version**:

rasa-core                 0.12.0
rasa-core-sdk             0.12.1

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Windows10

**Issue**:

When launching a an action server for [a Rasa chatbot](https://github.com/NaThemis/ChatbotRASA_Room-reservation) by running `python -m rasa_core_sdk.endpoint --actions actions` it told me there were a `ModuleNotFoundError` for a module named `'robot.libraries'` even if I aready had dowloaded `robot` module:

    (chaenv36) PS C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation> python -m rasa_core_sdk.endpoint --actions actions
    python : INFO:__main__:Starting action endpoint server...
    At line:1 char:1
    + python -m rasa_core_sdk.endpoint --actions actions
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (INFO:__main__:S...point server...:String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
     
    ERROR:rasa_core_sdk.executor:Failed to register package 'actions'.
    Traceback (most recent call last):
      File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core_sdk\
    executor.py", line 144, in register_package
        self._import_submodules(package)
      File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\chaenv36\lib\site-packages\rasa_core_sdk\
    executor.py", line 131, in _import_submodules
        package = importlib.import_module(package)
      File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\actions.py", line 8, in <module>
        from booking import make_a_booking
      File "C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation\booking.py", line 7, in <module>
        from robot.libraries.DateTime import convert_time
    ModuleNotFoundError: No module named 'robot.libraries'
    INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)

 Yet when downloading `robot.libraries` it said there were no matching distribution found for robot.libraries :

    (chaenv36) PS C:\Users\antoi\Documents\Programming\Nathalie\7_2_2019\ChatbotRASA_Room-reservation> pip install robot.libraries
    Collecting robot.libraries
    pip :   Could not find a version that satisfies the requirement robot.libraries (from versions: )
    At line:1 char:1
    + pip install robot.libraries
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (  Could not fin...rom versions: ):String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
     
    No matching distribution found for robot.libraries

**Content of domain file** (if used & relevant):
```yaml
slots:
  name_room:
    type: text
  day:
    type: text
  hour_start:
    type: text
  duration:
    type: text

intents:
 - greet
 - goodbye
 - book_room

entities:
 - name_room
 - day
 - hour_start
 - duration

templates:
  utter_greet:
  - text: "Hey ! How can I help?"
  - text: "Hi ! How can I help?"
  - text: "YAZZZZZZAAAAA ! ...  How can I help you ?"
  utter_goodbye:
  - text: "Bye :("
  - text: "Talk to you later"
  utter_ask_room:
    - 'In what room?'
  utter_ask_day:
    - 'What day?'
  utter_ask_hour_start:
    - 'What time do you want to start your meeting?'
  utter_ask_duration:
    - 'How long would you need ?'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_room
 - utter_ask_day
 - utter_ask_hour_start
 - utter_ask_duration
 - action_room
```
