### ISSUE TITLE
Unexpected answer crashes FormAction

### ISSUE THREAD

**Issue by lauraperge** [RasaHQ/rasa_nlu#2991]
**Rasa Core version**: 0.13.2

**Python version**: 3.6.8

**Operating system** (windows, osx, ...):Windows 10, 64

**Issue**: 

I have a FormAction **changepassword** and I have a (simplified) conversation as follows:

```
*greet
    - utter_greet
* changepassword{"email": "example1@mail.com"}
    - SOME VALIDATION
    - slot{"email": "example1@mail.com"}
    - form{"name": "changepassword_form"}
    - slot{"requested_slot": "password"}
* form: newpassword
    - form: changepassword_form
    - slot{"password": "Gh&gjdf445415"}
    - slot{"requested_slot": "confirmpassword"}
* form: provideemail{"email": "Example2@mail.com"}
    - slot{"email": "Example2@mail.com"}
    - form: changepassword_form
```
So, the bot gets an unexpected answer from the user, because it awaits a **confirmrequest** or **denyrequest** but it receives instead a new email address for whatever reason (*E.g.: the user wants to change the email address last minute*).

I overwrote the **request_next_slot()** in actions.py  to make sure that the email address exist in a DB, so what I would wait is that the form gets deactivated, validation happens and then the form carries on (implemented in custom action). Also, I have added some unhappy stories resembling this kind of path to give training examples.

*change in actions.py:*
```python
def request_next_slot(self,
                          dispatcher,  # type: CollectingDispatcher
                          tracker,  # type: Tracker
                          domain  # type: Dict[Text, Any]
                          ):
        # type: (...) -> Optional[List[Dict]]
        """Request the next slot and utter template if needed,
            else return None"""
        
         ## Check if validation has been done
        if ((tracker.get_slot('VALID') != tracker.get_slot('email')) & (tracker.get_slot('email')!=None)):
            ## if not then VALIDATE
            return [self._deactivate(), FollowupAction('action_validateEmail')]
```

**The issue is that when the user answers with an email address, the bot tries to extract the *confirmrequest* slot, it fails to do so and the following error occurs:

**LOG - with some of what happens just before**:

```txt
Action 'action_validateEmail' ended with events '['SlotSet(key: VALID, value: example1@example.com)', 'SlotSet(key: email, value: example1@example.com)', 'SlotSet(key: managestatus, value: Locked)', 'SlotSet(key: userid, value: 5229)', 'FollowupAction(action: changepassword_form)']'
Predicted next action 'changepassword_form' with prob 1.00.
Calling action endpoint to run action 'changepassword_form'.
Action 'changepassword_form' ended with events '['Form(changepassword_form)', 'SlotSet(key: requested_slot, value: password)']'
Bot utterance 'BotUttered(text: Please enter the new password! (Only the characters of the password.), data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
There is an active form 'changepassword_form'
Current tracker state [{'prev_action_validateEmail': 1.0, 'intent_greet': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_utter_unclear': 1.0}, {'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'prev_action_validateEmail': 1.0, 'intent_changepassword': 1.0}]
There is no memorised next action
Predicted next action using policy_0_FormPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'Gh&gjdf445415' with intent '{'name': 'newpassword', 'confidence': 0.6084855756337023}' and entities '[]'
Logged UserUtterance - tracker now has 25 events
Current slot values:
	VALID: example1@example.com
	confirmmanage: None
	confirmpassword: None
	email: example1@example.com
	managestatus: Locked
	password: None
	requested_slot: password
	userid: 5229
There is an active form 'changepassword_form'
Current tracker state [{'prev_action_validateEmail': 1.0, 'intent_greet': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_utter_unclear': 1.0}, {'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'prev_action_validateEmail': 1.0, 'intent_changepassword': 1.0}]
There is no memorised next action
Predicted next action using policy_0_FormPolicy
Predicted next action 'changepassword_form' with prob 1.00.
Calling action endpoint to run action 'changepassword_form'.
Action 'changepassword_form' ended with events '['SlotSet(key: password, value: Gh&gjdf445415)', 'SlotSet(key: requested_slot, value: confirmpassword)']'
Bot utterance 'BotUttered(text: Do you confirm changing the password to Gh&gjdf445415 for user example1@example.com?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
There is an active form 'changepassword_form'
Current tracker state [{'prev_action_validateEmail': 1.0, 'intent_greet': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_utter_unclear': 1.0}, {'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'prev_action_validateEmail': 1.0, 'intent_changepassword': 1.0}]
There is no memorised next action
Predicted next action using policy_0_FormPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'yes, for example@mail.com' with intent '{'name': 'provideemail', 'confidence': 0.21480617979668268}' and entities '[{'start': 9, 'end': 25, 'value': 'example@mail.com', 'entity': 'email', 'confidence': 0.9961804017668956, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 32 events
Current slot values:
	VALID: example1@example.com
	confirmmanage: None
	confirmpassword: None
	email: example@mail.com
	managestatus: Locked
	password: Gh&gjdf445415
	requested_slot: confirmpassword
	userid: 5229
There is an active form 'changepassword_form'
Current tracker state [{'prev_action_validateEmail': 1.0, 'intent_greet': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'entity_email': 1.0, 'intent_changepassword': 1.0, 'prev_utter_unclear': 1.0}, {'intent_changepassword': 1.0, 'prev_action_listen': 1.0}, {'prev_action_validateEmail': 1.0, 'intent_changepassword': 1.0}]
There is no memorised next action
NLU confidence 0.21480617979668268 is lower than NLU threshold 0.3.
Predicted next action using policy_0_FormPolicy
Predicted next action 'changepassword_form' with prob 1.00.
Calling action endpoint to run action 'changepassword_form'.
Encountered an exception while running action 'changepassword_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
[{'event': 'form', 'name': None, 'timestamp': None}, {'event': 'slot', 'name': 'requested_slot', 'timestamp': None, 'value': None}] is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions/

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    [{'event': 'form', 'name': None, 'timestamp': None},
     {'event': 'slot',
      'name': 'requested_slot',
      'timestamp': None,
      'value': None}]
Traceback (most recent call last):
  File "LOCALPATH\Anaconda3\lib\site-packages\rasa_core\processor.py", line 346, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "LOCALPATH\Anaconda3\lib\site-packages\rasa_core\actions\action.py", line 344, in run
    self._validate_action_result(response_data)
  File "LOCALPATH\Anaconda3\lib\site-packages\rasa_core\actions\action.py", line 279, in _validate_action_result
    raise e
  File "LOCALPATH\Anaconda3\lib\site-packages\rasa_core\actions\action.py", line 271, in _validate_action_result
    validate(result, self.action_response_format_spec())
  File "LOCALPATH\Anaconda3\lib\site-packages\jsonschema\validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "LOCALPATH\Anaconda3\lib\site-packages\jsonschema\validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: [{'event': 'form', 'name': None, 'timestamp': None}, {'event': 'slot', 'name': 'requested_slot', 'timestamp': None, 'value': None}] is not of type 'object'. Failed to validate Action server response from API, make sure your response from the Action endpoint is valid. For more information about the format visit https://rasa.com/docs/core/customactions/

Failed validating 'type' in schema['properties']['events']['items']:
    {'properties': {'event': {'type': 'string'}}, 'type': 'object'}

On instance['events'][1]:
    [{'event': 'form', 'name': None, 'timestamp': None},
     {'event': 'slot',
      'name': 'requested_slot',
      'timestamp': None,
      'value': None}]
Action 'changepassword_form' ended with events '[]'
There is an active form 'changepassword_form'
```

**Content of domain file** (if used & relevant):
```yaml
%YAML 1.1
---
actions:
- action_validateEmail
- utter_managestopped
- utter_confirmerror
- utter_usernotfound
- utter_confirmpwchange
- utter_wrong_password
- utter_confirmmanage
- utter_unclear
- utter_ask_email
- utter_goodbye
- action_reportmanage
- utter_ask_confirmmanage
- utter_foundandproceed
- utter_ok
- utter_ask_password
- utter_ask_confirmpassword
- action_exp
- utter_greet
- utter_error
- utter_pwstopped
- utter_stop
entities:
- email
forms:
- changepassword_form
- lockunlock_form
intents:
- confirmrequest
- wait
- changepassword
- lockunlock
- provideemail
- goodbye
- newpassword
- greet
- thankyou
- denyrequest
- stop
slots:
  VALID:
    type: unfeaturized
  confirmmanage:
    auto_fill: false
    type: unfeaturized
  confirmpassword:
    auto_fill: false
    type: unfeaturized
  email:
    type: unfeaturized
  managestatus:
    auto_fill: false
    type: unfeaturized
  password:
    auto_fill: false
    type: unfeaturized
  requested_slot:
    type: unfeaturized
  userid:
    auto_fill: false
    type: unfeaturized
templates:
  utter_ask_confirmmanage:
  - text: Do you confirm changing the account status of the user {email} from {managestatus}?
  utter_ask_confirmpassword:
  - text: Do you confirm changing the password to {password} for user {email}?
  utter_ask_email:
  - text: What is the email address of the user?
  utter_ask_password:
  - text: Please type in a new password! (Only the characters of the password.)
  utter_confirmerror:
  - text: I am not sure if you confirmed the change or not, please try again.
  utter_confirmmanage:
  - text: The account for the user {email} is now {managestatus}.
  utter_confirmpwchange:
  - text: The password for user {email} is now changed to {password}.
  utter_error:
  - text: Something went wrong with the connection. Please try again.
  utter_foundandproceed:
  - text: User found, how should I proceed?
  utter_goodbye:
  - text: Have a nice day!
  - text: Have a great day! :)
  utter_greet:
  - text: Hey! How may I help you?
  utter_managestopped:
  - text: The account for the user {email} is not changed as the change was not confirmed.
  utter_ok:
  - text: Okay, I'll leave the request here, please answer when you are ready.
  utter_pwstopped:
  - text: Password change was not confirmed, therefore the password did not change.
  utter_unclear:
  - text: I am not sure what you are aiming for.
  utter_usernotfound:
  - text: There is no user with the given email address. Please try again.
  utter_wrong_password:
  - text: "The password you gave is invalid. Please enter a new password.
  utter_stop:
  - text: Okay, I'll stop now, and we can restart our conversation.

```

Please let me know how to solve this error
