### ISSUE TITLE
TypeError: Object of type generator is not JSON serializable

### ISSUE THREAD

**Issue by bamania8** [RasaHQ/rasa_nlu#2997]
**Rasa Core version**:0.12.4

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...):Ubuntu 18.04.1 LTS

**Issue**:
___________________________________________________________________________________
? What is the next action of the bot?  0.00 action_my_custom_action
Thanks! The bot will now run action_my_custom_action.

DEBUG:rasa_core_sdk.executor:Received request to run 'action_my_custom_action'
DEBUG:rasa_core_sdk.executor:Successfully ran 'action_my_custom_action'
ERROR:flask.app:Exception on /webhook [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/rasa_core_sdk/endpoint.py", line 91, in webhook
    return jsonify(response)
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 373, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/dist-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 268, in default
    o.__class__.__name__)
TypeError: Object of type generator is not JSON serializable
___________________________________________________________________________________

**Content of domain file** (if used & relevant):
```yaml

slots:
  room:
    type: text
  persons:
    type: list
  duration:
    type: text
intents:
  - Welcome
  - BookingRequest
  - Stayduration
  - rooms
  - persons
entities:
  - rooms
  - persons
  - duration
action_factory: remote
actions:
  - utter_greet
  - utter_room
  - utter_person
  - utter_duration
  - utter_confirm
  - action_my_custom_action
templates:
  utter_greet:
    - text: Utter Welcome to Hotel Mountain View
  utter_room:
    - text: num of rooms?
  utter_person:
    - text: num of people
  utter_duration:
    - text: stay duration?
  utter_confirm:
    - text: Booking Done

```
