### ISSUE TITLE
pymongo.errors.OperationFailure: Authentication failed when trying to run rasa_core.run

### ISSUE THREAD

**Issue by Arghya999** [RasaHQ/rasa_nlu#3002]
**Rasa Core version**:  0.12.3

**Python version**: Python 3.6.8

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**:I am getting “pymongo.errors.OperationFailure: Authentication failed.” when trying to run rasa_core.run

a)Command used :- python -m rasa_core.run -d models/dialogue -u m odels/nlu/default/current --endpoints endpoints.yml --debug --enable_api

b)configuration in bot logic(rasa core) for MongoTrackerStore :-

global_db_mg = MongoTrackerStore(domain,host=‘mongodb://127.0.0.1:27017’, db=‘rasa’, username=None,password=None, collection=‘conversations’,event_broker=None)

c)Content of mongod.conf

```yaml

# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1


#processManagement:

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:


d)Content of endpoints.yml
action_endpoint:
  url: "http://localhost:5055/webhook"
tracker_store:
  store_type: mongod
  url: mongodb://127.0.0.1:27017
  db: rasa
  username: None
  password: None
```

e) service mongod status :

● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/lib/systemd/system/mongod.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-02-20 18:26:01 IST; 22h ago
     Docs: https://docs.mongodb.org/manual
 Main PID: 22505 (mongod)
    Tasks: 20
   Memory: 58.2M
      CPU: 5min 59.248s
   CGroup: /system.slice/mongod.service
           └─22505 /usr/bin/mongod --quiet --config /etc/mongod.conf

**Content of domain file** (if used & relevant):
```yaml

```
