### ISSUE TITLE
NameError: Cannot access action '', as that name is not a registered action for this domain. Available actions ar

### ISSUE THREAD

**Issue by MaulishShah** [RasaHQ/rasa_nlu#3027]
**Rasa Core version**: 13.3

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): ubuntu

**Issue**:
NameError: Cannot access action '', as that name is not a registered action for this domain. Available actions are:
I'm added all the actions in the yml file but all time it gives me above type of error 

**Content of domain file** (if used & relevant):
```yaml
slots:
  information:
    type: text

intents:
  - greet
  - bye
  - information
  - default

entities:
  - details
templates:
  utter_greet:
    - 'hello how can i help you!!!'
  utter_bye:
    - 'GoodBye'
  utter_ask_information:
    - 'what type of information you wants'

actions:
  - utter_greet
  - utter_bye
  - utter_ask_information
  - utter_details

```
