### ISSUE TITLE
Error when trying to integrate chatbot with slack.

### ISSUE THREAD

**Issue by Swarnalathaa** [RasaHQ/rasa_nlu#3051]
**Rasa Core version**: 0.13.3

**Python version**: 3.6(64 bit)

**Operating system** (windows, osx, ...):windows

**Issue**:
My bot when integrated with slack works fine with text messages but getting 404 error when i click the button.
Interactive component url:
http://43a65818.ngrok.io/wehooks/slack/webhook

**Content of domain file** (if used & relevant):
```yaml
slots:
  user_request:
    type: text
  user_type:
    type: text
  user_choice:
    type: text
  name:
    type: list

intents:
 - greet
 - goodbye
 - inform
 - affirm
 - deny
 - search
 - searchtype
 - startfresh


entities:
 - user_request
 - user_type
 - user_choice
 - name

templates: 
  utter_info: 
    - "what news do you want?"
  utter_moreinfo: 
    - 
      buttons: 
        - 
          payload: "/affirm"
          title: Yes, for sure
        - 
          payload: "/deny"
          title: No, thank you
        - 
          payload: "/startfresh"
          title: Start Fresh 
      text: "Do you want to know anything more?"
  utter_satisfy:
    - 
      buttons: 
        - 
          payload: "/affirm"
          title: Yes, for sure
        - 
          payload: "/deny"
          title: No, thank you
        - 
          payload: "/startfresh"
          title: Start Fresh
      text: "Are you happy with what we have provided?"
  utter_happy:
    - "We are happy to know that"
  utter_sad:
    - "Sorry, we will improve our service"
  utter_again:
    - 
      buttons: 
        - 
          payload: '/search{"user_request":"news"}'
          title: News
        - 
          payload: '/search{"user_request":"reports"}'
          title: Reports
        - 
          payload: '/search{"user_request":"both"}'
          title: Both
        - 
          payload: "/startfresh"
          title: Start Fresh
      text: "Please select one"

  utter_goodbye: 
    - "Talk to you later."
    - "Bye bye :("
  utter_greet: 
    - 
      buttons: 
        - 
          payload: '/search{"user_request":"news"}'
          title: News
        - 
          payload: '/search{"user_request":"reports"}'
          title: Reports
        - 
          payload: '/search{"user_request":"both"}'
          title: Both
        - 
          payload: "/startfresh"
          title: Start Fesh
      text: "Hello! I am a bot and I can provide you some interesting news and reports.Select one of the following option"
  utter_type: 
    - 
      buttons: 
        - 
          payload: '/searchtype{"user_type":"title"}'
          title: Title
        - 
          payload: '/searchtype{"user_type":"tag"}'
          title: Tag
        - 
          payload: '/searchtype{"user_type":"text"}'
          title: Text
        - 
          payload: "/startfresh"
          title: Start Fresh
      text: "How do you want the search to be based on?"
  utter_typeagain: 
    - 
      buttons: 
        - 
          payload: '/searchtype{"user_type":"title"}'
          title: Title
        - 
          payload: '/searchtype{"user_type":"tag"}'
          title: Tag
        - 
          payload: '/searchtype{"user_type":"text"}'
          title: Text
        - 
          payload: "/startfresh"
          title: Start Fresh
      text: "Select one"
  utter_typeask:
    - 
      buttons: 
        - 
          payload: "/affirm"
          title: Yes, for sure
        - 
          payload: "/deny"
          title: No, thank you
        - 
          payload: "/startfresh"
          title: Start Fresh
      text: "Do you want to search again based on different criteria?"
  utter_continue:
    - 
      buttons: 
        - 
          payload: "/affirm"
          title: Yes, for sure
        - 
          payload: "/deny"
          title: No, thank you
      text: "Do you want to start again?"



actions:
 - utter_greet
 - utter_goodbye
 - utter_info
 - utter_again
 - utter_sad
 - utter_happy
 - utter_satisfy
 - utter_moreinfo
 - utter_type
 - utter_typeagain
 - utter_typeask
 - utter_continue
 - action_news
 - action_reset
 - action_restart
```
here is the screenshot of my error
![log](https://user-images.githubusercontent.com/34007219/54198461-d5a3b580-44c6-11e9-9336-9ae6ee94edb4.PNG)
