### ISSUE TITLE
Filling slot in Form Actions.

### ISSUE THREAD

**Issue by josse995** [RasaHQ/rasa_nlu#3082]
**Rasa Core version**:
0.13.2
**Rasa SDK version**:
0.12.2
**Rasa NLU version**:
0.14.4
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Windows
**Issue**: Filling slot in Form Actions.

Hello.
We are trying to use form actions for our bot, and we have the next problem.
When we try to get an entity extracted with ner-spacy, the slot isn't filled using form actions.
Here are our formactions code:
```
class SaludosForm(FormAction):
    def name(self):
        return "form_saludos"

    @staticmethod
    def required_slots(tracker: Tracker) -> List[Text]:
        return ["persona"]

    def slot_mappings(self):
        print("He entrado")
        return {"persona": [self.from_entity(entity="PER", intent="me_llamo"),
                            self.from_entity(entity="per", intent="me_llamo"),
                            self.from_entity(entity="persona", intent="me_llamo")]}

    def validate(self,
                 dispatcher: CollectingDispatcher,
                 tracker: Tracker,
                 domain: Dict[Text, Any]) -> List[Dict]:
        slot_values = self.extract_other_slots(dispatcher, tracker, domain)
        slot_to_fill = tracker.get_slot(REQUESTED_SLOT)

        if slot_to_fill:
            slot_values.update(self.extract_requested_slot(dispatcher, tracker, domain))

        else:
            dispatcher.utter_message("Validation failed")

        return [SlotSet(slot, value) for slot, value in slot_values.items()]

    def submit(self,
               dispatcher: CollectingDispatcher,
               tracker: Tracker,
               domain: Dict[Text, Any]) -> List[Dict]:
        persona = tracker.get_slot('persona')
        if persona is not None:
            dispatcher.utter_template("utter_saludo_nombre", tracker)
            return []
        else:
            dispatcher.utter_template("utter_saludo", tracker)
            return []
```
**Content of domain file** (if used & relevant):
```yaml

%YAML 1.1
---
actions:
- utter_saludos_nombre
...
...
entities:
- PER
- persona
intents:
- me_llamo
- saludos
slots:
   ..
   ..
   ..
  persona:
    auto_fill: false
    type: unfeaturized
templates:
...
...
...
forms:
   -form_saludos

```
