### ISSUE TITLE
 Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. 

### ISSUE THREAD

**Issue by HovHak** [RasaHQ/rasa_nlu#3084]
**Rasa Core version**: 13.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:i have tried to configure the rasa policy to resolve this but no effect so far i am keep getting this error, please help.

 Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead. More info https://rasa.com/docs/core/migrations.html

**Content of domain file** (if used & relevant):
```yaml
intents:
    - schedule_meeting
    - search_for_meeting
    - greet

entities:
    - meeting
    - time

slots:
    size:
         type: text
    toppings:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_ask_meeting_day:
        - 'What time would you like me to schedule your meeting?'
    utter_ask_meeting_time:
        - 'What time would you like me to schedule your meeting?'
    utter_get_meeting_time_place:
        - 'here are your meetings for today'
actions:
    - utter_greet
    - utter_ask_meeting_time
    - utter_ask_meeting_day
    - utter_get_meeting_time_place
    - actions.ActionShowMeeting
```

**Content of dialogue_model.py **
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals


import logging
from rasa_core.agent import Agent
from rasa_core.domain import Domain
from rasa_core.featurizers import MaxHistoryTrackerFeaturizer, BinarySingleStateFeaturizer
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    dialog_training_data_file = './data/stories.md'
    path_to_model = './models/dialogue'
    # domain = Domain()
    featurizer = MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer(), max_history=5)
    agent = Agent('chat_domain.yml',  policies=[MemoizationPolicy(max_history=5),
                        KerasPolicy(featurizer)])

    agent.train(
        dialog_training_data_file,
        augmentation_factor=50,
        max_history=2,
        epochs=500,
        batch_size=10,
        validation_split=0.2)
    agent.persist(path_to_model)
```
