### ISSUE TITLE
How to restart a new session after the first conversation completion

### ISSUE THREAD

**Issue by zxsimple** [RasaHQ/rasa_nlu#3103]
**Rasa Core version**:
0.8.0
**Python version**: 
3.5
**Operating system** (windows, osx, ...):
Windows 64bit
**Issue**:

It performs perfect as the story template, but after the completion of the last response, a new conversation never start no mater whatever I input.

**Content of domain file** (if used & relevant):
```yaml
slots:
  bg:
    type: text
  region:
    type: text
  year:
    type: text
  period:
    type: text
  indicator:
    type: text

intents:
  - greet
  - query_finance
  - inform

entities:
 - year
 - period
 - region
 - indicator

templates:
  utter_greet:
    - "Hi"
  utter_ask_indicator:
    - "What indicator do you want?"
  utter_ask_region:
    - "Which region"
  utter_ask_time:
    - "When"
  utter_resp_indicator:
    - "Indicator queried {year}{period}{region}{indicator}is 1243"
  utter_goodbye:
    - "Bey~"

actions:
  - utter_greet
  - utter_goodbye
  - utter_ask_indicator
  - utter_ask_region
  - utter_ask_time
  - utter_resp_indicator
  - fin_bot.ActionIndicatorSearch
```
**Content of story file** (if used & relevant):
```## Generated Story 001
* greet
  - utter_greet
  - utter_ask_indicator
* query_finance{"indicator": "Sales"}
  - slot{"indicator": "Sales"}
  - utter_ask_region
* inform{"region": "Asia Pacific"}
  - slot{"region": "Asia Pacific"}
  - utter_ask_time
* inform{"period": "Feb."}
  - slot{"period": "Feb."}
  - action_indicator_search
  - utter_goodbye
```
