### ISSUE TITLE
Dialogue training is appending wrong stories to stories.md for no reason

### ISSUE THREAD

**Issue by NicoLivesey** [RasaHQ/rasa_nlu#3107]
**Rasa Core version**: 0.8.6

**Python version**:  3.6.3

**Operating system** (windows, osx, ...): Raspbian

**Issue**: Hello everyone, I am currently working on a little project and adapting the supervised learning tutorial, everything work well but one thing is really annoying. When I train the dialogue part (see below) I always find new irrelevant stories appearing in the stories.md.

Here's the training code (relatively basic):

```py
import logging
from rasa_core.agent import Agent
from rasa_core.domain import Domain
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    dialog_training_data_file = 'stories.md'
    path_to_model = './models/dialogue'
    # domain = Domain()
    agent = Agent('chat_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])

   agent.train(
        dialog_training_data_file,
        augmentation_factor=50,
        max_history=2,
        epochs=500,
        batch_size=10,
        validation_split=0.2)
    agent.persist(path_to_model)
```

Here's the stories appearing:

```
## Generated Story -5043732597440786429
* bye
    - utter_bye
    - export
## Generated Story 204787383519891157
    - utter_bye
    - export
## Generated Story -5043732597440786429
* bye
    - utter_bye
    - export
## Generated Story 204787383519891157
    - utter_bye
    - export
```

Everytime I want to do a new train I got this like 10 times bigger in stories.md and I have to remove it.

Is it a known bug?

Thank you for the help and for the amazing work!

**Content of domain file** (if used & relevant):
```yml
intents:
    - greet
    - mood
    - who
    - bye
    - contract
    - tips
    - compare
entities:
    - type
    - who
slots:
    type:
        type: text
    who:
        type: text
templates:
    utter_default:
        - 'some string'
    utter_greet:
        - 'some string'
    utter_mood:
        - 'some string'
    utter_who:
        - 'some string'
    utter_bye:
        - 'some string'
    utter_ask_tips_type:
        - 'some string'
    utter_ask_compare_type:
        - 'some string'
    utter_ask_compare_who:
        - 'some string'

actions:
    - utter_default
    - utter_greet
    - utter_who
    - utter_mood
    - utter_bye
    - bot.ActionGetContract
    - bot.ActionGetTips
    - utter_ask_tips_type
    - bot.ActionGetCompare
    - utter_ask_compare_type
    - utter_ask_compare_who
```
