### ISSUE TITLE
Form action does not fill requested slot

### ISSUE THREAD

**Issue by GiacomoZara** [RasaHQ/rasa_nlu#3116]
**Rasa Core version**: 0.12.3

**Rasa NLU version**: 0.13.8

**Rasa Core SDK version**: 0.12.1

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:

I am stuck at the following part of my stories

```
## Manually created story
> checked_answered_high_status_change_score
    - slot{"area_intervento": "aderenza terapia farmacologica"}
    - utter_introduci_health_literacy
    - utter_chiedi_atf_1
    - atf_form
    - form{"name": "atf_form"}
    - utter_ringrazia
```

The dialogue correctly arrives to this point of the story. This is the code of the form action `atf_form`:

```python
class AtfForm(FormAction):

    def name(self):
        return "atf_form"

    @staticmethod
    def required_slots(tracker):
        return ["aderenza_terapia_farmacologica_uno"]

    def slot_mapping(self):
        return {"aderenza_terapia_farmacologica_uno": [self.from_entity(entity = "risposta_health_literacy", intent = "rispondi_health_literacy")]}

    def validate(self, dispatcher, tracker, domain):
        acceptable_values = ['vero', 'falso', 'non so']

        slot_values = self.extract_other_slots(dispatcher, tracker, domain)
        slot_to_fill = tracker.get_slot("aderenza_terapia_farmacologica_uno")

        print("Slot to fill: " + str(slot_to_fill))
        print("Slot values: " + str(slot_values))

        if slot_to_fill:
            slot_values.update(self.extract_requested_slot(dispatcher, tracker, domain))

            if len(slot_values.items()) == 0:
                raise ActionExecutionRejection(self.name(),
                                               "Failed to validate slot {0} "
                                               "with action {1}"
                                               "".format(slot_to_fill,
                                                         self.name()))
        else:
            dispatcher.utter_message("Validation failed")

        for slot, value in slot_values.items():
            if slot == 'aderenza_terapia_farmacologica_uno':
                if value not in acceptable_values:
                    dispatcher.utter_message("Area errata: per favore riprova")
                    slot_values[slot] = None
            else:
                dispatcher.utter_template("utter_fallback", tracker)

        return [SlotSet(slot, value) for slot, value in slot_values.items()]

    def submit(self, dispatcher, tracker, domain):
        return []
```

The problem is that, for some reason, the mapping fails: despite the debug logging tells me that the intent and entities are correctly recognized, the slot `"aderenza_terapia_farmacologica_uno"` doesn't get filled and, therefore, the bot utters: "Validation failed". Here i include the relevant part of the action server debugging:

```
DEBUG:rasa_core_sdk.executor:Received request to run 'atf_form'
DEBUG:rasa_core_sdk.forms:There is no active form
DEBUG:rasa_core_sdk.forms:Activated the form 'atf_form'
DEBUG:rasa_core_sdk.forms:Skipping validation
DEBUG:rasa_core_sdk.forms:Request next slot 'aderenza_terapia_farmacologica_uno'
DEBUG:rasa_core_sdk.executor:Successfully ran 'atf_form'
127.0.0.1 - - [2018-12-05 09:06:49] "POST /webhook HTTP/1.1" 200 383 0.001181
DEBUG:rasa_core_sdk.executor:Received request to run 'atf_form'
DEBUG:rasa_core_sdk.forms:The form '{'name': 'atf_form', 'validate': True, 'rejected': False}' is active
DEBUG:rasa_core_sdk.forms:Validating user input '{'intent': {'name': 'rispondi_health_literacy', 'confidence': 0.9781476855278015}, 'entities': [{'start': 0, 'end': 4, 'value': 'vero', 'entity': 'risposta_health_literacy', 'confidence': 0.7666247797469885, 'extractor': 'ner_crf'}], 'intent_ranking': [{'name': 'rispondi_health_literacy', 'confidence': 0.9781476855278015}, {'name': 'inizia', 'confidence': 0.06422808766365051}, {'name': 'scegli_area_intervento', 'confidence': 0.0}, {'name': 'comunica_self_efficacy', 'confidence': 0.0}, {'name': 'afferma', 'confidence': 0.0}, {'name': 'input_numerico', 'confidence': 0.0}, {'name': 'nega', 'confidence': 0.0}], 'text': 'vero'}'
Slot to fill: None
Slot values: {}
DEBUG:rasa_core_sdk.forms:Request next slot 'aderenza_terapia_farmacologica_uno'
DEBUG:rasa_core_sdk.executor:Successfully ran 'atf_form'
127.0.0.1 - - [2018-12-05 09:06:58] "POST /webhook HTTP/1.1" 200 360 0.001361
```

**Content of domain file** (if used & relevant):
```yaml
##### SLOTS #####
slots:
  user_id:
    type: unfeaturized
  bot_name:
    type: unfeaturized
    initial_value: "Lisa"
  area_intervento:
    type: dialogue.dialogue_custom_slots.AreaInterventoSlot
  status_change_score:
    type: dialogue.dialogue_custom_slots.StatusChangeScoreSlot
  self_efficacy_score:
    type: dialogue.dialogue_custom_slots.SelfEfficacyScoreSlot
  aderenza_terapia_farmacologica_uno:
    type: dialogue.dialogue_custom_slots.AderenzaTerapiaFarmacologicaUnoSlot
  aderenza_terapia_farmacologica_due:
    type: dialogue.dialogue_custom_slots.AderenzaTerapiaFarmacologicaDueSlot
  alimentazione_1:
    type: unfeaturized
  alimentazione_2:
    type: unfeaturized
  alimentazione_3:
    type: unfeaturized
  alimentazione_4:
    type: unfeaturized
  alimentazione_5:
    type: unfeaturized
  attivita_fisica_1:
    type: unfeaturized
  attivita_fisica_2:
    type: unfeaturized
  controllo_glicemia_1:
    type: unfeaturized
  controllo_glicemia_2:
    type: unfeaturized
  controllo_glicemia_3:
    type: unfeaturized
  controllo_glicemia_4:
    type: unfeaturized


##### ENTITIES #####
entities:
  - numero
  - area_intervento
  - valore_self_efficacy
  - risposta_health_literacy


##### INTENTS #####
intents:
  - inizia
  - afferma
  - nega
  - input_numerico
  - scegli_area_intervento
  - comunica_self_efficacy
  - rispondi_health_literacy
  - None


##### TEMPLATES #####
templates:

    utter_benvenuto:
      - "Ciao {user_id}, il mio nome è {bot_name}, un'assistente virtuale che ti aiuterà a conoscere e gestire meglio il diabete, migliorando il tuo stile di vita"

    utter_chiedi_se_pronto:
      - "Per farlo, però, ho bisogno di conoscerti meglio. Sei pronto?"

    utter_perfetto:
      - "Perfetto, cominciamo!"
      - "Ottimo, cominciamo!"
      - "Fantastico, cominciamo!"

    utter_allora_ciao:
      - "Sarà per la prossima volta, a presto!"

    utter_ringrazia:
      - "Grazie"

    utter_fallback:
      - "Risposta non valida, per favore riprova"

    utter_valore_fuori_range:
      - "Il numero inserito è al di fuori dell'intervallo previsto, per favore riprova"

    utter_chiedi_area_intervento:
      - "Scegli quale di queste quattro aree comportamentali ti piacerebbe migliorare il tuo stile di vita: aderenza terapia farmacologica, alimentazione, attività fisica, controllo glicemia"

    utter_chiedi_livello_motivazione:
      - "Indica su scala 1-10 quanto ti senti in grado di cambiare il tuo comportamento nell'area {area_intervento}"

    utter_chiedi_self_efficacy:
      - "Quanto ti senti in grado di migliorare nell'area {area_intervento}, poco o molto?"

    utter_chiedi_atf_1:
      - "Un alto livello di zucchero nel sangue può essere causato da troppa insulina?"

    utter_chiedi_atf_2:
      - "Se ti fai l'insulina la mattina ma salti la colazione, la tua glicemia scenderà?"

    utter_chiedi_al_1:
      - "La dieta per persone diabetiche è una dieta salutare in generale?"

    utter_chiedi_al_2:
      - "Una porzione di pollo ha più carboidrati di una porzione di patate?"

    utter_chiedi_al_3:
      - "Il succo d'arancia ha più grassi del latte?"

    utter_chiedi_al_4:
      - "Il succo di frutta senza zuccheri alza il livello di glicemia?"

    utter_chiedi_al_5:
      - "Cucinare con l'olio d'oliva può prevenire l'aumento di colesterolo?"

    utter_chiedi_af_1:
      - "Fare regolarmente esercizio fisico può aiutare a ridurre il rischio di pressione alta?"

    utter_chiedi_af_2:
      - "Per una persona con un buon controllo glicemico l'esercizio fisico non ha effetto sul livello di zucchero nel sangue?"

    utter_chiedi_cg_1:
      - "L'emoglobina glicosilata è un test che misura la media dello zucchero nel sangue?"

    utter_chiedi_cg_2:
      - "Un'infenzione può causare un aumento della glicemia?"

    utter_chiedi_cg_3:
      - "Il test delle urine e l'analisi del sangue vanno bene entrambi per misurare il livello di zuccheri nel sangue?"

    utter_chiedi_cg_4:
      - "Quando hai l'influenza dovresti misurarti la glicemia più spesso?"

    utter_risposta_bassa_motivazione:
      - "Non molto alta, vedo..."

    utter_risposta_media_motivazione:
      - "Vedo che ci stai pensando..."

    utter_risposta_alta_motivazione:
      - "Ottimo, vedo che la tua motivazione è alta!"

    utter_introduci_health_literacy:
      - "Ora se per te va bene ti porrò alcune semplici domande. Cominciamo!"


##### ACTIONS #####
actions:
  - utter_benvenuto
  - utter_chiedi_se_pronto
  - utter_perfetto
  - utter_allora_ciao
  - utter_ringrazia
  - utter_fallback
  - utter_valore_fuori_range
  - utter_chiedi_area_intervento
  - utter_chiedi_livello_motivazione
  - utter_chiedi_self_efficacy
  - utter_chiedi_atf_1
  - utter_chiedi_atf_2
  - utter_chiedi_al_1
  - utter_chiedi_al_2
  - utter_chiedi_al_3
  - utter_chiedi_al_4
  - utter_chiedi_al_5
  - utter_chiedi_af_1
  - utter_chiedi_af_2
  - utter_chiedi_cg_1
  - utter_chiedi_cg_2
  - utter_chiedi_cg_3
  - utter_chiedi_cg_4
  - utter_risposta_bassa_motivazione
  - utter_risposta_media_motivazione
  - utter_risposta_alta_motivazione
  - utter_introduci_health_literacy
  - action_fallback
  - action_retrieve_and_set_user_id
  - action_retrieve_and_set_status_change_score
  - action_retrieve_and_set_self_efficacy_score
  - action_number_out_of_range

##### FORMS #####
forms:
  - atf_form
  - alimentazione_form
  - attivita_fisica_form
  - controllo_glicemia_form
  - intervention_area_form

```

and here is the nlu data md file, if needed:

```
## intent: comunica_self_efficacy
- [poco](valore_self_efficacy)
- [molto](valore_self_efficacy)

## intent: nega
- no
- non ancora
- non adesso
- non ora
- no, adesso no
- no, in questo momento no
- no, non mi va

## intent: rispondi_health_literacy
- [vero](risposta_health_literacy)
- [falso](risposta_health_literacy)
- [non so](risposta_health_literacy)

## intent: input_numerico
- [1](numero)
- [2](numero)
- [3](numero)
- [4](numero)
- [5](numero)
- [6](numero)
- [7](numero)
- [8](numero)
- [9](numero)
- [10](numero)
- [-1](numero)
- [-2](numero)
- [-3](numero)
- [-4](numero)
- [-5](numero)
- [-6](numero)
- [-7](numero)
- [-8](numero)
- [-9](numero)
- [-10](numero)

## intent: inizia
- ciao
- ciao lisa
- buongiorno
- buongiorno lisa
- buon pomeriggio
- buon pomeriggio lisa
- buonasera
- buonasera lisa

## intent: scegli_area_intervento
- [aderenza terapia farmacologica](area_intervento)
- sono interessato alla [aderenza terapia farmacologica](area_intervento)
- [alimentazione](area_intervento)
- mi interessano gli aspetti relativi alla [alimentazione](area_intervento)
- [attività fisica](area_intervento)
- vorrei sapere di più sulla [attività fisica](area_intervento)
- [controllo glicemia](area_intervento)
- vorrei migliorare nell'area relativa al [controllo glicemia](area_intervento)

## intent: afferma
- sì
- si
- certo
- certamente
- va bene
- va benissimo
- sì, va bene
- si, va bene
- sì, va benissimo
- si, va benissimo

## regex: numero
    - -?[0-9]{2}
```

This surprised me, since in a different part of the dialogue the form action (with same code, just referring to a different slot) seems to work flawlessly. Any help is very much appreciated. Thank you in advance
