### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Alexeijn** [RasaHQ/rasa_nlu#3136]
**Rasa CORE version**: 0.14.0a9
**Rasa NLU version**: 0.15.0a4
**Rasa CORE SDK version**: 0.13.0a1
** Tracker Store**: Redis

**Python version**: Python 3.6.8

**Operating system** DOCKER Desktop Comunity 18.09.2 running on Windows 10 PRO 1803 build 17134.648

**Issue**: TypeError: 'NoneType' object is not iterable

**Content of configuration file (nlu_config.yml)**:
```yml
language: "pt"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"
- name: "DucklingHTTPExtractor"
  url: "http://duckling:8000"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
  - oi
actions:
  - bom_dia_boa_tarde_boa_noite
  - utter_com_quem_falo
templates:
  utter_default:
    - text: "Desculpa, mas não lhe entendi."
  utter_com_quem_falo:
    - text: "Com quem falo?"
```

Tracking:
rasa_core_1       | 2019-03-24 16:39:19 ERROR    sanic.root  - Exception occurred while handling uri: 'http://localhost:5005/conversations/'
rasa_core_1       | Traceback (most recent call last):
rasa_core_1       |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 750, in handle_request
rasa_core_1       |     response = await response
rasa_core_1       |   File "/app/rasa/core/server.py", line 148, in decorated
rasa_core_1       |     result = await result
rasa_core_1       |   File "/app/rasa/core/server.py", line 363, in list_trackers
rasa_core_1       |     keys = list(app.agent.tracker_store.keys())
rasa_core_1       | TypeError: 'NoneType' object is not iterable
rasa_core_1       | [2019-03-24 16:39:19 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/conversations/'
rasa_core_1       | Traceback (most recent call last):
rasa_core_1       |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 750, in handle_request
rasa_core_1       |     response = await response
rasa_core_1       |   File "/app/rasa/core/server.py", line 148, in decorated
rasa_core_1       |     result = await result
rasa_core_1       |   File "/app/rasa/core/server.py", line 363, in list_trackers
rasa_core_1       |     keys = list(app.agent.tracker_store.keys())
rasa_core_1       | TypeError: 'NoneType' object is not iterable
