### ISSUE TITLE
Recognise entities that contain more than one word 

### ISSUE THREAD

**Issue by Nexemics** [RasaHQ/rasa_nlu#3138]
**Rasa version**:
Core - 0.12.4
NLU - 0.14.8
**Python version**: 
3.6.8
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
I would like to know how can I make the bot recognize entities that consist of more than one word aka entities that have a space between them. Eg: if my entity is city and my input is New York. Bot detects input as [New] (city) [York] (city) I want bot to detect it as [New York] (city) I also trained my bot with a lookup table that consist of all cities. But I am unsure how to make the bot ignore the space between the city names.

**Content of configuration file (config.yml)**:
```yml

```pipeline:
- name : "nlp_spacy"
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
path: "./models/nlu"
data: "./data/data.json"


```
