### ISSUE TITLE
Unable to create model with fixed name using HTTP API

### ISSUE THREAD

**Issue by tkalog** [RasaHQ/rasa_nlu#3139]
**Rasa version**: 0.14.6 (nlu)

**Python version**:  2.7

**Operating system** (windows, osx, ...): Linux Ubuntu 16.04

**Issue**:
I start the server by running: 
`python -m rasa_nlu.server --path ./models`

Then, using the HTTP API I'm trying to train a model with a fixed name with the following command: 
`curl -XPOST -H "Content-Type: application/x-yml" --data-binary @config.yml localhost:5000/train?project=current&model=my_model`

The model is created, although the name is not the one I specified (nlu) but a default one eg. model_20190321-102629

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: "spacy_sklearn"

data: |
  ## intent:abort
  - Bye
  - bye
  - I have to go

  ## intent:greet
  - Hi
  - hello

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
Not used
```
