### ISSUE TITLE
Failed to validate domain yaml

### ISSUE THREAD

**Issue by tchax3742** [RasaHQ/rasa_nlu#3141]
**Rasa version**: 0.14.5

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): linux 18.04

**Issue**: i am trying to train model and its showing validation error
![rasapic](https://user-images.githubusercontent.com/46517278/54919547-bdda2180-4f09-11e9-9dfb-7bd1ddfdcd9d.jpg)

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"                   # loads the spacy language model
- name: "tokenizer_spacy"             # splits the sentence into tokens
- name: "ner_crf"                   # uses the pretrained spacy NER model
- name: "intent_featurizer_spacy"     # transform the sentence into a vector representation
- name: "intent_classifier_sklearn"   # uses the vector representation to classify using SVM
- name: "ner_synonyms"                # trains the synonyms
```

**Content of domain file (domain.yml)** (if used & relevant):
```
       intents:
       # add your intents
       - greet
       - thanks
       - toppings_deny
       - stop
       - toppings_affirm
       - inform
       - what_is_pizza_cost
       - order_pizza
       - chitchat:
          use_entities: false
      
       entities:
       - size
       - pizzatype
       - toppings
       - num_pizza
       - number
       - feedback
      
       slots:
       size:
        type: text
       pizzatype:
        type: text
       ask_toppings:
        type: text
       toppings:
        type: text
       num_pizza:
        type: text
       feedback:
        type: text
       requested_slot:
        type: unfeaturized
      
       templates:
       utter_greet:
        - "Hey there, welcome to Tatenda's pizzabot, how can I help you"
       utter_thank:
        - "You're welcome!"
       utter_ask_size:
        - "We have small, medium, large and extra large pizzas. Which one do you want?"
       utter_ask_pizzatype:
        - "We have BBQ, Hawaiian, Bacon Cheeseburger, and Buffalo chicken pizzas, which one do you want"
       utter_ask_toppings:
        - "Do you want any toppings?"
       utter_ask_num_pizza:
        - "How many pizzas do you want"
       utter_toppings:
        -"We have mushrooms, onions, bacon, green peppers and sausage toppings, which would you like?
       utter_fallback:
        - "sorry, I did not get you"
       utter_affirm:
        -"thanks for the details.your order is being processed"
       utter_default: 
        - "sorry, i couldnt understand you.please retry"
       utter_ask_feedback:
        - text: "please give your feedback on your experience so far"
       utter_slots_values:
        - text: "You have ordered the following pizza:

             - size: {size}

             - pizzatype: {pizzatype}

             - num_pizza: {num_pizza}

             - toppings: {toppings}

             - feedback: {feedback}"
       utter_submit:
       - text: "submit"
       utter_chitchat:
       - text: "chitchat"
       utter_ask_continue:
       - text: "do you want to continue?"
       utter_wrong_size:
       - text: "We do not have that size, please try again"
       utter_wrong_pizzatype:
       - text: "We do not have that type of pizza, please choose from Hawaiian, buffalo chicken, Magherita and BBQ"
       utter_wrong_num_pizza:
       - text: "number of people should be a positive integer e.g 3, 4, please try again"
       utter_wrong_toppings1:
       - text: "Please answer with yes/no"
       utter_wrong_toppings2:
       - text: "Those toppings are currently unavailable, please choose from  mushrooms, onions, bacon, green peppers and sausage toppings "
       
       actions:
       # all the utter actions from the templates, plus any custom actions
       - utter_slots_values
       - utter_ask_continue
       - utter_chitchat
       - utter_greet
       
       forms:
       - pizza_form
   

```
