### ISSUE TITLE
botframework: Exception when trying to handle message. 'type'

### ISSUE THREAD

**Issue by selphe** [RasaHQ/rasa_nlu#3159]
**Rasa version**: 0.14.0a9

**Python version**: 3.6

**Operating system** (windows, osx, ...): CoreOS

**Issue**: 
1. Rasa core running inside docker with botframework channel. Server accessible from outside via nginx proxy.
2. At Microsoft Azure portal side, I've configured endpoint `https://servername/webhooks/botframework/webhook/` (with slash at end regarding to this issue https://github.com/RasaHQ/rasa_nlu/issues/2760)
3. I'm testing from Microsoft Azure webchat (please refer to this issue, to understand how tesing with azure webchat works: https://github.com/RasaHQ/rasa_nlu/issues/2365)
4. From webchat (azure side), I see, what the message is out
5. From rasa server, I see error:
>rasa.core.channels.botframework - Exception when trying to handle message. 'type'

Screenshot: https://i.imgur.com/v7NzXeB.png

**Content of configuration file (docker-compose.yml)**:
```yml
version: '3.0'
services:
  rasa_core:
    image: rasa/rasa_core:stable
    ports:
      - 5005:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - botframework
      - --endpoints
      - config/endpoints.yml
      - -u
      - current/
      - --credentials
      - config/credentials.yml
      - --enable_api
    networks:
      - rasa

  rasa_nlu:
    image: rasa/rasa_nlu:stable-full
    volumes:
      - ./models/rasa_nlu:/app/models
      - ./config:/app/config
    command:
      - start
      - --path
      - models
      - -c
      - config/nlu_config.yml
    networks:
      - rasa

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: <removed for security reason>
      MONGO_INITDB_ROOT_PASSWORD: <removed for security reason>
    networks:
      - rasa
    volumes:
      - ./mongodb:/data/db

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <removed for security reason>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <removed for security reason>
    networks:
      - rasa

networks:
  rasa:
    ipam:
      driver: default
      config:
        - subnet: <removed for security reason>

```

**Content of domain file (endpoint.yml)** (if used & relevant):
```yaml
nlu:
  url: http://rasa_nlu:5000

tracker_store:
  store_type: mongod
  url: mongodb://mongo:27017
  username: <removed for security reason>
  password: <removed for security reason>

```

**Content of domain file (endpoint.yml)** (if used & relevant):
```yaml
botframework:
  app_id: "<removed for security reason>"
  app_password: "<removed for security reason>"

```
