### ISSUE TITLE
TwoStageFallback policy doesn't end with "I don't provide this skill"

### ISSUE THREAD

**Issue by huberrom** [RasaHQ/rasa_nlu#3160]
**Rasa version**: 0.13.2

**Issue**: Using TwoStageFallback policy, the first time I say that it's "Something else", it asks me to rephrase, which is good. But the second time I press the button "Something else", the action 'action_default_ask_affirmation' is called again, but only with the intent out_of_scope (hors_perimetre in french) with confidence 1.0. 

I was expecting that the out_of_scope action would be called instead of action_default_ask_affirmation. Is this the default behavior ? If so, I can override the action_default_ask_affirmation but I want to be sure first

**Content of configuration file (config.yml)**:
```yml
policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 10
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.7
    core_threshold: 0.3
    fallback_nlu_action_name: "action_default_ask_affirmation"
    fallback_core_action_name: "action_default_ask_affirmation"
    deny_suggestion_intent_name: "hors_perimetre"
  - name: AugmentedMemoizationPolicy
    max_history: 10
```

**Comment by huberrom** [comment]
Maybe I should add that I overrided "action_default_ask_affirmation" to this :

```
class ActionDefaultAskAffirmation(Action):
    """Asks for an affirmation of the intent if NLU threshold is not met."""

    def name(self):
        return "action_default_ask_affirmation"

    def __init__(self) -> None:
        import csv

        self.out_of_scope_intent = "hors_perimetre"

        self.intent_mappings = {}
        with open(INTENT_MAPPING_CSV_PATH,
                  newline='',
                  encoding='utf-8') as file:
            csv_reader = csv.reader(file)
            for row in csv_reader:
                logger.info("ROW IS %s", row)
                self.intent_mappings[row[0]] = row[1]

    def run(self, dispatcher, tracker, domain):

        intent_ranking = tracker.latest_message.get('intent_ranking', [])
        if len(intent_ranking) > 1:
            diff_intent_confidence = (intent_ranking[0].get("confidence") - intent_ranking[1].get("confidence"))
            if diff_intent_confidence < 0.2:
                intent_ranking = intent_ranking[:2]
            else:
                intent_ranking = intent_ranking[:1]

        logger.info("Intent ranking : %s", intent_ranking)
        first_intent_names = [intent.get('name', '')
                              for intent in intent_ranking
                              if intent.get('name', '') != self.out_of_scope_intent]

        message_title = extract_text(request_response_faq("proposition_intentions",
                                                          get_sender_id(tracker), dispatcher))

        mapped_intents = [(name, self.intent_mappings.get(name, name))
                          for name in first_intent_names]

        entities = tracker.latest_message.get("entities", [])
        entities_json, entities_text = get_formatted_entities(entities)

        buttons = []
        for intent in mapped_intents:
            buttons.append({'title': intent[1] + entities_text,
                            'payload': '/{}{}'.format(intent[0],
                                                      entities_json)})

        buttons.append({'title': self.intent_mappings.get(self.out_of_scope_intent),
                        'payload': '/' + self.out_of_scope_intent})

        dispatcher.utter_button_message(message_title, buttons=buttons)

        return []
```

Not a lot of change, just some call to a CMS to get the text in french

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon.

**Comment by huberrom** [comment]
Oook sorry for the issue, but after reading the policy, I noticed this :

```
        Args:
            nlu_threshold: minimum threshold for NLU confidence.
                If intent prediction confidence is lower than this,
                predict fallback action with confidence 1.0.
            core_threshold: if NLU confidence threshold is met,
                predict fallback action with confidence
                `core_threshold`. If this is the highest confidence in
                the ensemble, the fallback action will be executed.
            fallback_core_action_name: This action is executed if the Core
                threshold is not met.
            fallback_nlu_action_name: This action is executed if the user
                denies the recognised intent for the second time.
            deny_suggestion_intent_name: The name of the intent which is used
                 to detect that the user denies the suggested intents.
```

So I changed my policy to this :

```
policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 10
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.7
    core_threshold: 0.3
    fallback_nlu_action_name: "action_hors_perimetre"
    fallback_core_action_name: "action_default_ask_affirmation"
    deny_suggestion_intent_name: "hors_perimetre"
  - name: AugmentedMemoizationPolicy
    max_history: 10
```

And now it's working.
So fallback_nlu_action_name is the action called when the user denies the second time, and the fallback_core_action_name is the action called to propose the recognized intents. Wasn't clear to me with the doc, but working like a charm now
