### ISSUE TITLE
latest docker image was broken

### ISSUE THREAD

**Issue by GaleLQ** [RasaHQ/rasa_nlu#3172]
**Rasa version**:
rasa/rasa_nlu: latest
**Python version**: 
3.7
**Operating system** (windows, osx, ...):
mac 10.14.3
**Issue**:
i always use latest version in docker,but i updated today,an error happened,the message is  usage: run.py [-h] -d CORE [-u NLU] [-v] [-vv] [--quiet] [-p PORT]
nlu_1       |               [--auth_token AUTH_TOKEN] [--cors [CORS [CORS ...]]]
nlu_1       |               [--enable_api] [-o LOG_FILE] [--credentials CREDENTIALS]
nlu_1       |               [-c CONNECTOR] [--endpoints ENDPOINTS] [--jwt_secret JWT_SECRET]
nlu_1       |               [--jwt_method JWT_METHOD]
nlu_1       | run.py: error: the following arguments are required: -d/--core
,there are nothing in the offical document about this argument,who can tell me why?thanks

**Content of configuration file (config.yml)**:
```yml
language: en
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "DucklingHTTPExtractor"
    url: "http://duckling:8000"
    dimensions: ["time", "number", "amount-of-money", "distance"]
    locale: "en-US"
    timezone: "Europe/Berlin"
  - name: "CRFEntityExtractor"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
no
```
