### ISSUE TITLE
Not able to leveraging Intent classification

### ISSUE THREAD

**Issue by mjordan007** [RasaHQ/rasa_nlu#3183]
**Rasa version**:
0.14.6
**Python version**: 
3.6.5
**Operating system** (windows, osx, ...):
windows
**Issue**:

E.g. Let’s say my intent name is DetectItem. Examples will be I have a Mango I have a Chair Do you need Coffee

Here, I’ll map Mango, Chair and Coffee to an entity called @Item. Now, my @Item entity will be like below. 
**Fruit** - Mango, Banana, Pineapple, Apple 
**Furniture** - Chair, Table, Cupboard Drink - Coffee, Tea

Please note that there is only one entity here called @Item which will have values as Fruit, Furniture and Drink. Mango, Banana etc. would be synonyms for Fruit. Similarly, Chair, Table would be synonym for Furniture and so on.

Now with the above, setup. If I ask “Where is my tea”, Response should be Intent - DetectItem Entity - Item EntityValue - Tea.

Also, please note that the example I gave above is pretty general but in my case it would be completely different(custom) values and those values won’t be common or well-known values. That being said, any general dictionaries won’t help and I have my own dictionary as I mentioned.

I don’t want to provide an example for every possible sentence structure for every entity. Just a few so the model is aware of it. That should directly extract the entity values from the list using lookup and PR.  Entity extraction works fine.  

**My Concerns is I am not able to leverage Intent classification**. If I added an example with entity value the same template asked then Intent classification works well. However, when I asked using synonyms values then wrong intent classified. What should be the approach to leverage Intent classification? 

Many thanks in advance.

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```
