### ISSUE TITLE
Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore.

### ISSUE THREAD

**Issue by HovHak** [RasaHQ/rasa_nlu#3201]
**Rasa version**: 13.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**: I am keep getting this issue i don't understand how to configure it manually just like it asks me to, I have tried to configure the rasa policy to resolve this but no effect so far, please help

**Content of configuration file (config.yml)**:
```yml
 language: "en"

 pipeline:
 - name: "nlp_spacy"
   model: "en"
 - name: "tokenizer_spacy"
 - name: "ner_crf"
 - name: "intent_featurizer_spacy"
 - name: "intent_classifier_sklearn"
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
    - schedule_meeting
    - search_for_meeting
    - greet

entities:
    - meeting
    - time

slots:
    size:
         type: text
    toppings:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_ask_meeting_day:
        - 'What time would you like me to schedule your meeting?'
    utter_ask_meeting_time:
        - 'What time would you like me to schedule your meeting?'
    utter_get_meeting_time_place:
        - 'here are your meetings for today'
actions:
    - utter_greet
    - utter_ask_meeting_time
    - utter_ask_meeting_day
    - utter_get_meeting_time_place
    - actions.ActionShowMeeting
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
```
**Content of dialogue.py **:
```yml
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals


import logging
from rasa_core.agent import Agent
from rasa_core.domain import Domain
from rasa_core.featurizers import MaxHistoryTrackerFeaturizer, BinarySingleStateFeaturizer
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
    logging.basicConfig(level='INFO')
    dialog_training_data_file = './data/stories.md'
    path_to_model = './models/dialogue'
    # domain = Domain()
    featurizer = MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer(), max_history=5)
    agent = Agent('chat_domain.yml',  policies=[MemoizationPolicy(max_history=5),
                        KerasPolicy(featurizer)])

    agent.train(
        dialog_training_data_file,
        augmentation_factor=50,
        max_history=2,
        epochs=500,
        batch_size=10,
        validation_split=0.2)
    agent.persist(path_to_model)
```
