### ISSUE TITLE
Rasa takes all available GPU memory (inference)

### ISSUE THREAD

**Issue by neil-119** [RasaHQ/rasa_nlu#3203]
**Rasa version**: 0.14.6

**Python version**: 3.6.3

**Operating system**: Ubuntu 18.04

**Issue**:
When we start an agent like so:
```python
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.utils import EndpointConfig

interpreter = RasaNLUInterpreter('models/current/nlu')
agent = Agent.load('models/dialogue', interpreter=interpreter, action_endpoint=EndpointConfig(url="http://localhost:5055/webhook"))
```
It loads up TensorFlow, which goes on (by default) to hog all available GPU memory:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
| 41%   37C    P2    64W / 260W |  10729MiB / 10986MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1423      G   /usr/lib/xorg/Xorg                            18MiB |
|    0      1553      G   /usr/bin/gnome-shell                          58MiB |
|    0      2127      G   /usr/lib/xorg/Xorg                           131MiB |
|    0      2272      G   /usr/bin/gnome-shell                         108MiB |
|    0      8550      G   ...quest-channel-token=9868978255989529958    44MiB |
|    0      9277      C   python                                     10363MiB |
+-----------------------------------------------------------------------------+
```
This prevents other ML models from being able to load on the same system. The solution to this problem is to enable `allow_growth` (see [here](https://www.tensorflow.org/guide/using_gpu))
```python
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config, ...)
```
However, how can we get access to the TensorFlow session being used?

**Content of configuration file (config.yml)**:
```yml
language: en

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_duckling_http"
  url: "http://localhost:8000"
  dimensions: ["time", "number", "amount-of-money", "distance", "duration", "temperature", "volume", "phone-number"]
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
```

**Comment by akelad** [comment]
@neil-119 i wouldn't suggest using a GPU with that, it's unnecessary. The pipeline you're using doesn't use tensorflow at all btw (i also won't suggest it even if you switch to the tensorflow pipeline)

**Comment by neil-119** [comment]
Hi, yes as you can see, I am not using TensorFlow in my pipeline, but I assumed that the underlying LSTM model being trained with the Keras policy was using TensorFlow. Here's my policies.yml:

```yaml
policies:
  - name: KerasPolicy
    epochs: 151
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
```

Now, when the trained model is loaded by Rasa for inference / production use, it appears to initialize a TensorFlow session without the `allow_growth` flag. With TensorFlow, a session initialized that way uses all available GPU memory by default.
