### ISSUE TITLE
OSError: [E050] Can't find model 'None'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by LKiera** [RasaHQ/rasa_nlu#3207]
**Rasa version**:0.1.1

**Python version**: 3.7

**Operating system** (windows, osx, ...):MacOS

**Issue**:

Traceback (most recent call last):
  File "nlu_model.py", line 18, in <module>
    run_nlu()
  File "nlu_model.py", line 13, in run_nlu
    interpreter = Interpreter.load('./models/nlu/default/clgnlu')
  File "/usr/local/lib/python3.7/site-packages/rasa_nlu/model.py", line 293, in load
    skip_validation)
  File "/usr/local/lib/python3.7/site-packages/rasa_nlu/model.py", line 320, in create
    model_metadata, **context)
  File "/usr/local/lib/python3.7/site-packages/rasa_nlu/components.py", line 419, in load_component
    cached_component, **context)
  File "/usr/local/lib/python3.7/site-packages/rasa_nlu/registry.py", line 133, in load_component_by_name
    return component_clz.load(model_dir, metadata, cached_component, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rasa_nlu/utils/spacy_utils.py", line 126, in load
    nlp = spacy.load(model_name, parser=False)
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'None'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Content of configuration file (config.yml)**:
```yml
haven't created any yet! As I am just aiming for NLU
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
slots:
  gender:
    type: text
  course:
    type: text

intents:
 - greet
 - goodbye
 - admission
 - hostel


entities:
 - gender
 - course

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_course:
    - 'In which course?'
  utter_ask_gender:
    - 'Are you a boy or a girl?'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_course
 - utter_ask_gender
 - action_admissioninfo
 - action_hostelinfo

```
