### ISSUE TITLE
Rasa - Resolving environment variables on the fly

### ISSUE THREAD

**Issue by pchristos** [RasaHQ/rasa_nlu#3216]
**Rasa version**: 0.13.7

**Python version**: 3.6.6

**Operating system**: debian/jessie

**Issue**:

1. Assume the environment variable `DUCKLING_URL` is set to `http://duckling-1:8000`
2. A model is trained
3. Rasa can reach Duckling at `http://duckling-1:8000`
4. `DUCKLING_URL` is updated to `http://duckling-2:8000` on the spot
5. Rasa **still** reaches Duckling at `http://duckling-1:8000`

It seems like environment variables are resolved when training the ML model (?). Is this intended? Is there any particular reason that prohibits the code from resolving environment variables on the fly? How can I make `DUCKLING_URL` configurable per environment, **without** the need to re-train my model. Am I missing something here?

**Content of configuration file (config.yml)**:
```yml
language: "en"                                                                  
                                                                                                                                                                
pipeline:                                                                       
- name: "tokenizer_whitespace"                                                  
- name: "ner_crf"                                                               
- name: "ner_duckling_http"                                                     
  url: ${DUCKLING_URL}                                                          
  locale: "en_GB"                                                               
  timezone: "UTC"                                                               
  dimensions:                                                                   
  - time                                                                           
  - number                                                                      
  - ordinal                                                                     
  - duration                                                                    
- name: "ner_synonyms"                                                          
- name: "intent_featurizer_count_vectors"                                       
- name: "intent_classifier_tensorflow_embedding"                                
```
