### ISSUE TITLE
    ('instruction', '')   # user instructions for select, rawselect, checkbox TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by sushilr007** [RasaHQ/rasa_nlu#3233]
**Rasa version**: 0.13.7

**Python version**: 3.6.5

**Operating system** (windows 8):

**Issue**:  I am trying to fire this command "python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c config.yml" I tried many  possibilities but dont know why it is getting wrong.
Please help me
Thnak you.

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline:
 - name: "nlp_spacy"
   model: "en"
 - name: "tokenizer_spacy"
 - name: "ner_crf"
 - name: "intent_featurizer_spacy"
 - name: "intent_classifier_sklearn"

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy





```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
  intents:
      - greet
      - PF_UAN_Number
      - Update_Bank_Account
      - Update_Mobile_Number
      - Update_PAN
      - Update_Name
      - previous_PF_number
      - reason_No_Salary
      - Update_Date_of_Birth
      - Experience_Relieving_letter
      - Offer_letter
      - Less_salary
      - form_16
      - Permanent_ID_Card
      - Promotion_letter
      - Maternity_Leave_Benefits
      - Leave_Policy
      - paternity_leave
      - Regularize_LOP
      - leave_Child_birth
      - Miscarriage_Medical_termination_of_pregnancy
      - Tubectomy_operation
      - Apply_for_leaves
      - Book_transportation_Drop
      - apply_Mobile_Reimbursement
      - fill_appraisal



  templates:
      utter_greet:
          - 'Hello, how can I help you?'
          - 'Hi, I am here to help.'
      utter_PF_UAN_Number:
          - 'How can I update my PF number?'
      utter_Update_Bank_Account:
          - 'How can I update my bank account?'
      utter_Update_Mobile_Number :
          - 'How can update my mobile number?'
      utter_Update_PAN :
          - 'How can I update my pan number?'
      utter_Update_Name:
          - 'How can I update my name?'
      utter_previous_PF_number :
          - 'How  can I continue with my previous PF number?'
      utter_reason_No_Salary :
          - 'I havent received my salary how could I know the reason?'
      utter_Experience_Relieving_letter:
          - 'How can I get my experience / relieving letter?'
      utter_Offer_letter :
          - 'How can I get my offer letter?'
      utter_Less_salary:
          - 'I have received less salary ,how could this happen?'



  actions:
      - utter_greet
      - action_db

  policies:
      - 'KerasPolicy'
      - 'MemoizationPolicy'

```
