### ISSUE TITLE
what should i use the look up table？

### ISSUE THREAD

**Issue by Duyshg** [RasaHQ/rasa_nlu#3236]
**Rasa version**:rasanlu 0.13.7

**Python version**: 3.6

**Operating system** (windows, osx, ...):Windows10

**Issue**:
when i tran the rasa nlu ，i got a problem ：UnicodeDecodeError: 'gbk' codec can't decode byte 0x97 in position 728: illegal multibyte sequence
i want know does the look up table support Chinese?

**Content of configuration file (config.yml)**:
```yml
pipeline:
- name: tokenizer_jieba
- name: tokenizer_whitespace
- name: ner_crf
- name: intent_featurizer_count_vectors
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: intent_entity_featurizer_regex
- name: intent_classifier_tensorflow_embedding
  epochs: 200

#- name: ner_duckling_http
#  url: http://localhost:8000
#  dimensions:
#  - email
#  - number
#  - amount-of-money
- name: ner_synonyms
language: zh

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```
