### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by karthikbalu** [RasaHQ/rasa_nlu#3238]
**Rasa version**:
rasa-nlu            0.14.6 
rasa-core           0.13.7 
rasa-core-sdk       0.12.2   

**Python version**: 
3.6.5

**Operating system** (windows, osx, ...):
MacOSx, Linux both OS has this issue

**Issue**:
I was able to train nlu and core without any issues but when i test it using REST as well as cli channel i get the following error

`
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  hi                                                                                                                                            
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 324, in on_message_wrapper
    on_new_message(message)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/agent.py", line 303, in handle_message
    return processor.handle_message(message)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 80, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 300, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 161, in predict_next_action
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 473, in _get_next_action_probabilities
    tracker, self.domain)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 321, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/policies/fallback.py", line 97, in predict_action_probabilities
    nlu_confidence = nlu_data["intent"].get("confidence", 1.0)
AttributeError: 'NoneType' object has no attribute 'get'
`

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: spacy_sklearn
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
actions:
  - utter_unclear
  - utter_greet
intents:
  - greeting
templates:
  utter_unclear:
    - text: "Sorry i dont know"
    - text: "I dont know"
    - text: "I didnt get it"
  utter_greet:
    - text: "hi how are you"
    - text: "great thanks"
    - text: "how are you"
```

**Content of domain file (nlu_data.md)** (if used & relevant):
```md
## intent:greeting <!--- The label of the intent --> 
- hi
- hello
- hey
- hi hi
- hey hey
- hey hi
```

Please let me know
