### ISSUE TITLE
Not able to train more than 10 intents.

### ISSUE THREAD

**Issue by sushilr007** [RasaHQ/rasa_nlu#3240]
**Rasa version**:0.13.7

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): win 8

**Issue**:

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline:
 - name: "nlp_spacy"
   model: "en"
 - name: "tokenizer_spacy"
 - name: "ner_crf"
 - name: "intent_featurizer_spacy"
 - name: "intent_classifier_sklearn"

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
  intents:
      - greet
      - PF_UAN_Number
      - Update_Bank_Account
      - Update_Mobile_Number
      - Update_PAN
      - Update_Name
      - previous_PF_number
      - reason_No_Salary
      - Update_Date_of_Birth
      - Experience_Relieving_letter
      - Offer_letter
      - Less_salary
      - form_16
      - Permanent_ID_Card
      - Promotion_letter
      - Maternity_Leave_Benefits
      - Leave_Policy
      - paternity_leave
      - Regularize_LOP
      - leave_Child_birth
      - Miscarriage_Medical_termination_of_pregnancy
      - Tubectomy_operation
      - Apply_for_leaves
      - Book_transportation_Drop
      - apply_Mobile_Reimbursement
      - fill_appraisal



  templates:
      utter_greet:
          - 'Hello, how can I help you?'
          - 'Hi, I am here to help.'

  actions:
      - utter_greet
      - action_db
![action](https://user-images.githubusercontent.com/35765579/55952760-fef76300-5c77-11e9-9394-4b75a0caedf8.png)
![commnad](https://user-images.githubusercontent.com/35765579/55952993-952b8900-5c78-11e9-96f3-45dcac439210.png)


![nlu_model](https://user-images.githubusercontent.com/35765579/55952540-7e386700-5c77-11e9-8db2-c0fb9f398da2.png)
![stories](https://user-images.githubusercontent.com/35765579/55952542-7e386700-5c77-11e9-91eb-f3f0b4216e41.png)


```
