### ISSUE TITLE
Actions not updating in interactive learning,when i try to use same intent again its not remembering the action to be performed..

### ISSUE THREAD

**Issue by garchaaman19** [RasaHQ/rasa_nlu#3250]
**Rasa version**:
rasa-core                          0.13.7   
rasa-core-sdk                      0.12.2   
rasa-nlu                           0.14.6  

**Python version**: 
3.6.0

**Operating system** (windows, osx, ...):
Kali linux 2019

**Issue**:

The intents are not getting updated in interactive learning when i try to run the same intent again after i have corrected it, It still does not classify it properly.
i have seen similar issue on #2636 
But i have not got the clear answer on what to do ?

and also i get error after interacting learning
ValueError: Could not locate the resource '/root/rasa_chatbot2/data/nlu.md'
But its automatically creating file nlu_interactive.md

**Content of configuration file (config.yml)**:
```yml
{
"pipeline":"spacy_sklearn",
"path":"./models/nlu",
"data":"./data/data.json"
}
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

slots:
   stream:
      type: text


intents:
 - new_admission
 - greet
 - goodbye
 - affirm
 - intro
 - events
 - health
 - entrance_exam
 - question_paper_entrance
 - college_timings
 - calculate_distance
 - abusive
 - out_of_scope

entites:
 - stream
 - location

templates:
  utter_greet:
   - 'Hello how can i help you'
   - 'Hey there'
   - 'Hi how can i help you'
   - 'Hi buddy'
   - 'hello'
   - 'hey buddy'
  utter_goodbye:
   - 'ok bye :('
   - 'bye have a nice day'
   - 'bye talk to you later'
   - 'bye have a nice day'
   - 'have a good day ahead'
  utter_affirm:
   - 'okayy'
   - 'cool'
   - 'chill'
   - 'i got that'
  utter_intro:
   - 'I am a chatbot to answer your queries related to college admission,placements,fees,etc'
   - 'I am a chatbot created by HARVINDAR SINGH GARCHA to answer queries related to college'
  utter_events:
   - 'We have a good record of conducting co-curricular activities'
   - 'We have big events as well as separated department events'
   - 'Co-curricular activities in our college help students to reduce study load which are organized properly every year'
  utter_health:
   - 'I am good Buddy,you say'
   - 'I am doing well today'
   - 'Life is always good'
   - 'I am fine'
   - 'I am cool'
  utter_entrance_exam:
   - 'Please keep checking the dates on website we will update it soon'
  utter_question_paper_entrance:
   - 'All the question papers of previous year question papers can be found on www.modencollege.edu'
  utter_ask_stream:
   - 'Please specify me the stream'
   - 'Please tell me the stream such as mba,bcs,mcs,bcom,mcom,bba '
  utter_default:
   - 'Sorry I am not trained Yet to do that,For More information Please Keep Checking The College Website '
  utter_abusive:
   - 'Please be polite to me.'

actions: 
 - utter_greet
 - utter_goodbye
 - utter_abusive
 - utter_affirm
 - utter_events
 - utter_health
 - utter_entrance_exam 
 - utter_question_paper_entrance
 - utter_college_timings
 - utter_intro
 - utter_ask_stream
 - admission_mcs
 - admission_bcs
 - admission_bba
 - admission_mba
 - admission_bcom
 - admission_mcom
 - fees_mcs
 - fees_bcs
 - fees_mba
 - fees_bba
 - fees_bcom
 - fees_mcom
 - placement_bcs
 - placement_mcs
 - placement_bcom
 - placement_mcom
 - placement_bba
 - placement_mba
 - timing_mba
 - timing_bba
 - timing_bcom
 - timing_mcom
 - timing_mcs
 - timing_bcs

```
